### ISSUE TITLE
no alert for missing income determination

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1007]
When record has no income determination, there is an error state. However, no error is displayed. Figure out some way to display this error state to the user 

@RyanHansz should this do the same thing we do for missing enrollment/funding ? i.e. display a banner error alert

**Comment by RyanHansz** [comment]
<img width="1186" alt="Screen Shot 2021-01-08 at 9 08 14 AM" src="https://user-images.githubusercontent.com/63253539/104024400-0d4a1a00-5191-11eb-994c-78f10d527191.png">
I'm seeing this error alert - is there a certain scenario where it doesn't show up?

**Comment by jlhogan** [comment]
if theres no income det, that generic error banners how sat the top, but theres nothing that indicates what the error is (that an income determination -- w/ info or "not disclosed") is required

**Comment by RyanHansz** [comment]
@jlhogan we had designs for improving the missing enrollment scenario in #487, so I added missing income to that ticket.

**Comment by jlhogan** [comment]
I feel like perhaps it should be in a different bucket than that -- we at least have a stopgap for the enrollment/funding stuff  (the additional, specific error banner that says what's wrong). I think we should do the same here, and change the language that says "redetermine" to "add an income determination" or something like that

**Comment by RyanHansz** [comment]
A quick fix alert wise:
**IF only income is missing:**
This record is missing income information
Records must have an income determination for OEC reporting. Add funding info in the family income section.

**IF income and other fields are missing:**
This record has missing or incorrect info
Add required info in child info, and add a family income determination before submitting your data to OEC.

For the section:
Change "redetermine" to "add an income determination"

**Comment by JordanGuinn** [comment]
Current UX _seems_ to address this (screenshot below).  Maybe we close it now?

![Screen Shot 2021-04-15 at 9.21.56 AM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/2ee21c91-b282-4083-b859-62b04115aefe)

**Comment by jlhogan** [comment]
yup!
