### ISSUE TITLE
Spreadsheet upload: As a person updating data, I can upload a new spreadsheet with my latest enrollments.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#101]
## Background
As a user, I can upload a file containing new enrollment records, as well as changes to my existing roster, preview those changes, and opt to cancel the upload or save them to my roster.

### [Designs](https://share.goabstract.com/075833a6-f13d-4626-840e-38479241cadd)

**_NOTE:_** This should receive a test/design review prior to completion/merge/deploy.

## Acceptance Criteria
- I can upload a spreadsheet that will update existing records, add new records, and withdraw old records. Update types include:
  - aged up
  - changed site
  - changed funding
  - new
  - withdrawn
  - income determination
  - edited (i.e. added birth cert)
- ECE Reporter will detect if my upload contains data for existing records, identified as those with perfect child ID matches
  - If birth cert didn't exist before, but does in the new upload, match if DOB + name match, and update with birth cert data
- For now, only edits supported will be:
  - adding birth cert info if it doesnt exist (changing from "Unavailable" to some other birth cert type is supported)
  - adding/editing family address
  - any edits not captured in one of the above "update types" will not be handled yet, and will result in new entities being created (that is, changing site or entry/exit of existing enrollment results in new enrollment, changing funding first/last reporting period or funding space results in new funding, changing existing income determination information results in new income determination)
- API response needs to contain some data structure representing the uploaded data, augmented with the upload type of each record
- User is still able to upload a file with historical enrollments (**IS THIS TRUE?**) so the data structure may not map exactly to the incoming sheet (i.e. there may be multiple rows for a single child)
  - If historical records included in upload, they should end up in the response data structure as a single row with multiple update type tags (i.e. new and changed site)
- I no longer need to choose which site to replace data for, since my file upload will have that information already
  - as a result, deleting roster data is no longer part of file upload in backend

**Comment by RyanHansz** [comment]
If we switch new components to Carbon, here's the progress indicator included in these designs:
https://www.carbondesignsystem.com/components/progress-indicator/usage/

**Comment by bamader** [comment]
`API response needs to contain some data structure representing the uploaded data, augmented with the upload type of each record`
Is this data structure what's going to be used for the other ticket with the "upload wizard"? I don't quite understand why having a structure augmented with the type of action performed (new record, edited record, whatever) is necessary for the work in this ticket specifically. All the other bullets in the AC make perfect sense, but that one I'm not sure I get.

**Comment by jlhogan** [comment]
yeah, i guess we could separate that out into the other ticket but i just wanted to make sure we ingest + parse this uploadin a way where that eventual out come is possible. would suck to build this, and then have tototally reengineer it to account for that very near future requirement.

**Comment by bamader** [comment]
Gotcha. I figured it was a "keep this in mind as you're designing" point. Shouldn't be hard to engineer that kind of structure concurrently with this PR, but wanted to make sure I wasn't missing something dumb about why we'd need the data structure to identify existing records.

**Comment by jlhogan** [comment]
no the data structure is a necessary desired output, not an input
