### ISSUE TITLE
Two save buttons in batch editing

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1011]
## Background
In dev secure, when adding info to records I see two save buttons:
<img width="440" alt="Screen Shot 2021-01-08 at 9 38 09 AM" src="https://user-images.githubusercontent.com/63253539/104027388-51d7b480-5195-11eb-8d69-fc54e8019bcc.png">

## Acceptance Criteria
- Only one `Save` button should exist when batch editing

**Comment by JordanGuinn** [comment]
Closing - duplicate of the more accurate https://github.com/ctoec/data-collection/issues/1235
