### ISSUE TITLE
Large roster counts are inaccurate until all records have been loaded

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1012]
## Background
Currently, when my roster has many records, the total enrollment numbers and number of records with missing info continually update until all records are loaded.

## Acceptance Criteria
- **If this isn't slow**, the enrollment list response includes a total count of records within and is displayed on the page
- **If the above is slow**, there is some sort of loading indicator blocking the record count until that information is available
- The totals persist instead of being reloaded every time I load my roster

## Designs
Current state:

https://user-images.githubusercontent.com/63253539/104027782-e2ae9000-5195-11eb-85c5-858417841700.mp4

**Comment by jlhogan** [comment]
A nice-to-have i'd been thinking about would be updating the way the alerts hook works to not ALWAYS scroll to top of window when there are alerts https://github.com/ctoec/data-collection/blob/base/client/src/hooks/useAlerts.tsx#L23, as this results in the user beingpulled to top of page on every API page load

(not sure what the fix here should be, and if nothing ends up being obvious/easy, then this can abso be considered out of scope. But i imagine could be achieved by wrapping the provided `setAlerts` func in a wrapper func, moving the call to `window.scrollTo` into there, and maybe  taking an additional flag as a param in wrapper func to indicate when to skip the scroll? -- that's just an idea off top of my head. dunno.)

**Comment by JordanGuinn** [comment]
Closing and holding on, in favor of the upcoming roster redesign work.
