### ISSUE TITLE
Only show valid funding period options based on enrollment date

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1014]
## Background
Funding period options for enrollments across the application should be limited to what's possible given the corresponding enrollment.  For example, an enrollment starting in September 2020 shouldn't have anything before September 2020 as a funding period option (since it would result in an error).

## Acceptance Criteria
- Available funding options for enrollments should not include funding periods that begin before the enrollment start date

**Comment by JordanGuinn** [comment]
Reporting periods aren't gonna be a thing anymore - deleting this.
