### ISSUE TITLE
Add e2e test(s) for submitting a completed roster

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#1018]
## Background
We should add additional automated test coverage for the submission of a completed roster, one of the more important flows we have in the application.

## Acceptance Criteria
- e2e test(s) exist to cover submission of a completed roster
- Test(s) should include the following:
  - upload a file
  - submit roster using the button at the bottom
  - check that the submitted alert appears
  - go to home screen and check that the post-submit version of home appears

**Comment by JordanGuinn** [comment]
The notion of ever submitting a completed roster was only a one-time thing, so I think we're safe to skip any additional automated testing for that work moving forward.
