### ISSUE TITLE
Show changes: As a person updating data, I can see changes to specific data fields from the last report's data.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#102]
## Background
As a person updating data, I can see changes to specific data points from the last report's data.

## Acceptance Criteria
After upload a file with records and resolving any errors and/or unmatched records, I can:
- See a summary of total records affected, withdrawn, added and edited
- See a roster preview of all the changes
- On hitting upload, all of the changes are added to my existing roster.
- On returning to my roster after successfully uploading a file, I see a confirmation alert with the text:
"Your records have been uploaded!
You uploaded 5 new enrollments, withdrew [#] and edited [#] enrollments."

## Designs
![6 1 Batch Upload – Upload data Copy](https://user-images.githubusercontent.com/63253539/102379676-18949600-3f95-11eb-9dae-84032b974388.png)

**Comment by jay-finch** [comment]
Does Emily have everything she needs from this?

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 You two wanna keep this ticket around, or close it in favor of any future tickets created for similar redesign work (for which I believe there are already designs underway)?

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 Follow-up ping to check and see if either of you see any reason that we should hold onto this ticket?

**Comment by ehuang525** [comment]
I believe this is captured in the current file upload designs. I saved the screenshot and details for my own references but I'm good to close it.
