### ISSUE TITLE
Post-verify Home page issues

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1022]
- Homepage stuck in endless loading when the user navigates away from the page and returns

- "Your data is complete" header should be removed 
<img width="850" alt="Screen Shot 2021-01-12 at 11 28 35 AM" src="https://user-images.githubusercontent.com/63253539/104342886-5075f700-54c9-11eb-8f8c-c779a98ede52.png">

**Comment by jlhogan** [comment]
let's prioritize fixing the endless loading state and get that merged ASAP to make base deployable

**Comment by bamader** [comment]
Fix incoming
