### ISSUE TITLE
Hide School Readiness space totals, only show enrolled #

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1028]
Value: 
Avoid user confusion when their School Readiness spaces have changed over the data collection period.

Instead of ##/##, just show ## enrolled.

Includes 
- Home page (pre and post verified data)
- Roster

**Comment by jlhogan** [comment]
I _believe_ this can be accomplished by updating SR capacity #s to -1 in the DB.

**Comment by jlhogan** [comment]
updated by running ```update funding_space set capacity = -1 where source in ('PSR', 'CSR');```
to restore capacities, we can look at value from older version of the record
