### ISSUE TITLE
Post-data-submit home page needs to have an h1 and page title

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/data-collection#1029]
With the merge of the roster infinite query bug fix, there are now only h2s on this page. It needs to have at least one h1 and the title should match, or at least closely reflect, the contents of the h1.

**Comment by jlhogan** [comment]
@RyanHansz can the h1 header /title be the same in the post submit homepage as in the pre-submit? I.e. just `Hello, Username` ?

**Comment by RyanHansz** [comment]
I'd prefer for it to be the org name

**Comment by bamader** [comment]
For users with multiple orgs (which I think is just one case), what should we make the h1? Initially we had the org names be h1's but Melanie raised an accessibility issue that pages should have only 1 h1, which is where the "Hello, username" repeat suggestion came from.

**Comment by jlhogan** [comment]
If my vote counts any, it's for `Hello, Username` at least just for now. makes our lives way easier. Orgs can be listed right below (as they are now) as H2.

**Comment by RyanHansz** [comment]
Okay, here's some spacing values for that option:
<img width="680" alt="Screen Shot 2021-01-20 at 1 25 03 PM" src="https://user-images.githubusercontent.com/63253539/105218271-f1486000-5b22-11eb-8796-c88d34aa4adc.png">

**Comment by jlhogan** [comment]
thank you !!!!
