### ISSUE TITLE
Record types: As a person updating data from a spreadsheet, all of the changes I've made can be identified by the data tool.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#103]
After I upload a spreadsheet to Fawkes, the tool is able to detect all the changes I've made to all fields. 
- If I update all fields in income determination - add a new income determination record
- If I only update one of the income determination fields - add the new info to the existing income determination
- If I add a new enrollment/funding, create a new enrollment record on the child's record
- Ensure we save the history for all fields changed (in case a user accidentally messes up all their data)
- Categorize each record as "new/withdrawn/edited" to be used on the update preview

**Comment by jlhogan** [comment]
closing as dupe
