### ISSUE TITLE
As an OEC decision-maker, I can use ECE Enrollment data to answer key legislator and policy questions

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1045]
<img width="628" alt="Screen Shot 2021-01-14 at 10 30 13 AM" src="https://user-images.githubusercontent.com/63253539/104611781-7e874280-5653-11eb-83d8-6ffd042ecf64.png">

# [See exploratory designs here](https://share.goabstract.com/c1d1bf1a-90e2-4809-8ce7-03d4634125f2) 

# Hypothesis:
If OEC decision-makers have access to well-visualized state-funded ECE data, then they will be able to better respond to legislator requests for data and be more informed when making policy decisions.

# User Type:
OEC Decision maker. I need to see key ECE enrollment data to make decisions and advance policies within the agency and with legislators in CT.

# Key Jobs to be done:
- I can view 2020 enrollment data (gathered by Julie in July) visualized
- I can log in to a secure site that hosts the data visualization
 
 ## Enrollment: How many children were enrolled?
- Across the state?
- In each city?
- At each site?
- In each funding source? Funding type?
- How many children are getting full-day vs. part-day experiences?

## Demographics: What are the backgrounds of the children served by OEC?
  - Age
  - Gender
  - Race
  - Ethnicity
  - Income (SMI and/or FPL)

## Geography: How are spaces distributed throughout the state?
- I can see enrollments by town
  - I can see the sites located in each town

**Comment by RyanHansz** [comment]
Potential Next steps:
- Adding licensing data
- Adding census data
- Care model data from funding reports
- Exporting (ex: give a legislator a report for their district)

**Comment by RyanHansz** [comment]
**Questions:**
- Did Julie group funding space types into full day vs. part day?
- Do we have good capacity numbers? Or just total enrollment?
- I assume we're focusing on a point of time to begin with, is that true?
-

**Comment by RyanHansz** [comment]
- Unmet needs: For every town in CT, eligible children - number of spaces

**Comment by JordanGuinn** [comment]
Created https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1083 as the Zenhub equivalent of this (which is an actual epic, allowing for issue management and tracking progress). Closing this in favor of that.
