### ISSUE TITLE
Resolve Children's Playhouse org/site

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1053]
my understanding:
- `Children's Playhouse, Too` should become a site under `Children's Playhouse, Inc` (New name for children's playhouse too org)
- `Children's Playhouse` site should be added to the org
The Children's Playhouse
112 Bouton Street
Norwalk, CT
06854

license #: 13225
naeyc id: 293032
registry id: 1474

**Comment by jlhogan** [comment]
Tasha confirmed that Leah Tobin should only have access to data for `Children's Playhouse` facility; she did not make clear if she (Tasha) should have access to both facilities' data. In the FY 20-21 funded programs, I see Rovitta Paul (tchidrenply@aol.com) listed as the program contact for SR, so I think she may be the org-level user. However, tasha was the person who send the data manager survey response. 

How can I confirm the "trusted program contact" list; how do we determine if Rovitta is a trusted program contact?

**Comment by jlhogan** [comment]
victoria & Julia determined that Tasha should have org level access
need to:
- create user for Leah Tobn
- create Children's playhouse, Inc site
- give Leah site perms for Children's Playhouse, Inc.

**Comment by jlhogan** [comment]
@victoriasuwardiman user for Lead Tobin (lchidrenply@aol.com) created, please send her the welcome comms

**Comment by victoriasuwardiman** [comment]
@jlhogan welcome comms sent!

**Comment by jlhogan** [comment]
sweeet, invite sent as well. Marking this complete!
