### ISSUE TITLE
Figure out SHS space types

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1058]
from Eileen @ Naugatuck:
>I used to be able to choose a full day/school year and also part day/school year.  We have 3 classes that run from 9am to 3pm school year, 3 classes that run 7:30am to 5:30 pm full year and 1 classroom that runs 7:30am to 5:30pm school year

Does one of our existing types map to "part day/school year"? If so, update language. Otherwise, are we missing a funding time for SHS ? Do we need to provide guidance about how to correctly id the SHS funding type you receive?

**Comment by RyanHansz** [comment]
We can add or update as needed, those spaces were my best guess at what people would put in
