### ISSUE TITLE
Create Enrollment Charts from July 2020 ECIS Data

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-collection#1068]
## Background
Once the July 2020 dataset is purged of all PII, we should put it into a prototype Dash application and use it to create enrollment charts.  The work done to [set up a repo/deploy pipeline](https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1080) should provide a cursory guide on how one might create such a chart in Dash.

## Acceptance Criteria
- Enrollment charts are created from ECIS data within Dash, or whatever data visualization tool we decide upon
- Charts answer the following questions
  - How many children were enrolled?
    - Across the state?
    - In each city?
    - At each site?
    - In each funding source?
    - Funding type?
  - How many children are getting full-day vs. part-day experiences?

**Comment by JordanGuinn** [comment]
Is this done?  I see there's an associated merged PR, and it's still sitting in the backlog.
