### ISSUE TITLE
Create Demographic Charts from July 2020 ECIS Data

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-collection#1069]
## Background
Once the July 2020 dataset is purged of all PII, we should put it into a prototype Dash application and use it to create demographics charts.  The work done to [set up a repo/deploy pipeline](https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1080) should provide a cursory guide on how one might create such a chart in Dash.

## Acceptance Criteria
- Demographics charts are created from ECIS data within Dash, or whatever data visualization tool we decide upon
- Charts answer the following questions:
  - What are the backgrounds of the children served by OEC?
  - Age
  - Gender
  - Race
  - Ethnicity
  - Income (SMI and/or FPL)

**Comment by JordanGuinn** [comment]
Is this done?  Looks like the associated PR got merged, but the ticket is still in `Current Sprint`
