### ISSUE TITLE
Users want to enter negative family income values

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1078]
## Background
There are certain situations where, due to the way income is determined, the actual income value to be provided is a negative number.  We should allow providers to supply them as such.

Additionally, while we're in this space, we might as well starting using the Carbon `NumberInput` component for the family income field as well.

## Acceptance Criteria
- Family income input field is replaced with Carbon's `NumberInput` component in the child create and child edit views
- Users can enter negative family income values without issue

**Comment by JordanGuinn** [comment]
@jlhogan Do you know if this is still a thing that's desired by folks?  And if so what they'd want it for?

**Comment by jlhogan** [comment]
yes, they want it because the way income is determined can sometimes result in a negative number! this is a rare but legit use case

**Comment by JordanGuinn** [comment]
oh, gnarly - sounds good though, keeping this around!
