### ISSUE TITLE
Better messaging when the funding entered in the template does not match the funding types available

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#1089]
![Screen Shot 2021-01-26 at 11.06.58 AM.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/897d0209-1a4d-4538-8c73-9d941b63300c)

- Users are currently able to enter a funding type in the template for file upload that does **not** match the funding types they have available to their organization. 
- After upload, the record is flagged as missing information but there is no way to fix the funding (the funding type options are not available).

Consider validation of funding type and funding types available either during file upload or in missing information (to delete funding and add one that matches what they have).

**Comment by RyanHansz** [comment]
Here's a proposed design:
[Design in abstract](https://share.goabstract.com/be94dfd5-45a6-4ae5-a4db-de3528712c43)

**If the user enters correctly formatted, but unassigned funding/space types:**
- Show error modal, with funding and or space type highlighted with info icon
- Add info message with a link to #1005's form to request updates
- If the user uploads anyway, discard the funding info and let them add another, valid funding in the child record or batch-edit screen

**If the user enters incorrectly formatted funding type/space type**
- Show error modal as usual

**Comment by JordanGuinn** [comment]
The UX this applies to no longer exists, plus we're redesigning this whole experience, soooooooo closing.
