### ISSUE TITLE
Leaving birth certificate type blank in the template gives user an error that it is required during file upload (instead of defaulting to Unavailable)

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#1090]
Do we want to require users to enter "Unavailable" in the template for file upload or can we default to Unavailable if it is left blank?

**Comment by jlhogan** [comment]
if we do not change this behavior, we should at least update the template/data def to indicate birth cert type is not optional

**Comment by bamader** [comment]
Is there a preference on which route we take? I.e. changing the template to not optional vs making it optional and defaulting to Unavailable if it's not given?

**Comment by RyanHansz** [comment]
I'd suggest ` make it optional and default to unavailable` if not given if we want to reduce users seeing errors

**Comment by victoriasuwardiman** [comment]
Agreed with Ryan!
