### ISSUE TITLE
enrollment report upload for site level user overwrites all org data

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1096]

**Comment by JordanGuinn** [comment]
Gonna throw a 1 on this to avoid us bringing unpointed work into the sprint, which we ought do as much as possible.

**Comment by JordanGuinn** [comment]
## Test Cases
- [ ] Upload enrollment as an organization-level user successfully
- [ ] Upload/replace data for "all sites" as a site-level user within the same organization successfully 
- [ ] Organization-level user's site data inaccessible by site-level user was untouched

**Comment by JordanGuinn** [comment]
Looks good to me - ready for merge/deploy
