### ISSUE TITLE
Create a process for reviewing dev work from a design perspective

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#1104]
**As a designer on the ECE Reporter team:**
Currently, tickets are implemented with little design review, unless specifically asked for. 
Ideally, every change that affects the front-end of ECE Reporter and other tools would have a design review before a ticket is considered "done".

**Comment by JordanGuinn** [comment]
Thought: We could experiment with adding a `Design Review` swimlane to the ZenHub dev board?  And any tickets that don't warrant a design review (devops, back-end work, etc) can just skip over it.

**Comment by RyanHansz** [comment]
That sounds good to me, I'll bring it up to Phoebe/Jay.
