### ISSUE TITLE
Follow up with SDE re ECIS

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1112]

**Comment by jay-finch** [comment]
## 2:30 Executive Strategy Meeting (1/25/2021) Update
- Posted Rachel on the need to reconnect the SDE team
- Didn't finish the conversation here, so I will follow-up tomorrow

**Comment by victoriasuwardiman** [comment]
@jay-finch is there any update on this? We're about a month out from when data is "due" so would be nice to get some sort of resolution for those folks still waiting for their ECIS data soon, in the case they need to clean it up before submitting.

**Comment by jlhogan** [comment]
we have a meeting with SDE tomorrow that  I believe is specifically to address this! (you're on the invite)

**Comment by victoriasuwardiman** [comment]
oh nice!
