### ISSUE TITLE
Allowing private pay children

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#1116]
For some organizations who have been using ECIS, they have become accustomed to entering in private pay children. Is there a way we can allow this? While we most likely cannot do any meaningful data analysis for private pay children from ECE Reporter data, it does set the stage for potentially expanding data collection efforts to meet OEC's vision of understanding the full landscape of children served in CT. Also, it doesn't hurt to collect??

**Comment by JordanGuinn** [comment]
@jlhogan Do you happen to know anything about this, and if it's valuable?

**Comment by jlhogan** [comment]
there's not much more to it than what's in victoria's comment. to assess value we would need to know if any programs had interest in maintaining all of their data in ECE Reporter for reasons beyond funding reporting. we opted to require all data be for funded programs to work around a special waiver that programs/OEC need to collect from parents of private pay students to collect data about them. overall i think this data is interesting to OEC, but not requierment to focus on right now.

**Comment by JordanGuinn** [comment]
Gotcha.  Does `private pay` === `income not disclosed`?  Tryna understand what's actually being talked about here
