### ISSUE TITLE
Privacy Policy language references ECIS

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1118]
Should probably not :)

**Comment by JordanGuinn** [comment]
@jlhogan Is this actionable?  I see the single place where ECIS is currently referenced in the privacy policy  the `Reason for collecting` column of the `Site` field (below `Enrollment and funding`):

`Used to link with other data like ECIS and PSIS.`

Is this saying to just... delete that?

**Comment by jlhogan** [comment]
ahhh nope this has already happened! the privacy policy at some point referenced "ECIS" where it now says "ECE Reporter"

**Comment by JordanGuinn** [comment]
ahhh okay SWEET
