### ISSUE TITLE
OEC to kick off webinars

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#1119]
@jay-finch should have thought of this before, but can we ask Rachel or Lorna to attend and kick off our webinars?

**Comment by victoriasuwardiman** [comment]
Onboarding webinar outline: https://docs.google.com/document/d/17987EeTCutdD-83BDAMOOB2jgvQeYDk-w4MdYrPnsx0/edit?usp=sharing

**Comment by jay-finch** [comment]
## 2:30 Executive Strategy Meeting (1/25/2021) Update
- Rachel has added the meetings to her calendar and is thinking through her availability.
- I will follow-up with her tomorrow (1/26/2021) to confirm participation.
