### ISSUE TITLE
Instrument Google analytics

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1127]
## Background
There are almost assuredly a handful of benefits we'd receive from the metrics we could potentially gather with Google Analytics, so as a starting point, we should set it up in ECE Reporter so we can take a look at what's available to us.

## Acceptance Criteria
- Google Analytics account is created/discovered for ECE
  - Reach out to Amelia to see what account is being used on the OEC website
- Google Analytics is set up in ECE Reporter application

**Comment by JordanGuinn** [comment]
Blocked until we're clear on if there is an existing GA account that we can use for this, or if we need to spin one up ourselves.

**Comment by Derekskylight** [comment]
Hi I can start looking into this. I actually made one with my Skylight e-mail yesterday without reading this ticket and have the ID, but can DM Amelia

**Comment by JordanGuinn** [comment]
@Derekskylight Did you ever check in with Amelia re: OEC GA accounts already in use?

**Comment by Derekskylight** [comment]
Yup! 

10:22
Amelia Wellers (she/her) Hi Derek! Welcome to Skylight and nice to meet you! Wanted to give you a quick answer first - My first thought would be to use OEC’s unique GA ID just to keep everything in one place. **However, ECE Reporter isn’t currently hosted on ctoec.org, correct?
10:22
I believe each GA ID is generated according to the specific domain, so it may not even be possible**
10:23
United Way would also know more. I need to hop into some meetings, but will look into it today too

10:29
Amelia Wellers (she/her) haha cool. Yes, I’m “running” it, meaning I’m the person who draws the metrics, but technically, United Way is the administrator
10:29
I may have administrator access as well, but I can double check
10:30
it was set up a full year before I joined the website project

**Comment by Derekskylight** [comment]
Can send screenshots in a chat if anyone would like

**Comment by JordanGuinn** [comment]
Confirmed we can track activity now!  Although for what it's worth, most ad blocker extensions will prevent GA from initializing, meaning we'll only get usage data from anyone without an ad blocker setup (which may not be fully reflective of our entire user base).

**Comment by Derekskylight** [comment]
Hmm I wonder if the computers data analysts/site providers use will have ad blockers downloaded on them then, at the moment I would assume the majority don't but we can see the sample size
