### ISSUE TITLE
Confirm optionality of fields in batch upload

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1128]
## Background
For the sake of a consistent user experience, we want to make sure that all of the optional fields within our batch upload UI are in fact optional at the API and/or data layer.

## Acceptance Criteria
- All fields marked as **OPTIONAL** in data requirements table can be left empty in upload without causing errors
  - If any fields are **conditionally** required based on the value of another field, those should be enumerated and confirmed as well
  - Birth certificate ID number, town of birth and birth state are required if birth certificate type is US
- e2e test(s) exist to confirm this for **each and every applicable field**

**Comment by JordanGuinn** [comment]
@bamader Looks like the e2e suite is failing

**Comment by bamader** [comment]
@JordanGuinn Oh crap this is the really dumb exit 10 failure where none of the tests actually run and we get no helpful log output 😑 . That means it's some super small nuance bug. Into the mines I go...

**Comment by JordanGuinn** [comment]
Is there any more output when the `--verbose` flag is added to the nightwatch command running the tests?

**Comment by bamader** [comment]
I managed to diagnose it. `exit code 10` has thus far referred to finicky module stuff (importing, exporting, ts vs js, etc.) so that was at least somewhat of a clue. I'm putting details in the Readme.

**Comment by JordanGuinn** [comment]
@bamader Created a ticket for the bug we found earlier.  Lemme know if I'm missing anything:

https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1157

**Comment by bamader** [comment]
@JordanGuinn I made a few updates just to give some extra details, but it looks good! Realistically I'll probably handle it first thing tonight/tomorrow once the audit PR lands so we won't have to wait long 😛
