### ISSUE TITLE
Add link to the site/funding request form in help page

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1162]
## Background
We have a request form for users that would like to suggest changes to site/funding information within their organization, but its existence isn't too clear in the application.  We should add a link to this form in the help page so users have another path to access it.

[Designs can be found **here**.](https://share.goabstract.com/4e752af7-27dc-4423-82e8-3e92e32f2a1a)

## Acceptance Criteria
- Site/Funding Request form can be accessed directly from the Help page in ECE Reporter
   - Not to be confused with https://help.ece-reporter.ctoec.org

## Screenshots
![image.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/6d1ed70d-0745-4c62-bc82-671b1c26f3a0)
![image.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/49a3cc87-cf30-4201-80ab-aa51e7f295f1)

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 Either of you have thoughts as to whether or not this is something we still even want to do?  Seems like now that the admin view is nearly complete, the value of this form is pretty close to zero.

**Comment by ehuang525** [comment]
I don't think we need to keep this. It's probably up to OEC to determine how they want to operationalize how site/funding spaces information gets updated. And since they will have access to admin features, it's more of a process thing on their end perhaps.

**Comment by JordanGuinn** [comment]
Agreed!  Cool, will close
