### ISSUE TITLE
QUESTION? remove deleteddate from entities?

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1174]
## Context
- we added deleteddate to entities in order to be more HIPAA compliant by more easily recovering data
- this is already achieved via temporal tables without the additional deleteddate field, which is not really all that well supported by typeORM and thus adds complexity without adding any additional information or other benefits

## Consideration
- removing deleteddate should be relatively easy
- removing deleteddate will reduce complexity of the code and complexity of queries needed to do data analysis

**Comment by JordanGuinn** [comment]
The more I think about this, the more I don't actually think we should do this.  TypeORM certainly does support the `DeleteDateColumn` decorator, just [not in a couple particular instances](https://github.com/typeorm/typeorm/issues/6265).  Regardless, I still think it'd be valuable to have generally, and isn't really incurring any tech debt or introducing any problems at the moment.

Closing for now.
