### ISSUE TITLE
Previous month roster view does not show all children w/active enrollments

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1187]
## Background
A user just reported that she was trying to use the `Roster for a past month` filter to confirm her enrollment data was correct.  However, a student withdrawn in **January 2021** (with enrollment dates in the tool confirmed) was not showing up in the **December 2020** filtered roster view.

## Acceptance Criteria
- ALL children with an active enrollment **within the filtered month** are visible in the filtered roster

## Additional Context
- **Active enrollment** = An enrollment without an explicit `exit` date

**Comment by vonbearshark** [comment]
Investigated the code and it looks like on the backend we are correctly filtering the students according to the intention here. But then we are seemingly filtering _again_ on the frontend, separating out `active` and `withdrawn` children. This seems intentional. For what it's worth the condition is `child.enrollments?.every((enrollment) => !!enrollment.exit)`, which does match

> Active enrollment = An enrollment without an explicit exit date

technically. But not 

> active enrollment *within the filtered month*

Wouldn't a student withdrawn in January 2021 rightfully show up as "withdrawn" in the December 2020 filtered roster view? Is the issue that withdrawn students aren't listed in the roster view?

**Comment by vonbearshark** [comment]
Or is the definition of `active` actually: either no `exit` or an exit in the future (past the filtered month)?

**Comment by vonbearshark** [comment]
But I am also running into the potential bug: trying to filter to `Withdrawn records` shows no records...

**Comment by JordanGuinn** [comment]
@vonbearshark We talked about this directly over Zoom, but putting here for tracking purposes.

Here's my understanding of what those 3 distinct views are supposed to reflect (@jlhogan plz correct me if this seems off):

- **Default Roster View:** Show all children that have **at least one** enrollment without an exit date
- **Withdrawn Records View:** Show all children that **don't have any** enrollments without an exit date
- **Filtered by Month View:** Show all children that either:
   - Have **at least one** enrollment without an exit date
   - Have **at least one** enrollment with an exit date _after_ the filtered month

**Comment by vonbearshark** [comment]
Just sharing my thinking: that makes the `withdraw` and `month` query params mutually exclusive. It's a little hard for me to decipher, but I don't think that's the way the code is organized right now, regardless of this issue

**Comment by jlhogan** [comment]
above sounds correct to me. Perhaps theres a way to simplify this a bit by fitting the default and withdrawn rosters into a time-based filtering definition:
- default view is enrollments that meet the month filter requirement for CURRENT month
- withdrawn view is inverse of default view -- every child for whom no enrollments meet the filter requirement for the CURRENT month (probably still easiest to implement this the way it is alraedy implemented) 
Not sure if this tweak to the definition/implementation of the "active" roster feels useful enough; i see that a fix is already up
