### ISSUE TITLE
Multi-org users generate lots of unnecessary API/RDS activity when retrieving report data

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1190]
## Background
Recently, the ECE Reporter ALB was unresponsive for a minute or two earlier this morning, and digging through Cloudwatch logs and metrics, it looks like it was the result of a sudden burst of API (and thereby RDS) activity.  The biggest culprit I see is the oec-report endpoint, and more specifically, how it’s called once per each organization that a user has permission to access.  This can’t scale effectively, as we already have a couple of users who have permission to access 18 organizations.  So when said users log into the application, they implicitly open **18 new, concurrent DB connections** and execute **18 SELECT queries** for _just_ oec report data for _just_ themselves.

The first and most immediate course of action is here to simply use a **single** API call to retrieve all OEC reports for a single user across all that user's organization.  But additionally, we should also consider beefing up our RDS hardware and seeing how much of an impact that has on situations like this.  Because while there's certainly an improvement to be had on the query-side here, at the end of the day this still wasn't _that_ much activity.

## Repro Steps
- Create a new user (or use an existing user)
- Configure the user to have 20+ organization permissions
- Log in to ECE reporter
- Navigate to the Home page
- Observe the number of `oec-report` API calls generated

## Acceptance Criteria
- OEC report data for a given user, across **all** organizations that user has access to, is provided in a **single** API call w/a **single** db query
- Enable [Performance Insights](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.html) on our prod-like RDS instances (to get a better idea of any other queries that are particularly burdensome)
- Consider bumping our prod RDS instance from a **small** to a **medium or larger** ([it's the difference of like ~**$0.03/hour**](https://aws.amazon.com/rds/sqlserver/pricing/?pg=pr&loc=6))

**Comment by JordanGuinn** [comment]
Did this get sprinted at some point?

**Comment by jlhogan** [comment]
i rogue clicked, my bad, will return it to where it's supposed to be!!!
