### ISSUE TITLE
First Pass of ECE Data Collection Template

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1197]
@victoriasuwardiman @jlhogan 

**Layout**

Layout --> Horizontal scroll is not ideal, what if we laid out form 1st 2 columns instead of 1st 2 rows?

**Dropdown menus** - I experimented, and it's possible we create drop-down menus for every multi-answer solution here. This could eliminate any human-input errors from the client-side while also reducing time spent entering data total. My main point! Can send screenshots of my mockups

Data Options - There are about 7 options for inputting dates, I wonder if users input different formats. It'd be helpful to direct them to choose one and **only** one format for consistency throughout. 

**Specific columns**

"Birth certificate type"- "Generally an 11-digit number" --> Specifics could be useful, children born in which circumstances need an 11-digit number and children born in what other circumstances need an X - digit number

"Race": No option for a drop-down menu of the race instead of putting 'N' for 6 straight fields? Include a 'mixed' option as well as an edge case. 

"Dual Language Learner" - Not specific enough. What is defined as a 'learner?' Proficient? Beginner? 

"Determination Date" - Of what?

"Space Type" - Can't list it in the same format?

"Zipcode" - Perhaps instead of 'valid zipcode (5-digit number)' --> 'Number (5-digit)' for consistency?

**Comment by JordanGuinn** [comment]
@Derekskylight Any word if this is something we might take action on in the foreseeable future?  Or if there's even value in considering this at this point?

**Comment by Derekskylight** [comment]
@JordanGuinn I don't believe this is anything we will be taking action on in the future nor has it been on my mind in a verrry long time. In fact, I didn't actually believe I was the one who wrote this upon the first pass. I think that we've settled on the current excel template and users are able to use it in a way such that there hasn't been a roadblock for them on that end! If we need to discard/store this somewhere it should be fine
