### ISSUE TITLE
Non-int values in "number of people" column causes "template has incorrect format error"

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1201]
## Background
Type errors cause the insert queries to fail, and then the whole upload fails, which results in "Your template is in the wrong format" error.

## Acceptance Criteria
- The resultant error from these failure is more informative than "something went wrong with your upload!"
- strip ints out of that field if it's a string to be more forgiving 
  - ECIS had "9 or more" as a value for number of people that is rare enough that I only just encountered it, but is likely in data I sent folks
  - someone had an errant ` char in one of those cells that caused the upload to fail

**Comment by JordanGuinn** [comment]
_Should_ we actually allow them to enter in string values here?  It seems like that would force us to try and understand the surrounding context as well, like:

- `9 or more`
- `less than 5`
- `5 or 6`
- `no more than 8`

Which seems like it could easily become a pretty slippery slope.
