### ISSUE TITLE
Site-specific users cannot see sites / funding spaces in home page 

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1205]
# Background
The `Sites` and `Funding Spaces` tab on the Home page is blank for site-specific users, which is super unhelpful.

## Acceptance Criteria
- `Sites` and `Funding Spaces` are present on the Home page for site-specific users

**Comment by JordanGuinn** [comment]
@jlhogan Is the idea here that we want to allow site-specific users to be able to see **all** site and funding space data within their organization, or are there funding spaces specific to sites that are for whatever reason absent from the Home page?
