### ISSUE TITLE
Users cannot add income determination to records with no income determinations

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1209]
## Background
Users are unable to add income determinations to child records that don't have any income determinations specified, which is confusing as the UI informs them that it's required.

## Repro Steps
- Add a new child to your roster, **omitting** the income determination fields
- Click on the link to that child in your roster
- Navigate to the `Family Income` tab
- Observe

## Expected Behavior
User is able to add income determination data data.

## Actual Behavior
User is told that `A recorded income determination is required.`, but are unable to do anything about it.

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/706859bf-9775-462b-b268-7fe1da45a9d6)

**Comment by bamader** [comment]
Okay so can repro in staging, just not locally

**Comment by jlhogan** [comment]
sorry, I dont have more info except that I definitely saw it in the wild; didn't dig in any more, but can if needed.
My guess was that it was something to do with not ending up inthe exact "empty" state the app expects, due to users entering data w/out batch upload.
although if you can repro with batch upload then very likely i was wrong :)

**Comment by bamader** [comment]
No problem! Am doing some digging myself now. I'd bet it's exactly what you described and the conditional that recognizes the empty state from create flow needs a lil tweak. Soon we shall know for sure!
