### ISSUE TITLE
OEC View

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1214]
## Background
Members of OEC staff should have the ability to log in to ECE Reporter and quickly view a high level summary of all submitted data up to that point.  Additionally, they should have the ability to look into any given site or organization in more detail, should they have any questions or concerns as to what data submissions remain outstanding and from whom.

## Acceptance Criteria
- New **Submissions Status** view is created and wired up, following the [linked designs](https://app.abstract.com/share/4d17d6ac-17d7-48ae-9a12-3592d68aae76?collectionId=6e3972b5-1dd6-470d-b2fb-f50b5d9264c9&collectionLayerId=903621f7-7347-4411-b4f5-9d380c96d13f&present=true&preview=false&sha=c174feadd60c143ad7a4cc6889dada00b71eeeff)
   - View is treated as the home page for "OEC" users (they are navigated here post-login)
- New **Site detail view** is created and wired up, following the [linked designs](https://app.abstract.com/share/4d17d6ac-17d7-48ae-9a12-3592d68aae76?collectionId=6e3972b5-1dd6-470d-b2fb-f50b5d9264c9&collectionLayerId=4774b8b9-e0d1-4183-9d8c-f75e033ef8f2&present=true&preview=false&sha=c323ac93070e23d46266530d59941cec3a5dcc12)
  - View can be accessed by clicking on a site name in the **Submission Status view** OR the **Org detail view**
- New **Org detail view** is created and wired up, following the [linked designs](https://app.abstract.com/share/4d17d6ac-17d7-48ae-9a12-3592d68aae76?collectionId=6e3972b5-1dd6-470d-b2fb-f50b5d9264c9&collectionLayerId=84c5121c-4d87-42ce-8628-e5267d9ddbbc&present=true&preview=false&sha=c323ac93070e23d46266530d59941cec3a5dcc12)
  - View can be accessed by clicking on an org name in the **Submission Status view** OR the **Site detail view**
- New "OEC" user type exists and can be distinguished from provider users
- **Only** "OEC" users have access to these three views
- "OEC" users **do not** have access to the **file upload** or **roster** views

## [Designs](https://share.goabstract.com/4d17d6ac-17d7-48ae-9a12-3592d68aae76)

![Screen Shot 2021-02-11 at 1.23.06 PM.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/5555bd69-8d32-45a5-9c33-514dac2c464a)

**Comment by JordanGuinn** [comment]
Closing in favor of https://app.zenhub.com/workspaces/jays-backlog-purge-board-606df910b665d7000fad2c67/issues/ctoec/data-collection/1282.
