### ISSUE TITLE
Improved roster loading / pagination

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1219]
## Background
Loading the entire roster into browser memory at once causes performance problems for users, especially those with large rosters. It would be better experience if we enable the user to page through their data, and only display/maintain in browser the relevant data.

Some users have experienced performance issues where they intermittently see the tool freeze, or throw unexpected errors. We believe the large roster in browser cache may be the culprit. 

## Technical Details
- requires ability to fetch children by agegroup (as they are displayed in the roster)
- requires a design solution for paginated date within the roster accordion
   - Add a button at the bottom of the child list to allow the user to load more child data, and don't do so by default

**Comment by JordanGuinn** [comment]
Closing this - we have official roster redesign tickets now present in the backlog, removing the need for addressing this specifically outside of that work!
