### ISSUE TITLE
500 response to GET "api/children?siteMap=true"

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1228]
## Background
The API call for `GET api/children?siteMap=true` on the home page post roster submission (responsible for retrieving child metadata by site) is sometimes returning a 500, with the following error message:
```
TypeError: Cannot read property 'siteName' of null
```

## Repro Steps
- Log in to ECE Reporter
- Fill in any missing child data necessary to submit your roster
- Submit your completed roster
- Navigate back to the home page
- Observe

## Expected Behavior
- `Sites` section has cards containing child metadata per site

## Actual Behavior
- `Sites` section is blank and `GET api/children?siteMap=true` returns a 500

**Comment by bamader** [comment]
Depending on what the context/steps are, I may have put a fix for this in my PR for income determination bugs.

**Comment by jlhogan** [comment]
no more details, sorry -- that was just an API response in a pre-prod env; but I think brandon is right

**Comment by bamader** [comment]
If there's no specific repro then I'm like 99% sure adding '?' will fix this. I'm gonna pull this over into the validation column with the other stuff in that PR.

**Comment by JordanGuinn** [comment]
What's the fix exactly?  How do you trigger this API call within the application?  Is there some implicit context I should have here?

Just wanna make sure there's enough information in this ticket for anyone one of us to validate it 🙂

**Comment by bamader** [comment]
This call gets generated by the home page when we fetch the cards that show in the site section (the "you have this many kids of these age groups enrolled at this site" part). Call gets made by home page, data structure gets built on back end, data structure gets sent back to front end. The validation should be making sure the call actually happens on the home page under a variety of uploading conditions.

**Comment by JordanGuinn** [comment]
Okay gotcha - thanks for the clarification 😁

**Comment by JordanGuinn** [comment]
Ahhhh, looks like that API call is only made from the home page post-submission, as well.  No wonder I couldn't get a repro 😅

**Comment by JordanGuinn** [comment]
@bamader Which PR is this associated with?

**Comment by bamader** [comment]
Whoops it's addressed in https://github.com/ctoec/data-collection/pull/1218. I've updated the PR to link to this issue, too.
