### ISSUE TITLE
As a city-wide data staff, I can enter data for multiple child care organizations at the same time.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#123]
**AC**:
- user can only update data for sites/orgs that have permissions for: implement SOME internal to the app authorization layer 

Cities like Hartford have city-wide staff who manage data. Rather than asking each individual provider to enter data, that role should be able to enter data for multiple organizations.

The data template includes an "Organization" column to handle this.

**Comment by RyanHansz** [comment]
Access checking: The person is authorized to create/edit data for these organizations. Are you allowed to update data for those organizations.

**Comment by jlhogan** [comment]
@RyanHansz  should the user be blocked & alerted that they are trying to add data for a site they don't have access to (or a site that does not exist) when they attempt to upload the data or when they attempt to submit to OEC?
