### ISSUE TITLE
Exit reason field does not show up properly in batch edit

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1235]
## Acceptance Criteria
- Exit reason can be properly updated in batch edit

## Screenshots
![Screenshot from 2021-03-11 12-28-06.png](https://images.zenhubusercontent.com/5f6cfe3876416295f5d06c52/9ccd5134-5a9f-49a0-b0cb-321ea68d5022)

**Comment by jlhogan** [comment]
You'll see this: ![Screenshot from 2021-03-11 12-28-06.png](https://images.zenhubusercontent.com/5f6cfe3876416295f5d06c52/9ccd5134-5a9f-49a0-b0cb-321ea68d5022)

when really the only issue is that exit reason is missing

**Comment by JordanGuinn** [comment]
Ohhhhhhhh, so THAT'S what's going on with https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1011.  I'ma close that one cuz this is more accurate

**Comment by JordanGuinn** [comment]
Closing - can no longer reproduce this issue.
