### ISSUE TITLE
in multi-org user view, site tabs are sticky after switching org tabs

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1243]
## Background

if you log in as a multi-org user, you'll see sites correctly nested under each org on first visit, however upon switching back to a previously viewed org roster, the site tabs from roster you were just on will persist until you click on the org tab again 

## Acceptance Criteria

**Comment by JordanGuinn** [comment]
Deleting cuz this isn't gonna be a thing in roster v2.0!
