### ISSUE TITLE
Fix child count in OEC admin view to be only currently enrolled children

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1246]
## Background
The new `ECE Reporter Overview` page we created for OEC admins mistakenly includes previously withdrawn children in the total child count all sites.  The `n children enrolled` text should **only** include children with an active enrollment. 

## Acceptance Criteria
- The count of children at the top of the `ECE Reporter Overview` page only includes children with an active enrollment

## Screenshots
![image.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/2a1365fa-beb7-4972-acfa-0a18470516b3)

**Comment by JordanGuinn** [comment]
@jlhogan Same question as https://github.com/ctoec/data-collection/issues/1247 - is this referring to the OEC admin view?

**Comment by jlhogan** [comment]
yes -- is it not in the epic? :/

**Comment by JordanGuinn** [comment]
Ahhhh, no I see it is now - I just didn't see a description and got confused
