### ISSUE TITLE
Uploading the same file twice duplicates children in roster

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1256]
## Actual Behavior

**Comment by JordanGuinn** [comment]
I cannot for the life of me get a repro on this anymore, regardless of the contents of the file I upload.  There may be a very specific use case that I'm missing here, but overall this appears to be working as intended.  Closing - if there _does_ end up being some edge cases where this is still an issue, we can create a new ticket and outline the specifics in it.

**Comment by bamader** [comment]
I would wager this is a holdover from before we did the maprows refactor, which had a metric butt ton of validations from me, so I'm like 99% sure we caught this while fixing batch update

**Comment by JordanGuinn** [comment]
Ahhhhh, yeah would make all the sense
