### ISSUE TITLE
SPIKE: Investigate in-app authentication solution to deprecate IdentityServer

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1257]
## Background
In an attempt to:
- reduce footprint + complexity of what we will hand over to OEC
- improve user login experience

we want to replace the existing ID server solution with in-app auth. Likely, this will be username/password + JWT auth, something a la https://www.digitalocean.com/community/tutorials/api-authentication-with-json-web-tokensjwt-and-passport

### HIPAA Compliance

From Josh Dorothy:

> a lot of this will be obvious to you when reading through the doc, but I'd say everything in this section is a must: https://docs.google.com/document/d/1gEontLUf-PIuTaj8Z-6sngjXrHSpTdPcYcBcI8WUyIQ/edit#heading=h.p7fkptna2ql5
12 h 05
if you do everything there you're also in compliance w/ HIPAA I think, with the following two additions:
    - log everything you can related to login successes/failures as long as it's not PII/PHI/could be used to construct them
    - HIPAA has a record keeping requirement of 6 years, so make sure those logs end up somewhere and/or OEC knows about it

## Acceptance Criteria
- In-app authentication solutions are researched
   - Username/password + JWT authentication, along with any other reasonable alternatives
   - Login.gov as a potential alternative?
   - If none of the solutions are really feasible, maybe we stick with our IdentityServer solution (shudder)
- Technical strategy is understood and discussed with the team
   - Ensure it adheres to everything in the [User Management section of the Skylight Technical Handbook](https://docs.google.com/document/d/1gEontLUf-PIuTaj8Z-6sngjXrHSpTdPcYcBcI8WUyIQ/edit#heading=h.p7fkptna2ql5)
- If team doesn't find any fundamental issues with the strategy, Zenhub tickets are created for the work to be done here

## Resources
- https://docs.google.com/document/d/1gEontLUf-PIuTaj8Z-6sngjXrHSpTdPcYcBcI8WUyIQ/edit#heading=h.p7fkptna2ql5
- https://www.digitalocean.com/community/tutorials/api-authentication-with-json-web-tokensjwt-and-passport

**Comment by JordanGuinn** [comment]
Closing - the decision has been made to migrate to [ForgeRock](https://www.forgerock.com/) long-term, eliminating the need for us to do any more IdentityServer work at this point.
