### ISSUE TITLE
Refactor roster export API logic

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1261]
## Background
The logic responsible for exporting a CSV representative of a client's current roster is pretty hacky and potentially prone to error.  We should take the time to largely simplifying that behavior, and add some additional automated testing coverage to feel confident in what we've built moving forward.

## Acceptance Criteria
- Roster export logic is refactored to be simpler and more immediately accessible to future engineers
   - Modularize logic explicitly responsible for transforming child data into exportable format
   - If possible, resulting CSV/spreadsheet is streamed **directly** to the response, instead of first written to the EC2 filesystem
   - `src/controllers/export.ts`
- Unit and/or e2e tests are written to cover the most important logical pieces here

**Comment by JordanGuinn** [comment]
Whoever pick this ticket up, be sure to check in with Emily to confirm that the new roster designs will still actually necessitate this ticket (suspicions are that it should).

**Comment by vonbearshark** [comment]
Also, just confirming this is still priority? I know we are moving away from tech debt addressing. Makes sense this would carry over, but I could also see the argument that if it works then it works. And maybe worth revisiting _after_ the new roster design changes?

**Comment by JordanGuinn** [comment]
Yeah, that's a good point - probably makes the most sense to revisit this post roster redesign, given some of the design pieces there might warrant tweaking of the GET children API (which we'll presumably be largely harnessing for this work anyway).

**Comment by vonbearshark** [comment]
That's what I am thinking. Maybe mark this ticket as dependent on that and put back in backlog for now?

**Comment by JordanGuinn** [comment]
Closing in favor of #1335, which inherently covers this.
