### ISSUE TITLE
Record match in file upload checks across organizations

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1268]

**Comment by JordanGuinn** [comment]
This sounds like one of the specific issues to be addressed within https://app.zenhub.com/workspaces/jays-backlog-purge-board-606df910b665d7000fad2c67/issues/ctoec/data-collection/1256, yeah?

**Comment by jlhogan** [comment]
dont think so -- this is like, a data access issue where folks uploading records about a child already in the system (even if uploaded by another user) will edit that child. We havent built the tool to handle that, so need to keep all children siloed to the org that creates them.

**Comment by jlhogan** [comment]
it's addressed in my refactor

**Comment by JordanGuinn** [comment]
OH, I see - the cross-org check is the _bug_, not the expected behavior

**Comment by jlhogan** [comment]
yeah sorry heh
