### ISSUE TITLE
Clicking "Add a Record" button sometimes breaks ECE Reporter

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1272]
## Background
Found during validation of https://github.com/ctoec/data-collection/issues/1265, and confirmed it existed independently of that work.  Long story short, if you refresh the roster view and then attempt to add a child to your roster, the application crashes.

This may be a result of us losing location state in the application when the application is refreshed.

## Repro Steps
- Navigate to the roster view
- **Refresh the page**
- Click the `Add a Record` button
- Observe

## Expected Behavior
- The child info form appears, and you can begin the process of adding a record.

## Actual Behavior
- The application crashes, displaying the `Something went wrong` error.

## Demo
https://images.zenhubusercontent.com/274936723/373a142e-a42a-4f58-bc57-d527f5f75240/screen_recording_2021_04_14_at_9_20_42_am.mov

## Stacktrace
```
ErrorBoundary.js:64 TypeError: Cannot read property 'uniqueIdType' of undefined
    at T (Form.tsx:112)
    at Qa (react-dom.production.min.js:153)
    at _c (react-dom.production.min.js:261)
    at ml (react-dom.production.min.js:246)
    at yl (react-dom.production.min.js:246)
    at cl (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Yo (react-dom.production.min.js:122)
    at Zo (react-dom.production.min.js:123)
```

**Comment by lukenewman** [comment]
Seems that the `activeStep` effect hook in `CreateRecord.tsx` is the culprit here. If you comment it out, the form loads, albeit incorrectly. Could someone with more context around the `history` state in the app provide some insight on a potential fix?
