### ISSUE TITLE
Users cannot have varying access levels across different organizations

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1275]
## Background
Confirmed this is still an issue in `EPIC-roster-redesign` - permissions are not currently respected for users that have both organization level and site level permissions across multiple sites.

## Repro Steps
- Log into ECE Reporter
- Create a new user (or edit an existing user)
- Provide this user with **organization-level permission** to one organization
- Provider this user with **site-level permissions** to a **subset** of sites at **another** organization
- Log in to ECE Reporter as this new user
- Observe

## Expected Behavior
- Org list view shows roster counts limited to **only the sites the user has access to**
- Roster for org-level permissions includes enrollments for all sites at that org
- Roster for site-level permissions **only includes enrollments for the sites the user has access to** at that org

## Actual Behavior
- Org list view shows roster counts across all sites per org
- Roster for org-level permissions includes enrollments for all sites at that org
- Roster for site-level permissions includes enrollments for all sites at that org

## Acceptance Criteria
- Site-level access is respected for **all** users, regardless of how many organizations those site permissions span
- Organization-level access is respected for **all** users, regardless of how many organizations they have access to
- Site-level access of **one** organization and organization-level access of **another** organization are respected simultaneously

**Comment by JordanGuinn** [comment]
@JordanGuinn Be sure to account for this in our upcoming new roster world
