### ISSUE TITLE
As an OEC Admin User, I can create a new organization

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1279]
## Background
As an OEC Admin User, I would like to add more organizations with sites and allocate the required funding spaces and user permissions. 

## Acceptance Criteria
- `Create New Organization` button is added to admin org list view

As an OEC Admin User, I am able to create an organization's:
- **Name**
- **Site Information**
     - Name
     - Title. This title will link to a dropdown selection of choices
     - Region. This will link to a dropdown selection of choices
     - Facility Code (Optional)
     - License Number (Optional)
     - Registry ID (Optional)
     - NAEYC ID (Optional)
     - Add more than one site (Optional). Clicking on this button will allow for more sites to be added.

- **Funding Spaces**
     - Funding Sources
     - Age Group
     - Space type
     - Capacity

## Designs
[Create Org Figma File](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=2%3A2)

![Create Org Final Design.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/3ab86045-5a2d-443f-9a7f-8cd6529f6031)

**Comment by jlhogan** [comment]
need to be able to create funding spaces as well @Derekskylight

**Comment by jlhogan** [comment]
Additionally, users need to be associated with orgs/sites (not sure if that should happen here, from user view, or both)

**Comment by Derekskylight** [comment]
^^Updated description + picture to include funding spaces based on "Final Designs" in Figma

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 Few questions/thoughts here:

1.  This is gonna need to be broken up into several distinct tickets, given the scope of certain parts of this work.  You two mind if I do that, or would you prefer to?
2.  The new organizations created can _only_ have new sites added to it within this form, correct?
3.  Funding spaces are currently only associated with organizations, not individual sites.  I see the `Site` dropdown exists within the `Funding Spaces` section though, so do we want to take on the additional work to associate sites with funding spaces?
4.  If the answer to #3 is yes, which sites should be populated in the `Funding Spaces` tab?  Should it include the yet-to-exist sites that a user may add within this form?

**Comment by Derekskylight** [comment]
1. Yes, please feel free to break it up into distinct tickets and label them within the epic.
2. I would assume this is yes, but will default to @ehuang525 on this as well. 
3. I believe we cleared this up within the Design review meeting where we won't include the sites at all

**Comment by JordanGuinn** [comment]
Closing - a handful of smaller tickets have since been created representing the overall work necessary here.
