### ISSUE TITLE
As an OEC Admin User, I can edit another user's first/last name

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1281]
## Background
As an OEC Admin User, I can **edit** another user's personal data, specifically their first and last name. 

## Acceptance Criteria
- Clicking on a user's name in the admin list view takes you to this Edit view
- Admin is able to edit user's first and last name, but **not** email
- User permission management can be ignored for now
   - To be handled in another ticket

## Designs
[Full Figma files can be found here.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=2%3A2)

#### Edit View
![Screen Shot 2021-05-07 at 9.23.06 AM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/7e0c9cdf-c7f1-4bfd-a9dc-fd324658b575)

**Comment by jlhogan** [comment]
Currently, changing a users email (an thus their login username) requires the separate ID management system.
What can be edited here is the users name + their association with any orgs/ sites

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525  Also, now that I think about it, do we _really_ want to provide OEC admins with the ability to edit _other users'_ first and last names?  I could be off-base here, but that feels odd and kind of intrusive to me

**Comment by ehuang525** [comment]
@JordanGuinn Since providers don't currently have the ability to edit their own information, I think that capability on the admin side is probably better to have than not. I don't see why admins would edit people's information unless there was a real reason to? @jlhogan any thoughts on this?

**Comment by jlhogan** [comment]
somehow just seeing this^ i think the ability to edit user's names is whatever -- won't be abused by staff, probably isn't actually all the useful. More important is the permissions stuff.
