### ISSUE TITLE
Roster API is still invoked from OEC admin view

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1288]
## Background
For whatever reason, if you log in to ECE Reporter as an OEC admin and navigate to your main admin view, you'll see in your network activity that you're still making paginated GET children requests only applicable to the roster view.  Note that this is **in addition** to the summary data API we make in order to display the admin overview presented to the user, making these quasi-expensive roster API calls virtually worthless (as we're doing _nothing_ with that data).

## Repro Steps
- Open the Network tab in your dev console
- Log in to ECE Reporter as an OEC admin user
- Observe the network activity on the main OEC admin view page

## Expected Behavior
- The roster API is not invoked, as OEC admin users don't have rosters to review

## Actual Behavior
- The roster API is invoked, consuming additional EBS and RDS CPU for virtually no reason

**Comment by vonbearshark** [comment]
If we haven't removed `swr` already, we might as well also add the `{ revalidateOnFocus: false, revalidateOnReconnect: false }` config to the `swr` calls while we are at it. It won't fix the issue, since we really want to (but can't) add `revalidateOnMount: false`, but it will help.

**Comment by JordanGuinn** [comment]
Closing - this has been fixed as part of https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1459!
