### ISSUE TITLE
DRAFT: Roster View: As an OEC Staff Member, I can view an Improved Roster Landing Page

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1303]
## Background
Currently, the roster is not represented in the best way conducive for staff members to see their enrollment data across all sites. The roster view should allow enrollment data to be filtered, searched, exported, and appended, which will allow all OEC Staff Members to view their rosters with greater ease. 

## Acceptance Criteria
1.  Roster view is treated as the home page of the user post-login.
2. Text representing the total number of children across all sites
   - Loading UX should be present until the numbers are calculated and ready to be displayed
3. 3 side-by-side buckets showing number of children in each age group. 
   - Loading UX should be present until the numbers are calculated and ready to be displayed

4. Four buttons shown horizontally, including:
    - `Search bar` (to search against **child name only**), `Export Roster`, `Upload File`, `Add Record`
    - `Export` should return **a non-paginated list of all child enrollments contained within the specified set of filters**

5. The tabular roster view now shows all children across all sites onto one filterable table:
   - Shows all children in all organizations/sites the user has access to, **INCLUDING** site-specific permissions
      - All entries in `OrganizationPermission` as well as all entries in `SitePermission` tables
   - It maps the following data for each child:
       - _Name_ (Last Name, First Name), _Age Group_, _Funding Type_, _Space Type_,  _Site_, _Enrollment Date_
   - Sorting dates in the table now results in `down arrow` filtering by descending order (most recent to latest dates) and `up arrow` filtering by ascending order. This is currently reversed and not in line with the other columns in staging 
6. Display on the bottom showing:
    - Number of entries out of total enrollments
    - Current page out of all pages that display the enrollments between arrows. **If there are more pages to display,** clicking on the arrows will shift over the roster page view to the next one.

## Designs
[Figma View](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)
![Roster View.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/b9b593a1-e893-4d16-bdc7-a64fa12dceb8)

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 @jlhogan Thoughts on how we might incorporate users with access to multiple organizations into this UX?  Could potentially be as simple as:

- Adding an `Organization` filter for those users specifically
- Update the organization header text to say `Multiple Organizations` or the like
- Update the subheader text to say something like `Your roster has x children across y sites over z organizations`

**Comment by ehuang525** [comment]
@jlhogan to your knowledge, is there a case for providers having access to multiple organizations? i would imagine that need would come from a SR liaison level which is different from this provider view but not super sure.

**Comment by jlhogan** [comment]
yes there are currently ~4 users who access data for multiple orgs

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 @jlhogan Any final word on if/how we might incorporate users w/multiple orgs into this UX?

**Comment by JordanGuinn** [comment]
Also, just to be overly explicit, does this default view (i.e. without any filters set) include **all enrollments** (active or not), or just the enrollments that haven't yet ended?

**Comment by ehuang525** [comment]
We'll review the multi-org solve today during today's design session! My suggestion is to create a new page for those users that lists the organizations they have access to and for them to click on each of them to view those rosters. Therefore no changes will be needed on the roster view itself. This seems like the most straightforward solution to me.

My attempt at responding to the questions:
- Are enrollments that haven't ended yet considered active enrollments? I would expect the number shown to reflect children that are currently enrolled and assume withdrawn records would not be displayed here.
- Might need more clarification on this!
- Search will be for the child name only. 
- Will also need some more context on this.

Let's discuss some of these items during the design session today.

**Comment by JordanGuinn** [comment]
Sounds like a plan - thanks for clarifying Emily!

**Comment by JordanGuinn** [comment]
Gonna close this ticket and throw all it's contents in the [Roster Redesign epic](https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1317), as it's since been decomposed into like 15-20 more actionable tickets.
