### ISSUE TITLE
DRAFT: Roster View: As an OEC Staff Member viewing the Roster Page, I can filter my roster view. 

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1304]
## Background
OEC Staff Members could see a tabular view of all their enrollment data across all sites. Within this, they could filter the data based on several parameters.

## Acceptance Criteria

1. Six dropdowns placed horizontally showing filtering options, including:
    - `Record Status` (**Options**: Complete, Incomplete)
    - `Age Group`
    - `Funding Type`
    - `Space Type`
    - `Site`
    - `Date Range`
2. Clicking on each dropdown option will add an indicator below showing which option was selected and subsequently filter the roster view.
3. Clicking on each dropdown option will show an outline around the selected dropdown.
4. Multi-select filter dropdowns should be created using the Carbon multiselect component
5. Filter selection bubbles should be made using the Carbon filter tag component

## Designs
[Figma View](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)
![Roster - Filter View.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/d7199e20-067d-450a-95c9-1113c914a304)

**Comment by JordanGuinn** [comment]
Making a note here specifically so I don't lose sight of it:

Whenever a user filters against an enrollment date range **specifically with an end date**, we should add an `Enrollment End Date column` to the roster view (and remove it when that filter is no longer applied)

**Comment by JordanGuinn** [comment]
Closing - I've captured all the requirements outlined here in 7 other tickets within the epic.
