### ISSUE TITLE
Manually/programmatically add email data to Fawkes users

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1313]
## Background
While we do currently have an `email` column in the `User` table of ECE Reporter, that column isn't currently populated with any actual data in any of our environments.  The emails of all of our users currently resides solely in Winged Keys.  In order to allow for our [user search functionality from within our OEC admin view](https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1310), we're going to need to both manually add that data to all the users that exist in our prod-like environments, as well as update any scripts/automated code responsible for auto-creating users accordingly in our non-prod-like environments.

## Acceptance Criteria
- All users in our `prod` and `devsecure` environments have their emails in the `Users` table in Fawkes updated manually
- All user mutation scripts in the repo are updated to include email address, including:
   - All scripts `src/data/prod`
   - All scripts `src/data/fake`
   - The user creation mechanism in `src/middleware/authenticate.ts`

**Comment by jlhogan** [comment]
alternatively, might it be a better idea to ignore the email column in ece reporter, and have the server make API call to wingedkeys to see if theres a user with that email? can we do that? or can we only look up by uuid? because keeping those emails in sync is an annoying and unnecessary step.... i added email column when we were talking about moving all of auth into ECE reporter and i was in there anyway so i just did it, but i dont think its the rightest way forward

**Comment by JordanGuinn** [comment]
The native IdentityServer 4 `userinfo/connect` endpoint we're currently using supplies user info based on jwt and jwt alone.  I'm sure we _could_ extend the Winged Keys API to include an endpoint to look up users by endpoint, but I'm not sure we want to, namely because:

1. We don't have any precedent for a hand-rolled IdentityServer API to be consumed by a different application, so effort there is kind of an unknown
2. We know WingedKeys is eventually going to be replaced with ForgeRock

Certainly neither options are particularly ideal; I just picked this one because it seemed somewhat simpler and less throwaway.
