### ISSUE TITLE
OEC admin users can access all the various roster and child detail views

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1316]
## Background
While non-admin users are currently prevented from accessing all admin views in any capacity, the reverse is not actually true currently.  While OEC admins are navigated to their default overview page by default (and don't have access to the roster navbar directly), they're _also_ able to access all provider roster views as well, if they know the direct URL.

It should be noted that both the corresponding non-admin views **and** the non-admin APIs should be appropriately gated by role.

## Repro Steps
- Log in to ECE Reporter **as an OEC admin**
- Manually attempt to navigate to the `Roster` view
   - Appending `/roster` to your URL should do it
- Observe

## Expected Behavior
- User is re-routed to the default admin overview page

## Actual Behavior
- User is able to navigate to the roster view, as well as all the detail/edit child views within

**Comment by JordanGuinn** [comment]
@jlhogan @ehuang525 @Derekskylight Something we uncovered a week or two ago - turns out that admin OEC users can actually access ALL views, including the roster, file upload, child edit, etc.  So they could theoretically edit child/enrollment data on behalf of given providers, whether accidentally or intentionally.

Thoughts on whether or not this is problematic?

**Comment by Derekskylight** [comment]
Ideally, it's probably best to have admin users only access specific views just to remove this possibility, but I wouldn't expect providers to be accidentally/intentionally editing another user's information. 
From what I've seen in usability sessions, users typically focus on the buttons/UX that are right in front of them and data enrollment/viewing, I didn't get the notion that they would be experimenting heavily with ECE Reporter's functionalities

**Comment by ehuang525** [comment]
In the current schema of things, how would the admin user access all the roster views? Does clicking on an organization in the list view take them to the organization's roster? 

If that's the case, we just have to make sure that when the admin user clicks on an organization's page that the roster isn't the most prominent thing. There may be a way we intentionally make roster access a bit more hidden. To my knowledge, the admin's primary goals are to create and edit org info so that's what we should present to them upfront.

**Comment by JordanGuinn** [comment]
If they just append `roster` to the end of their URL, they can get to the roster view without issue.  Unlikely an admin would ever _do_ that, so this likely isn't particular high priority, but did wonder in principle if we just wanted to prevent that across the board.

**Comment by jlhogan** [comment]
sure, let's prevent it. 
But also, since none of the admin are associated with any org or site permissions, I don't think they actually can access data.

**Comment by JordanGuinn** [comment]
Closing, as this is inherently addressed by #1347.

**Comment by JordanGuinn** [comment]
Re-opening, as it turns out this was never actually addressed.
