### ISSUE TITLE
Update copy/styles for ECE Reporter Help site

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1329]
## Background
The Mid-Year June deadline for data collection in ECE Reporter is coming up, and users should see a revised help page to clear up any relevant discrepancies for this submission, _not_ the December 2020 upload. Clearing this up will direct users towards a smoother collection process, and ideally help to minimize customer support requests this time around. Megan and Morgan have both made captured the [necessary updates to this copy in Google Docs](https://docs.google.com/document/d/1F1WOR0QcDHOE-02ZdqlPw2oZDjxefMvJH5zXRv0o5Wc).

**Note:** Crossed out items in red indicate removal of content, and new text with red indicate addition of content

**Please note that the ECE Reporter Help site contents are maintained in the `ece-reporter-support` repository, with the site itself residing at https://help.ece-reporter.ctoec.org/.**

## Acceptance Criteria
- The following pages on the ECE Reporter help site have been updated:
   - _[Home](https://help.ece-reporter.ctoec.org//)_:
      - Table of Contents has relevant parts removed or revised according to [in the main edits here](https://docs.google.com/document/d/1F1WOR0QcDHOE-02ZdqlPw2oZDjxefMvJH5zXRv0o5Wc/edit#heading=h.9dlztn5y0apr)
      - `What ECE Reporter does` has language added
      - `How to add records in ECE Reporter` has language removed
      - `How to update data with the template` has been updated with header styling, and July to December language has been removed
      - `Get more help with ECE Reporter` has July to December language removed, and necessary language added
   - _[Guide: How to prepare your July to December data](https://help.ece-reporter.ctoec.org//prepare-your-data/)_
      - Sidebar language has been updated to reflect general data collection
      - Title has been updated to reflect general data collection, not the July to December collection
      - Crossed out sections have been removed
   - _[ECE Reporter data requirements](https://help.ece-reporter.ctoec.org//data-requirements/)_
      - `Initial data collection period`, `Initial data submission deadline` sections have been removed
      - `Keep data up-to-date` has language removed

## References
- [ECE Reporter help site](https://help.ece-reporter.ctoec.org)
- [Content for the home page](https://docs.google.com/document/d/1F1WOR0QcDHOE-02ZdqlPw2oZDjxefMvJH5zXRv0o5Wc/edit#heading=h.cnvjj16106op)
- [Content for the July to December guide page](https://docs.google.com/document/d/1F1WOR0QcDHOE-02ZdqlPw2oZDjxefMvJH5zXRv0o5Wc/edit#heading=h.7q4pv8vlj44x)
- [Content for the ECE Reporter data requirements page](https://docs.google.com/document/d/1F1WOR0QcDHOE-02ZdqlPw2oZDjxefMvJH5zXRv0o5Wc/edit#heading=h.6uni0tnbbftl)

**Comment by JordanGuinn** [comment]
Blocked until language explaining the removal of a need for SASIDs has been added.

**Comment by jlhogan** [comment]
I dont think this should be blocked. Let's make these changes ASAP, and then add that language whenever we have it @JordanGuinn

**Comment by JordanGuinn** [comment]
alrighty, will make a note to follow-up on sasid language

**Comment by vonbearshark** [comment]
Just making a note for myself to also fix the link wonkiness where some links in the jekyll site have too many backslashes
