### ISSUE TITLE
Add search to roster

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1334]
## Background
Users should have the ability to search for child by **first and last name** from within their roster view, and get a subset of children based on that search.  Specifically, the search should operate as a substring match against the child's **entire name** (i.e. the child's first and last name joined together with a space).

Let's say, for example, that the following children exist within in our roster:

- `Alexander Hamilton`
- `James Vanderhaus`
- `Derek Alhambra`
- `Chad Sanders`

Assuming the above, a roster search with the text `der ha` should **only include** `Alexander Hamilton` as an applicable result.

## Acceptance Criteria
- Search bar is added to the roster view, with a clickable magnifying glass button on the end
   - Search button **cannot** be clicked unless **at least one character** has been entered
- [A computed column for `name`](https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver15) is added to the `Child` table, joining first and last name with a space
   - Should just be a simple DB migration
- When the search button is clicked, search string is included in the roster query and query is re-run
   - _If trivial_, hitting `Enter` should **also** initiate search
- Search should be **case-insensitive**
- Search should be a **substring match against first/last name, joined by a single space and treated as a single string**

## Technical Specs
In order to search on first and last name joined together, we'll need to [create an additional computed column](https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver15) in the `child` table based on the combination of those two fields (which will require a migration).  From there, we should be able to perform standard SELECT queries with wildcarded `LIKE` clauses directly against that new field.

## Designs
[The full set of designs can be found in Figma.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)

![image.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/f0389165-fd2a-407c-98ca-074487819448)

**Comment by JordanGuinn** [comment]
@jlhogan @Derekskylight @ehuang525 Got a few questions on how we envision roster search working:
- We only want to search against **first name** and **last name**, correct?
   - If so, how do we envision that working?  Like we search on the first name and last name fields independently of each other?  Or, as an example, if a user searched for `dan Gu`, would we expect `Jordan Guinn` to be in the list of search results?  (The latter is more effort than the former, fwiw)
- Do we want to impose a minimum character limit at all?
- Should there be any UI on the roster showing the user what they searched for, beyond just what's sitting in the search box?  Maybe something similar to the filter bubbles?

**Comment by ehuang525** [comment]
- Agree, case sensitive search here doesn't make much sense to me.
- Searching against first name and last name makes sense. In the example of `der ha` I think the only example from what you listed that would make sense as a result is `Alexander Hamilton` since it matches both the spelling and the space in between. Does that help?
- I don't think a minimum character limit would benefit the user since they would have to re-enter their search query again anyway to get the more specific result they were looking for. Open to hear other thoughts but don't think this is super important.
- Don't think we need the filter bubbles for search. The query can just sit in the search box which I think is a common interface pattern.
