### ISSUE TITLE
Make all roster table columns sortable

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1339]
## Background
Once we get a Carbon roster table up and functional in ECE Reporter, we should allow for each of the columns displayed within the table to trigger a **back-end sort** against all the enrollments retrieved.  By default, the table should be sorted in **ascending order by last name**.

## Acceptance Criteria
- Sort should take place **exclusively** on the back-end, as part of the overall roster query
- All columns in the roster table can be sorted in both **ascending** and **descending** order:
   - `Name` (sorted alphabetically by **last name**)
   - `Age Group`
   - `Funding Type`
   - `Space Type`
   - `Site`
   - `Enrollment Start Date`
- Arrow icon should point **down** when **descending**
- Arrow icon should point **up** when **ascending**
- Default roster sort should be the `Name` column

## Designs
[The full set of designs can be found in Figma.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)

#### Roster View w/Sort
![Screen Shot 2021-06-03 at 1.02.50 PM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/5323b26c-294a-491c-9441-44f8738b441b)

**Comment by JordanGuinn** [comment]
@ehuang525 @Derekskylight Few questions:

- What should the default sort column be when users navigate to the roster?
- Should sorting by `Name` sort by first name or last name?
- What does the `Enrollment Date` column pertain to? Enrollment start date or end date?

**Comment by JordanGuinn** [comment]
Answered the questions above in-person, so outlining the answers here:

- Default sort should be by **last name** (assuming names are displayed in the roster view as `Last Name, First Name`
- The `Name` column should sort by **last name**
- The `Enrollment Date` pertains to an enrollment's **entry** date, and should be labeled accordingly
   - On this same token, we should add an `Enrollment End Date` column if a user applies an `Enrollment Date` range with an end date

**Comment by bamader** [comment]
For clarity, we _don't_ want to just use the built-in sorting options that the Carbon data table gives us, right? Those columns already come with sort functionality if we extend them to do so. But it looks like we want things to be on the back end instead? If so, what should be the UI for that? Add our own arrows?

**Comment by vonbearshark** [comment]
Pairing with @lukenewman and it _looks_ like we might be able to use the Carbon UI/props with our context-based/backend search approach, but he's still proving it out for sure

**Comment by bamader** [comment]
Whoops didn't know y'all were working on this! I'll un-assign myself from it. Lemme know if you want any more eyes on it or some extra pairing!

**Comment by JordanGuinn** [comment]
@bamader I believe @vonbearshark & @lukenewman are pairing on back-end _search_, not sort?

**Comment by bamader** [comment]
Sounds good

**Comment by vonbearshark** [comment]
> Sounds like there's gonna be some good insights into if we can leverage current Carbon props to hit our APIs coming from that, but I think sort itself can be started on

This is right. Sorry for the confusion. I meant to suggest that the approach for both might be similar in that we might still be able to Carbon to work with the backend

**Comment by lukenewman** [comment]
@JordanGuinn currently, the children controller defaults to ordering by family income determination date, enrollment entry date, and enrollment funding first reporting period. do we want to keep those sorts and add these sorts on top of that?

**Comment by JordanGuinn** [comment]
@lukenewman Let's get rid of those previous sorts and just include support for the fields now present in our roster table
