### ISSUE TITLE
Create new placeholder roster page

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1340]
## Background
This ticket effectively marks the beginning of the roster redesign work!

First things first - we should do away with the previous roster page entirely, and create a brand new placeholder, containing nothing more than the **organization name**, **site count** and **child count**, both total and broken down by age group (all captured in the designs below).

## Acceptance Criteria
- New roster page is created, **replacing** the current roster view
   - Current roster view is removed
- Roster should **only** include what's captured in the screenshot below
   1. User's **organization** as the header (multi-user support to come later)
   2. Subheader of org **child count** and org **site count**
   3. **Child counts across age groups** in cards (we already have a UI component for this kinda thing)

## Designs
[The full set of designs can be found in Figma.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)

#### Initial Roster View
![Screen Shot 2021-05-19 at 11.37.55 AM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/4765bd52-48e5-4095-b02c-7bf02f700e08)

**Comment by bamader** [comment]
Documenting here a conversation I had with Jordan: the goal is to create a _complete_ overhaul/redesign of the roster, so as part of this ticket work I'll be making all the existing Roster stuff called `RosterOld`. That way we can keep it around until we're ready to delete the whole thing, but we're not tempted to pull from the code that's already there (the idea after all is to massively simplify what's going on).
