### ISSUE TITLE
Add explicit error UX to create org admin view

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1342]
## Background
As a provider creating new organizations, there are scenarios in which not all required tables are filled out correctly. In such a scenario, I can see error states/messages that show appropriate messaging and will redirect me to completely fill out the correct information. Doing so will increase the correctness of child enrollment data while also reducing the number of customer support requests submitted towards members of the OEC ECE team at Skylight. 

## Acceptance Criteria
- The `Please enter all required information` error text is displayed at the top of the page whenever there are **any** issues within the form to be corrected

#### Sites
- If a user has not properly filled out all fields for a particular site, an error in red text above the forms will be displayed indicating as much 
   - Error text should read `Please enter all required site information`
- The fields that need to be properly filled out should be receive a red border until they're corrected

#### Organization Name
- If user submits an organization whose name is already in the ECE Reporter database, user will receive a notification saying so and will not be able to submit the creation of this organization. 
   - Error text should read `This organization name already exists`
- The `Organization Name` field should receive a red border until corrected

#### Funding Spaces
- If user does not click on a funding space or form in this section, user will receive a notification saying so and will not be able to create a new organization until this has been clicked on
- The fields that need to be properly filled out should be receive a red border until they're corrected

## Designs
[The full set of designs can be found in Figma.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)

#### Sites Error UX
![Error.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/67c92059-4454-4c7d-b1b7-080bf50601c6)

#### Org and Funding Spaces Error UX
![Error2.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/5f8c5807-2ad9-4857-a8de-682e11477833)

**Comment by JordanGuinn** [comment]
@Derekskylight Do you remember the context for this ticket, by chance?

**Comment by Derekskylight** [comment]
Hey I cleared this up with Emily and this has to do with error states in org creation in the admin view! Editing ticket here accordingly.
