### ISSUE TITLE
As an OEC Provider, I can see an improved navigation bar

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1349]
## Background
Currently, the navigation bar has categories that are not particularly helpful to the user. As an OEC Provider, I should see an improved navigation bar with a more clear, intuitive navigation that is related to the user journey.

## Acceptance Criteria
- Current **roster** navbar is removed
   - Admin navbar to remain untouched
- Upon login, the new top-level navbar will include the following four links:
   1. **Roster**
      - On click, the user will be redirected to their roster page view. 
      - When a user is on the roster page, the "Roster" link is underlined according to USWDS styling
   2. **Resources**
      - On **hover**, the user is shown a Carbon dropdown with the following links:
         - _[Data Template](https://ece-reporter.ctoec.org/template)_
         - _[Data Requirements](https://ece-reporter.ctoec.org/data-requirements)_
         - _[Privacy Policy](https://ece-reporter.ctoec.org/privacy)_
      -  Clicking on "Resources" will not direct user to any page
   3. **Help**
      - On **hover**, the user is shown a Carbon dropdown with the following links: 
         - _[How To Guides](https://help.ece-reporter.ctoec.org/)_
         - _[Support Requests](https://ece-reporter.ctoec.org/support)_
      -  Clicking on "Help" will not direct user to any page
   4. **Log out**
      - On click, the user is logged out and redirected to the log-in page

## Designs
[Full Figma files can be found here.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=194%3A671)

#### Screenshots
![Nav1.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/0f5089fe-44df-4498-b090-8ba7d3021548)
![Nav2.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/6685f71f-5c16-4cf3-b2ee-2f4982a715d2)
![Nav3.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/ca5f86e9-aa62-4c00-b42d-25d03dad1179)

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 So to confirm, this will do away the current roster navbar entirely?

![Screen Shot 2021-05-20 at 3.24.01 PM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/7a46b8b1-e67a-45a4-bea2-a47dfad63076)

Which would mean that if users want to upload a file, they'll need to go to the roster view first.  Which makes sense to me, just want to confirm that's the case (so I can put this in the roster redesign epic).

**Comment by Derekskylight** [comment]
The roster view will now be the provider's landing page to upload a file from that view with the relevant button. Probably want this to be blocked by [DRAFT - Add "Upload File" and "Add Record" buttons to roster#1337
](https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1337) so that once we get rid of this nav bar^ there will be buttons/functionalities to upload rosters in!

**Comment by JordanGuinn** [comment]
That'd be great! 🙂

I know that the navbar work doesn't _really_ relate to the roster redesign, but if we did the two independently, we'd end up in a temporary situation where either:

- There's no way through the UI to access file upload (if we **fully replace** our current with the new)
- There are multiple navbars providing roster navigation (if we **kept** the current alongside the new)

**Comment by JordanGuinn** [comment]
@ehuang525 @Derekskylight Do we want to keep the current admin navbar we've been working on alongside this new navbar?  Or do we want to try and encompass those navigations in this top-level navbar as well?
![image.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/2690984b-5b27-4667-b1b1-6c137f54a7d1)

**Comment by Derekskylight** [comment]
IMO I would say keep it as that navbar is unique only to admins and keeping the new nav bar consistent across all users will allow the user to be more familiar with the entire experience. Plus since we've been working on this new bar already I'd recommend making the best use of that hard work!

**Comment by ehuang525** [comment]
To me the admin nav is inherently different from the provider nav since they are different users. I'm all for bringing the **pattern** of a single primary navigation in the upper right hand part of the page for admin but it will be a different navigation because of the contents. So I think the admin nav above can stay for now and we can tackle bringing that pattern in later so avoid confusion for the time being!

**Comment by JordanGuinn** [comment]
Sounds like a plan - thanks y'all!
