### ISSUE TITLE
 As an OEC Provider, I can see a monthly reminder to confirm that my data is up to date

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1356]
## Background
As an OEC Provider, I should be able to confirm that my data is complete within ECE Reporter on a monthly basis.  More specifically, I should be notified on the **first of every month** that I need to confirm my organization's data's accuracy for the **previous month**.

I should also be prompted to do so when I haven't yet, and I should be alerted that I have successfully done so when I have.

## Acceptance Criteria
- If the user's organization's data **HAS NOT** been confirmed to be up-to-date for the current month:
   - Starting on the **1st of every month**, users are prompted with a submission reminder modal **post-login** for the accuracy of data from the **previous month**
   - The user is _also_ shown a submission reminder alert on the roster page by default and on page refresh
   - Clicking the `Yes` button within the alert should pop a submission confirmation modal, allowing the user to explicitly confirm their data's accuracy through the current month for the specific sites that the user has access to
   - Once confirmed through the modal, a new `OECReport` row should be created for the user/org/month, and a success alert (captured below) should be shown
- If the user's organization's data **HAS** been confirmed to be up-to-date for the current month:
   - User is shown a submission confirmation alert **post-login**
   - Confirmation alert is shown through the remainder of the month

## Technical Details
The `OECReport` table is where we'll be tracking these monthly data submissions.  The presence of a row in that table containing the `organization` that a user belongs to and an `updateDate` within the current month should indicate that data **has been submitted**.

## Designs
[Full Figma files can be found here.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)

### Submission Reminder Modal
![Indicator.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/807dfacc-5782-4c5e-b567-439bac150d73)
#### Submission Reminder Alert
![Indicator2.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/345a163e-8e0e-4faa-9ee9-f834ea631e04)
### Confirm Submission Modal
![image.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/ac06d770-3cb4-43bd-91f4-5cc1b5ef1b6f)
### Submission Confirmation Alert
![Indicator4.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/5ffdfb00-44e5-42c2-95e4-751a8bd67f6e)

**Comment by JordanGuinn** [comment]
@Derekskylight @ehuang525 Few questions here:

- Did we ever decide on a monthly date with which to use to notify providers here?  Just the first Monday of the following month or something?
- Do we want to handle situations where providers fail to confirm their rosters over the course of multiple months?  If so, how?
- Do we want the `Your roster has been confirmed` alert to be present on all logins following roster confirmation?  Or is it just a one-time thing?

**Comment by JordanGuinn** [comment]
Answered the questions above in-person, so outlining the answers here:

- For now, let's start notifying providers on the **first day of the following month**, with the submission due date being the **second Friday of that same month**
- We shouldn't need to explicitly handle situations where providers fail to confirm their data over multiple months, as nothing really _changes_ in that scenario (they'll still need to just update their roster)
- The `Your roster has been confirmed` alert **should** be present on all logins following roster confirmation
