### ISSUE TITLE
As an OEC Provider, I can see an automated e-mail notifying me to update my roster

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1357]
## Background
As an OEC Provider, I should receive an automated e-mail notifying me to submit my monthly data. This will allow all providers within ECE Reporter to have their data accurate on a monthly cadence in one place rather than disparate sources. With updated data, users will be able to understand their data better, and this could also lay the groundwork for admins to see it or monthly reports to be created in the future.

## Acceptance Criteria
- Submission reminder email for **each month** is sent out on **the first of the following month**
   - This can be accomplished by setting up a [cron job](https://www.digitalocean.com/community/tutorials/nodejs-cron-jobs-by-examples) that utilizes SendGrid's API, an email provider we already have provisioned
- Email is sent to **all providers in ECE Reporter**
- Email contents match specs captured below

## Technical Details
While using something like [Serverless](https://www.serverless.com/)/[Lambda](https://aws.amazon.com/lambda/) is probably the most appropriate technical solution for something like this, it would require additional infrastructural investment (Lambda spin-up, API Gateway spin-up, Serverless configuration and permissioning, etc) that simply isn't worth the effort at this moment, _especially_ given the uncertainty around whether or not we'll even continue with AWS in the foreseeable future.  So, as an interim stopgap, let's just [set up a cron job on our Express server](https://www.digitalocean.com/community/tutorials/nodejs-cron-jobs-by-examples) to get this done.

## Designs
![Email.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/e72b8992-3c5f-4cae-848c-83b5915627a7)

**Comment by JordanGuinn** [comment]
@jlhogan @Derekskylight @ehuang525 Wondering if this is actually worth an engineering ticket at this point?  It looks like we can automate recurring batch emails entirely through the SendGrid UI, which would assuredly be quicker than whatever tech solution we'd roll out.

**Comment by JordanGuinn** [comment]
Update - spoke in person, and decided that because we would still need to continually update the list of users that emails get sent to, we might as well build a technical solution here.

**Comment by JordanGuinn** [comment]
@JordanGuinn FYI https://www.digitalocean.com/community/tutorials/nodejs-cron-jobs-by-examples

**Comment by bamader** [comment]
Structure question: where's the best place to put this code? I feel like we should probably give  it a new file somewhere within `src/` but I'm not entirely sure where.
