### ISSUE TITLE
Add Back button on file upload page

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#136]
File upload needs a back button to go the getting started page.

**Comment by RyanHansz** [comment]
@bamader can we use the same back button as the verify data table? 
<img width="501" alt="Screen Shot 2020-08-13 at 2 30 41 PM" src="https://user-images.githubusercontent.com/63253539/90172845-93446f00-dd71-11ea-8d05-9b57a4b7c987.png">

**Comment by bamader** [comment]
Sure! I'll set that up.
