### ISSUE TITLE
Remove reporting periods from ECE Reporter

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1373]
## Background
The `June 2021` reporting period is the **final** reporting period providers will be able to specify as the `first reporting period` for enrollment fundings, which naturally is problematic - it's currently June 2021!

Additionally, given the real lack of any value reporting periods have provided us up to this point, now seems like as good a time as ever to do away with them entirely, and simply allow for all fundings to have their own specific start and end dates.

## Acceptance Criteria
- `Reporting periods` display text in `Funding` cards is replaced with `Funding period` (to indicate range between new start and end date)
- Fundings can be created/edited with a custom start/end date, independent of any previous notion of reporting periods
   - `First reporting period` dropdown is replaced with `Funding start date` datepicker across the application
   - `Last reporting period` dropdown is replaced with `Funding end date` datepicker across the application
- File uploads are updated according to of the following:
   - Map `First funding period` and `Last funding period` columns to these new columns
   - Change `First funding period` and `Last funding period` to `Funding start date` and `Funding end date` in the upload template

## Technical Specs
- Migration is written to add `startDate` and `endDate` columns directly to `Funding` entity
- ETL is written to perform the following for all current fundings:
   - For enrollments with **a single funding**:
      - Copy `enrollment.entry` into `funding.startDate` column
      - Copy `enrollment.exit` into `funding.endDate` column
   - For enrollments **with multiple fundings**:
      - Copy `reportingPeriod.startDate` of **first reporting period** into `funding.startDate` column
      - Copy `reportingPeriod.endDate` of **last reporting period** into `funding.endDate` column
- Follow-up migration is written to remove `firstReportingPeriod` and `lastReportingPeriod` columns from `Funding` entity
- Funding decorators are updated to reference the new `startDate` and `endDate` columns directly

**Comment by Derekskylight** [comment]
Hi! Just to confirm with this, will the Excel file template also be reflected to show these changes? And will file upload still accept the template if there is any missing data under the column 'first funding period?'
