### ISSUE TITLE
DRAFT - Add time periods for funding spaces within Admin views

### ISSUE THREAD

**Issue by ehuang525** [ctoec/data-collection#1376]
## Background
In the current Admin features, users can add funding spaces when creating an organization. They are also able to edit these funding spaces when viewing an organization that has been already created.

From conversations with various OEC folks, it would be valuable to assign time periods for each of those funding spaces so that utilization over time can be tracked with more specificity. Adding time periods to funding spaces will impact the UI on both creating and editing an organization. 

## Acceptance Criteria
In the Create Organization view, each funding space instance contains `Start Date` and `End Date` in addition to the dropdowns/fields that already exist (Funding source, Age group, Space type, Capacity). 

In the View/Edit Organization view, each funding space that has been already created will live in its own card. 
- _Site (currently not in scope), age group, space type, and current capacity_ are displayed as static text. In the previous version of this page, this information were editable.
- Upon expanding the "View and edit capacity" accordion link, there will be a table of historical capacity as well as the ability to add another instance of capacity. Users are able to add and delete capacity instances but not edit them directly. 
- In the table view, each row will display _Start Date, End Date, Capacity,_ as well as the ability to delete that instance.
- Under **"Add Capacity"**, users can input _Start Date, End Date, and Capacity._ Clicking on **"Add Capacity"** will add this instance to that funding space.
- **"Remove funding space"** will remove a funding space unless that funding space currently has enrollments assigned to it. This removal link is likely to be used moreso in situations where an Admin is creating a new funding space and needs to remove it out of error, before it has been assigned to any specific enrollment.
- In the case where there are inactive funding spaces that are no longer current and not assigned, they can live in an "Inactive Funding Spaces" page accessed from the link in the Funding Spaces section.

## Designs

[Figma file can be viewed here](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/?node-id=2%3A2).

Funding spaces in Create Organization
![CreateOrg_FundingSpace.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/ceb449a7-bbb3-4528-91c2-499153d2e7a2)

Funding spaces in View/edit Organization
![ViewEditOrg_FundingSpace.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/97ff063d-4b97-4d04-baa3-1d25d55ea3fe)

Inactive funding spaces
![Admin - Organization - Inactive Funding Spaces.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/587944f6-759e-4efb-b37b-60e4e55b9c71)

**Comment by JordanGuinn** [comment]
Closing - we've since decided that a historical funding spaces MVP for our admin view will look a good deal simpler!
