### ISSUE TITLE
Remove sorting on data definitions table.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#138]
Likely best to keep the data definitions in the same order as the template. 
<img width="1057" alt="Screen Shot 2020-08-11 at 1 29 51 PM" src="https://user-images.githubusercontent.com/63253539/89929112-c7cff380-dbd6-11ea-8084-2678e1629218.png">

**Comment by bamader** [comment]
When the page initially loads, for me the fields are in the order specified by the template. It looks like you pressed the sort button (the little arrow by Field Name turned purple, but it starts as grey). Do you want to get rid of the sort functionality in the column?

**Comment by RyanHansz** [comment]
Yes, remove the sort functionality and just leave it as the template order
