### ISSUE TITLE
DRAFT - Update funding space UI in create org admin view

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1385]
## Background
In the current Admin features, users can add funding spaces when creating an organization. They are also able to edit these funding spaces when viewing an organization that has been already created.

From conversations with various OEC folks, it would be valuable to see the historical capacity of certain funding spaces. For this, the usage of an accordion will be helpful in seeing this information

## Acceptance Criteria
In the Organization view, each funding space instance displays the following:
- Funding source, age group, space type, and current capacity along with its start date. This is different from the previous iteration of an organization's funding space, in which the funding space information was kept in editable fields.

Within each funding space instance, users can expand an accordion to reveal additional function: 
- Upon expanding the _"View and edit capacity"_ accordion link, there will be a table of historical capacity as well as the ability to add another instance of capacity. Users are able to add and delete capacity instances but not edit them directly. 
- In the table view, each row will display _Start Date, Capacity,_ as well as the ability to delete that instance.

## Designs

[Figma file can be viewed here](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/?node-id=2%3A2).

![Accordion.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/411b5a49-7f1e-453b-8429-81dad0399b87)

**Comment by JordanGuinn** [comment]
Closing - for the purposes of tracking multiple capacities for a single funding space, we've decided to simply start storing them behind the scenes and largely leave the UI as it is currently is!
