### ISSUE TITLE
DRAFT - As an OEC Admin, I can delete an instance of the historical capacity within a funding space

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1387]
## Background
In the current Admin features, users can add funding spaces when creating an organization. They are also able to edit these funding spaces when viewing an organization that has been already created.

From conversations with various OEC folks, it would be valuable to assign time periods for each of those funding spaces so that utilization over time can be tracked with more specificity.

## Acceptance Criteria
- **"Delete"** will remove the instance of the historical capacity from the specific funding space
- The instance will be deleted from the storage of funding spaces, and its display in the tabulated view will be removed from the user's point of view

## Designs 
[Figma file can be viewed here](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/?node-id=2%3A2).

![Delete Capacity.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/3038dbc9-0ee2-4054-9f86-3ecaca76999e)

**Comment by JordanGuinn** [comment]
Closing - for the purposes of tracking multiple capacities for a single funding space, we've decided to simply start storing them behind the scenes and largely leave the UI as it is currently is!
