### ISSUE TITLE
DRAFT - As an OEC Admin, I can remove a funding space 

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1388]
## Background
In the current Admin features, users can add funding spaces when creating an organization. They are also able to edit these funding spaces when viewing an organization that has been already created.

From conversations with various OEC folks, it would be valuable to assign time periods for each of those funding spaces so that utilization over time can be tracked with more specificity.

## Acceptance Criteria
- **"Remove funding space"** will remove a funding space if there is 0 capacity assigned to it. If there is capacity other than 0, the funding space cannot be removed and an error message will display. This removal link is likely to be used in situations where an Admin is creating a new funding space and needs to remove it out of error, before it has been assigned to any specific enrollment.
- Engaging in this action will trigger a modal to be displayed asking the user to confirm whether they want to remove this particular funding space.

## Designs 

[Figma file can be viewed here](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/?node-id=2%3A2).

![Remove Funding Space.PNG](https://images.zenhubusercontent.com/602d78337403e44d7db5c4f3/1d078747-909b-4d01-b617-404c7040eaf2)

**Comment by JordanGuinn** [comment]
@ehuang525 @Derekskylight Is the first AC bullet point saying that all capacity entries for a given funding space will need to be deleted before the funding space itself can be deleted?

**Comment by JordanGuinn** [comment]
Closing - for the purposes of tracking multiple capacities for a single funding space, we've decided to simply start storing them behind the scenes and largely leave the UI as it is currently is!
