### ISSUE TITLE
Provide visual cue to user that an Edit page has unsaved changes

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#1396]
## Background
We currently have three places in the app where a user can make changes to information in a form: Edit Record, Edit User, and Create Record. On these pages, no information is persisted to the DB until the user presses save. However, it would be nice to provide some sort of visual cue to users if they have unsaved changes on the page (which appear either when they attempt to navigate away from the page, or which appears as a small but persistent alert at the top of the page whenever the user starts modifying information).

## Acceptance Criteria

**Comment by JordanGuinn** [comment]
Closing - read-only views are going to be something we introduce to both the provider and admin UX, which will thereby force users to be intentional about the actions they take when they do so (implicitly addressing this issue).
