### ISSUE TITLE
I can enter data for school readiness funded enrollments

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#142]
**Funding types:**
CSR (Competitive School Readiness)
PSR (Priority School Readiness)

**Space types:**
Full Day	
School Day
Part Day
Extended Day
		

**Other data needed:**
On the backend, we will need to associate each school readiness funded program with a school readiness community (and liaison eventually)

**Comment by jlhogan** [comment]
funding types == FundingSource enum
space types == FundingTime enum
add a model for Community with minimally:
- id
- name
- organizations: [] (and so org should be updated to have an optional communityId)

@RyanHansz can u confirm that it is organizations, not sites, that should be linked to communities  ?

**Comment by RyanHansz** [comment]
Organizations are linked to communities. Here's a screenshot of the slot grid as an example
<img width="810" alt="Screen Shot 2020-08-13 at 11 55 51 AM" src="https://user-images.githubusercontent.com/63253539/90157622-f0cdc100-dd5b-11ea-950c-158c97abd3eb.png">
