### ISSUE TITLE
Update to LTS of Node 14

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1458]
## Background
According to [the releases section on the NodeJS website](https://nodejs.org/en/about/releases/), Node v14 (codename **Fermium**) is the current version with active LTS support.  And while v12 is still going to receive maintenance support for about another year, we might as well try bumping our major version to v14 and take advantage of [some of the benefits it brings](https://nodejs.medium.com/node-js-version-14-available-now-8170d384567e).  Assuming it doesn't end up being a huge rabbit hole, of course...

## Acceptance Criteria
- All components in `component-library` function as they did previously
   - `engines` in `package.json` will need to be updated accordingly
- ECE Reporter can be built and deployed to remove environments as it could previously
   - Will require a tiny Terraform update to the Node runtime used by Elastic Beanstalk
- ECE Reporter can be built and run **locally** as it could previously, on the following hardware:
   - **macOS** machines
   - **M1** machines
   - Directly through **Docker**
- READMEs are updated accordingly

**Comment by jessethach** [comment]
@JordanGuinn Is there a story to update the shared components library as well?

**Comment by jessethach** [comment]
> @JordanGuinn Is there a story to update the shared components library as well?

It's looking like I will need to update that repo as well. Getting a compatibility complaint when using `yarn install` after upgrading node engines and nvm rc.
