### ISSUE TITLE
Update copy in Edit Record view

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1483]
## Background
There have been numerous customer support requests on the specific use cases for withdrawals and/or changing enrollment. Users haven't been cross-referencing the long help page content, and the tool isn't as intuitive as we'd like to guide them in the specific scenario to use the `withdraw` or `change age group/site`. Updating the feature information and notation in an explicit manner should help in alleviating this confusion.
On the modal for each action, explicit language will be presented to show the scenarios for using each feature. 

## Acceptance Criteria
- The `Change age group and/or site` quick action has been renamed to `Change enrollment`
- Copy outlined in the designs below has been added right beneath the child's name header
- The `redetermine` link in the added copy opens up the `Income Determination` tab on the Edit page
- The `change enrollment` and `Withdraw` links open up the corresponding action modals

## Designs
[Final designs can be found here.](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/ECE-Reporter-%E2%80%93-Final-Designs?node-id=86%3A348)

#### Current Edit Page
![Screen Shot 2021-09-23 at 9.40.40 AM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/86208a0a-04af-47c3-84e5-3a1d9145b6be)

#### Updated Edit Page
![image.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/9d10f52f-9558-4597-9d49-382b51c4fb67)

**Comment by JordanGuinn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ECE-Dev-Board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1483?planning-poker) with ZenHub @lukenewman @nickbristow

**Comment by Derekskylight** [comment]
Also note the text should be "If your child has aged out into a non-funded program or **is** no longer part of any funded program"!

**Comment by JordanGuinn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ECE-Dev-Board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1483?planning-poker) with ZenHub @vonbearshark
