### ISSUE TITLE
As an OEC Provider, I can view detailed withdrawal information in a popover/tooltip

### ISSUE THREAD

**Issue by Derekskylight** [ctoec/data-collection#1486]
## Background
There have been numerous customer support requests on the specific use cases for withdrawals and/or changing enrollment. Users haven't been cross-referencing the long help page content, and the tool isn't as intuitive as we'd like to guide them in the specific scenario to use the `withdraw` or `change age group/site`. Updating the feature information and notation in an explicit manner should help in alleviating this confusion.
In a pop-up/hoverover, explicit language will be presented to show the scenarios for using each feature alongside information describing what the definitions explicitly mean in ECE Reporter. 

### Change Age Group/Site
- [Tooltip](https://www.carbondesignsystem.com/components/tooltip/usage/) or [Modal](https://www.carbondesignsystem.com/components/modal/usage/) has been selected
- Selected design has the following text added onto it in `(pop-up/hoverover?)` format: 

If a child has changed age group or site, please provide the updated enrollment information below. Changing a child’s age group or site will still retain the record of their previous enrollment.`

If a child is no longer part of your roster and has not moved to a different age group or site, they should be withdrawn.

### Withdraw
- [Tooltip](https://www.carbondesignsystem.com/components/tooltip/usage/) or [Modal](https://www.carbondesignsystem.com/components/modal/usage/) has been selected
- Selected design has the following text added onto it in `(pop-up/hoverover?)` format: 

If a child is no longer enrolled within your roster, you may withdraw them.

However, if a child has changed age group or site but is still enrolled, they do not need to be withdrawn. You may change their enrollment instead.`

## Designs
TBD

**Comment by ehuang525** [comment]
@Derekskylight @JordanGuinn With the updated child record page copy, not sure if this is a necessity or priority at the moment until we learn more about the provider's journey(s).

**Comment by JordanGuinn** [comment]
Agreed - I think we move forward with what's specified in https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1483 for now, then wait for further feedback to provide more context (just in case that doesn't end up being enough).
