### ISSUE TITLE
Re-upload of same file multiple times silently breaks

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1520]
## Background
For whatever reason, only on the `EPIC-roster-redesign` branch, uploading the same file multiple times is causing 500 errors to be thrown by our upload API.  This route should be idempotent (as is the case in production currently), with the second upload simply being treated as a collection of no-op updates.

## Repro Steps
- Navigate to ECE Reporter
- Download the `Completed Sample Date` upload file from the `dev` utility
- Upload said file to ECE Reporter
- On completion, delete one of the child rows manually from the roster
- Re-upload that same file again
- Observe

## Expected Behavior
The user's re-upload is handled successfully, processing the file as primarily updates, with one additional child row addition.

## Actual Behavior
The user's re-upload causes the upload API to throw a 500, and the user remains stuck on the `Confirm Upload` page without any indication as to what happened.

**Comment by lukenewman** [comment]
i am unable to reproduce this bug. upon re-uploading the same file after deleting one record, the entirety of the file is uploaded again as new records, resulting in 39 records. is this expected?

**Comment by bamader** [comment]
No that's definitely not expected. It should recognize the other 19 records as duplicates of entries already in the system and not re-upload them. So unfortunately that is a new bug.
