### ISSUE TITLE
Close button in submission confirmation modal is positioned weirdly

### ISSUE THREAD

**Issue by JordanGuinn** [ctoec/data-collection#1541]
## Background
The `Close` (or `X`) button in the data collection submission modal has somehow overflowed to underneath the modal header, which looks really weird and screwy.  We should fix this, bringing the button back to the upper right-hand corner of the modal.

Screenshot captured below.

## Acceptance Criteria
- The `Close` button is in the top right-hand corner of the modal
- The `Close` button continues to function as it did previously

## Screenshot
![Screen Shot 2021-10-26 at 7.20.16 PM.png](https://images.zenhubusercontent.com/5ff504ac246966652b569927/fe8ae302-7158-4f77-bdf1-0e05975ce745)

**Comment by JordanGuinn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ECE-Dev-Board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1541?planning-poker) with ZenHub @bamader @GordonFarrell @jessethach @lukenewman @nickbristow

**Comment by lukenewman** [comment]
what branch is this on? i can't find the modal on `base`

**Comment by GordonFarrell** [comment]
https://github.com/ctoec/component-library/pull/174

**Comment by GordonFarrell** [comment]
Accidentally bumped the component library version directly on the RELEASE-monthly-submission-alerts branch, so that'd be the branch to use to validate this. Thanks!
