### ISSUE TITLE
Remove user permissions UI from the Create/Edit Org views

### ISSUE THREAD

**Issue by ehuang525** [ctoec/data-collection#1543]
## Background
With the addition of the School Readiness Liaison view, user permissions must be modified to include the ability to assign roles to users. Due to the complex nature of the relationships between roles, organizations, sites, and users, it would be simpler for permissions to only be assigned at the user level. Therefore, we can remove the permissions section at the organization level -- on both the Create and Edit views.

## Acceptance Criteria
- Permissions section is removed from the `Create Organization` page.
- Permissions section is removed from the `Edit Organization` page.
- Corresponding API logic to handle user permissions when editing/creating organizations is removed
- Admins can now only assign user permissions from the `Create User` and `Edit User` pages

## Designs
[Figma file can be viewed here](https://www.figma.com/file/GcYwZ05CjnG6QZNYlsCS1X/?node-id=2%3A2).

![Create org without permissions.png](https://images.zenhubusercontent.com/6050f59bb12f6b5f4da9aeb1/a7cf2ca7-9164-439c-8eed-99c8b4500a2c)

**Comment by lukenewman** [comment]
@JordanGuinn should this work be based off of `base` or `EPIC-oec-admin-view`?
