### ISSUE TITLE
Rebase Epics on base

### ISSUE THREAD

**Issue by nickbristow** [ctoec/data-collection#1592]
## Background
Need to update our Epic branches to keep up with changes on base

## Acceptance Criteria
Three epic branches are up to date with base
Epic roster redesign
epic file upload
monthly roster submission

## Technical Specs
Specify any **technical** requirements that need to be met in in order to mark this ticket as done.

## Designs
If applicable, include any mockups or other additional designs for this user story.

## Additional Context
If there's any additional context necessary for the engineer picking this ticket up, please provide it here.

**Comment by lukenewman** [comment]
@nickbristow is `RELEASE-monthly-submission-alerts` the right branch for "monthly roster submission"?

**Comment by nickbristow** [comment]
@lukenewman yes it is
