### ISSUE TITLE
add child info form

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#162]
blocked by #160

**AC**: 
- adds forms to edit child info to the child info tab
- forms use "Child" as root form data type
- on submit, form PUTs to a new `children/:childId` PUT endpoint, which updates the child object in the database

<img width="1023" alt="Screen Shot 2020-08-17 at 3 34 42 PM" src="https://user-images.githubusercontent.com/63253539/90436725-2eee1c00-e09f-11ea-9f79-5095d5666111.png">

**Comment by mmazanec22** [comment]
Closed by #202
