### ISSUE TITLE
As a provider, I can log in with my username and password.

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#17]
[Mockup](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&sha=721beadef8c072936fe5c4358852ea21dd9f32b5)

I can log in to staging using the username `voldemort` and password `thechosenone`. 
If I enter an invalid username or password, I seen an error that I have "Invalid username or password."

When I am logged in, I see "Hi, [firstName]" in the header in the top right hand corner.

I can log out by clicking "Log out" in the header's upper right hand corner.

When I log out, I am taken back to the sign in page.

**Comment by cailyncodes** [comment]
Closed by #22
