### ISSUE TITLE
**Don't move** QA Testing list and Data for Uploading

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#184]
See QA steps [here]
(https://docs.google.com/document/d/1zOI8Py2MCMevK80YNleFZF-RrX0CFqFqO9B9qgiTGPQ/edit#)

See enrollment changes to test [here](https://docs.google.com/spreadsheets/d/1xXusioyhPRJKKt3DCV5law1vmmGyz2MhYWSSERjcyfA/edit#gid=0)

[SCenariotesting.xls.zip](https://github.com/ctoec/data-collection/files/5537788/SCenariotesting.xls.zip)

Files for upload here:
[Data Template page](https://staging.ece-fawkes.ctoecskylight.com/template)

**Comment by lucasolivia** [comment]
Data template with dummy data inside the zip folder is 2 options for quantity of data 200 or 1000 and 2 options for testing with essential data missing or "blanks" or without "blanks" [


[dummy data data templates.zip](https://github.com/ctoec/data-collection/files/5335134/dummy.data.data.templates.zip)

](url)
