### ISSUE TITLE
As a provider, I can download the spreadsheet template from the Getting Started page

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#19]
When I log in, I land on the [Getting Started](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=f128d451-cb06-4a7a-bd3a-0e775883af75&present=true&preview=false&sha=d0e45d802a3591157e933772e71eb5a474ca35d7) page which has links to download the [spreadsheet template](https://docs.google.com/spreadsheets/d/1Td7MRxWLWs6osdvC1nfzmtuhztPCB-MkTCNUfgocV7o/edit#gid=0) as an Excel or CSV file.

Clicking either of these links downloads the file to my computer.

**Comment by cailyncodes** [comment]
Is there a link to the Google sheets or just the CSV download? If I convert the linked Google Sheet into a CSV, it will lose some formatting (and might not be able to have multiple tabs), is that intended?

**Comment by RyanHansz** [comment]
@julyytran it'd be good to get a product/engineering view into the accepted format column of the data definitions (which will be its own page of content in Fawkes):
https://docs.google.com/spreadsheets/d/1Td7MRxWLWs6osdvC1nfzmtuhztPCB-MkTCNUfgocV7o/edit#gid=112823525&range=F2

**Comment by RyanHansz** [comment]
CSV: https://docs.google.com/spreadsheets/d/1Z5YHVDBC5HLp3nebRimOrw5z7ifDFZn_M3Yk2OtEokI/edit?usp=sharing
Excel: https://docs.google.com/spreadsheets/d/1Td7MRxWLWs6osdvC1nfzmtuhztPCB-MkTCNUfgocV7o/edit?usp=sharing
(To be updated as we confirm content and requirements)
