### ISSUE TITLE
Add record: I can add enrollment records to my roster data.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#204]
![Enrollment](https://user-images.githubusercontent.com/63253539/91859244-359c9780-ec38-11ea-84c4-833246d6f4c9.gif)

# Acceptance Criteria
- I can click the "add enrollment" button on the verify data page
- Clicking the add enrollment button launches the enrollment flow 
- The enrollment flow contains all data elements in the following sections
-- Child identifiers
-- Child demographics
-- Family Address (previously family info)
-- Family Income Determination
-- Enrollment and funding

- I can save the enrollment to my roster by hitting the save and finish button at the end of the enrollment and funding section
- I can save the enrollment and hit the "save and add another record" to start another enrollment

- I know the new record was added when I see the success message on the verify enrollments page that reads: **"Record added** [Child name] was added to your roster."

**Comment by RyanHansz** [comment]
Missing info validations can be added in a later ticket.

**Comment by RyanHansz** [comment]
Family homelessness question is now in the family info section.

**Comment by mmazanec22** [comment]
Closed by #293
