### ISSUE TITLE
Funding and Space types: I can enter data for all the possible funding and space type combinations

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#207]
As a user, I want funding and space types to match the format in which I already record them. I want to avoid my batch upload failing because I had the wrong formatted space type. 

**Acceptance criteria**
• Users can see the space types from a link on the data definitions page:
![Space types](https://user-images.githubusercontent.com/63253539/91095557-96214880-e62a-11ea-8180-cce3f590822a.gif)

• All of the below spaces are supported by the data model and listed in the space type page:
**Child Day Care or CDC:**
- 1 or Part time or PT
- 2 or Full time or FT
- 3 or Full time/part time or PT/FT or split time

**Priority School Readiness or Competitive School Readiness or School Readiness or PSR or CSR:**
- 4 or Full-day or Full-day/Full-year or FD
- 5 or School-day or School-Day/School-Year or SD
- 6 or Part-Day or Part-Day/Part-Year or PD
- 7 or Extended day or ED

**State Head Start or SHS**
- 8 or Extended day or ED
- 9 or Extended year or EY

**Smart Start or SS**
- 10 or School day or School-day/school-year or SD

**Comment by JordanGuinn** [comment]
@RyanHansz @jlhogan Got a couple questions for this one:

1. Right now, if a provider uploads a file with a row that contains a `Funding type` value that we don't recognize, we allow that record _but_ leave the `Funding type` column blank.  Do we want to apply that same behavior for unrecognized `Funding space` values as well?

2. Even though we're allowing users the ability to upload records with multiple format variations for each `Funding space` value, do we actually want to _store_ those values as they're uploaded?  I'd imagine we'd instead want to implicitly convert them to the singular `Space Type` values we have defined in our [data requirements page](https://staging.ece-fawkes.ctoecskylight.com/data-requirements) (Full, Part, Split, ExtendedDay, ExtendedYear, School) and instead save _those_ (for the sake of consistency), but I just wanted to confirm.

**Comment by jlhogan** [comment]
i'll leave 1 to ryan
quick clarification: `Funding space` is an actual data entity, associated with a specific organization that has a `FundingSource` (aka the type of funding, CDC, PSR, etc), a `FundingTime` (aka the type of slot for that funding these spaces represent; we sometimes call this "contract space" as well -- aka Full Time, Half Day, etc) and a capacity (the # of individual children that the organization has $ to funding via the given funding source for the given funding time)
re 2: I think for the _most_ part we've been storing raw user data (barring dates and booleans) in the FlattenedEnrollment table, and then doing the real look up when we do the mapping. I think it'd be fine to do the same here as well.

**Comment by RyanHansz** [comment]
to 1: We can leave it blank for this round. To get my thoughts down for how it can be developed in the future:
- the next step would be flagging it in the missing info validation #92 
- and then flagging it if it happens in batch upload 
- Want to avoid someone batch uploading 200 records with the wrong space type.
