### ISSUE TITLE
Validate upload

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#21]
As I provider, if I try to upload a CSV or Excel file that is not formatted according to the template, or if I try to upload a file that is not a CSV or Excel file, I get an error that I must upload a CSV or Excel file formatted according to the template.

First pass - check ~file type and~ headers

**Comment by jlhogan** [comment]
file type will be enforced by the upload, so users will not be able to upload data that are not excel or csv

**Comment by jlhogan** [comment]
first pass could be returning parsed raw data from a new `/reports/id` GET endpoint, and confirming that headers match the headers in the template
