### ISSUE TITLE
Zip codes starting with '0' are parsed as dates

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#217]
In uploaded excel spreadsheets, zip codes beginning with a 0 (as many state of CT zip codes do) are treated as four digit numbers when excel turns them into strings (it throws away the 0). This then gets parsed as a year by the Moment check in parseUploadedTemplate, and so a UTC timestamp is stored in place of the zip code in the family object.

**Comment by RyanHansz** [comment]
We'll either need to provide everyone using the tool with instructions on how to keep 0s in zipcodes or somehow get our data template to keep them.

**Comment by RyanHansz** [comment]
<img width="245" alt="Screen Shot 2020-08-31 at 11 09 24 AM" src="https://user-images.githubusercontent.com/63253539/91735553-759d4500-eb7a-11ea-8d2e-f3e2bef6063f.png">

**Comment by RyanHansz** [comment]
01920 gets turned into:
<img width="288" alt="Screen Shot 2020-08-31 at 12 06 45 PM" src="https://user-images.githubusercontent.com/63253539/91741259-78039d00-eb82-11ea-9870-42bf2b27610c.png">
