### ISSUE TITLE
add "model type" to enrollment (virtual, in person, hybrid)

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#223]
"model" exists on FlattenedEnrollment, but not Enrollment.

**AC**
- Create enum for CareModel with values "In person", "Virtual", "Hybrid"
- Add `careModel` field to Enrollment, of type `CareModel`

**Comment by RyanHansz** [comment]
Need to check with OEC that this is a data collection requirement (I've just been assuming it is)

**Comment by RyanHansz** [comment]
@bamader got updated definitions for this data element:
**Format:**  In-Person, Hybrid, Distance
**Definition:** In-Person: In-school learning for all students on a full-time basis. 
Hybrid: A combination of both in-person and remote learning support resulting in a limited student population on school premises at any given time. 
Distance: Learning opportunities in which students and educators are not physically present in a classroom environment.
