### ISSUE TITLE
Support unique ID type for a site. 

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#235]
**AC** 
- The system reflects the type of unique ID (if any) my organization uses
- Text in the app reflects the type of unique ID my organization uses when adding and viewing a child record
- If my organization does not use a unique ID, the field is hidden when adding and viewing a child record

**Tasks**
- Make sure User site and organization model can support all these things
- Add additional optional Unique ID field to child (in addition to optional SASID field)
- Template and the forms show/hide appropriate unique ID field

**Comment by RyanHansz** [comment]
@jlhogan started added specific data elements here, feel free to tweak!

**Comment by RyanHansz** [comment]
Unique ID:
at what level do we need to know this ?

multi-org and/or org, so add a field to both
one field or two booleans
add additional optional uniqueId field to child (in addition to optional SASID)

make template reflect SASID or other unique ID

UI will only show the user the field they need, or neither if we know they do not use one

**Comment by RyanHansz** [comment]
- one field or two booleans

- add additional optional uniqueId field to child (in addition to optional SASID)

- make template reflect SASID or other unique ID

- UI will only show the user the field they need, or neither if we know they do not use one

**Comment by jlhogan** [comment]
@JordanGuinn just wanted to call out i just updated this ticket, sorry that was  hanging around in a weird state

**Comment by JordanGuinn** [comment]
Thanks for the heads up!  No worries at all - I'm probably just gonna take my face off this ticket for the time being, at least until the rest of the MVP devops tickets are done
