### ISSUE TITLE
As a provider who has uploaded my data, I can view the data I've upload to confirm accuracy.

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#24]
[Mockup](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=d1e55b27-ba88-4edb-adfe-761469fcb9c8&present=true&preview=false&sha=c48a65163e8532e6de4b7594d18763f321e83306)

After I have uploaded my data, I can click "Check your data" to see a view of the data I have uploaded.

I see how many records I have uploaded.
I see a table that shows the data I've uploaded.

If this information looks incorrect, I can go "Back to upload" to re-upload a file.

**Comment by RyanHansz** [comment]
@julyytran edited the mockup on this to have an actual table design instead of a google sheets screenshot

**Comment by RyanHansz** [comment]
Note to self: Show how this evolves into a version where the provider can see changes from last upload. And possible showing translation from what they uploaded into whatever our database standardizes it as (example: Upload is "M", our database is "Male")

**Comment by JordanGuinn** [comment]
For whoever picks this up, #83 looks like it includes some technical particulars for this ticket.
