### ISSUE TITLE
OEC View - submission status overview

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#243]
## Acceptance Criteria
- New **Submissions Status** view is created and wired up, following the [linked designs](https://app.abstract.com/share/4d17d6ac-17d7-48ae-9a12-3592d68aae76?collectionId=6e3972b5-1dd6-470d-b2fb-f50b5d9264c9&collectionLayerId=903621f7-7347-4411-b4f5-9d380c96d13f&present=true&preview=false&sha=c174feadd60c143ad7a4cc6889dada00b71eeeff)
   - View is treated as the home page for "OEC" users (they are navigated here post-login)

## Technical Details
- Add a `isAdmin` column to the `user` table, allowing for the delineation between OEC users and providers

**Comment by jlhogan** [comment]
1) current #of orgs, sites, accounts 
2) # with data started, # with data outstanding
3) details for each org/site, inclding all contact info with names
4) **NOT YET IN SCOPE** create/edit/delete this data

**Comment by JordanGuinn** [comment]
Updated the details of this ticket some, just to make it a little clearer that this is actually three distinct views, not one.
