### ISSUE TITLE
As a provider who has verified my data are correct, I can submit my data to OEC.

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#25]
When I have verified that my uploaded data are correct, I can click "Send to OEC" to submit my data to OEC.

Upon successful submission, I see the [screen for successful submission](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=799d0ece-6864-465d-bbb3-eddce905deb4&present=true&preview=false&sha=c48a65163e8532e6de4b7594d18763f321e83306) that contains the contact email for the pilot, a .csv download of their enrollment data, and a link to upload another spreadsheet.

**Comment by RyanHansz** [comment]
@julyytran for providers who need to update data before we launch editable tables, I added a re-upload button to replace the current file.

**Comment by jlhogan** [comment]
@JordanGuinn are you planning to do the ingestion to real model in the scope of this ticket? Or only the UI/UX  flow bits

**Comment by JordanGuinn** [comment]
I was thinking it was just gonna be the UX itself, but I have no preference either way.  I'm happy to tackle that here as well if that makes the most sense

**Comment by jlhogan** [comment]
no no that sounds good. im trying to get better at small tickets ! just wanted to confirm
