### ISSUE TITLE
Ability to delete income det, enroll, funding

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#250]

**Comment by bamader** [comment]
@RyanHansz Is there any desired functionality associated with this? Or I guess rather a specific place/way you want this implemented? I just put up a PR for deleting erroneous records, and that adds an apiDelete call that lets us delete enrollments, fundings, etc. Just wondering how I can leverage that for this ticket.

**Comment by jlhogan** [comment]
an individual funding,  enrollment (including fundings),  or income determination can be deleted. See https://app.abstract.com/share/d5d88c1b-6934-4718-b6d8-7c86a4d172c3?collectionId=5b228507-a588-4ce3-ab5d-be7242edd7fa&collectionLayerId=e912a5f7-4d17-454b-9ec4-d824667447d9&present=true&preview=false&sha=1a229de47b105d249096509861dfc63260262b58
