### ISSUE TITLE
Separate first/middle/suffix/last name in the data model.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#258]

**Comment by JordanGuinn** [comment]
@RyanHansz Is this to say that we want to break up the singular `Name` field in the `Data Requirements` template into: 
- `First Name`
- `Middle Name` (presumably optional)
- `Last Name`
- `Suffix` (presumably optional)

And if so, is there specific copy we want to use for the definitions of each of those individual fields?

**Comment by JordanGuinn** [comment]
@jlhogan @RyanHansz ^^ Ping 🙂

**Comment by jlhogan** [comment]
@JordanGuinn yes RE splitting up name into 4 separate fields on flattenedEnrollment (& thus in template); can't offer specific copy tho

**Comment by RyanHansz** [comment]
We can just use: "Legal name as appears on the child’s birth certificate." for each field

**Comment by JordanGuinn** [comment]
Sounds good - thanks y'all!
