### ISSUE TITLE
As a provider who has uploaded data and sees a mistake in the data, I can edit the data in place.

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#26]
When I see the view of what I have uploaded and I see an error, I can edit the data in the table instead of having to re-upload a file.

**[Mockup](https://app.abstract.com/share/bf8fb067-6052-441a-a981-63cee6ecb444)**

**Comment by RyanHansz** [comment]
Started a design/product issue to figure out validations:
https://github.com/ctoec/data-collection/issues/52
Maybe a first start is just simple data type validations (like having text in a number field)

**Comment by RyanHansz** [comment]
@julyytran here's the mockup for editing with no validations:
https://app.abstract.com/share/bf8fb067-6052-441a-a981-63cee6ecb444

**Comment by RyanHansz** [comment]
It has an excel/google sheets style selector to emphasize the fact that data is editable
