### ISSUE TITLE
Opening one form on income determination or enrollment/funding page should close all other open forms

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#278]
Currently a user can open multiple forms at the same time:
<img width="554" alt="Screen Shot 2020-09-24 at 11 14 13 AM" src="https://user-images.githubusercontent.com/63253539/94164485-17047780-fe57-11ea-9450-ee5e4ec7a47d.png">

Ideally, opening another form should close all other open forms on the page to reduce clutter. In this example, only one of "redetermine family income" or "edit family income" should be open.

**Comment by kmagida110** [comment]
@RyanHansz is this ticket still relevant since most of the different sections to edit have been split out across tabs? Right now the only place where multiple menus could be open are Site and Funding under Enrollment and Funding.

**Comment by RyanHansz** [comment]
This is still relevant on both the income and enrollment sections. But I'd prioritize other tickets in the meantime.

**Comment by kmagida110** [comment]
I'm going to spend a little time more time on it since it seems like it is a good entry into a few concepts I'm not familiar with, if it takes more than a few hours I'll move on.

**Comment by RyanHansz** [comment]
Note: Let's stop work on this if it can't be resolved by EOD.
