### ISSUE TITLE
As a provider, I can download the spreadsheet template from the landing page

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/data-collection#28]
Adds the links to download template as Excel or CSV in this [mockup](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=fa73a30a-aec8-4aaf-874f-9d5a1cb09093&present=true&preview=false&sha=2aca6b6a909d92d30fe01737244996211d85c82d).

[Spreadsheet template](https://docs.google.com/spreadsheets/d/1Td7MRxWLWs6osdvC1nfzmtuhztPCB-MkTCNUfgocV7o/edit#gid=0)

**Comment by julyytran** [comment]
Added a link to the template
