### ISSUE TITLE
Clean up tab-nav component

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#287]
<img width="983" alt="Screen Shot 2020-09-10 at 9 46 57 AM" src="https://user-images.githubusercontent.com/63253539/92739142-93bd2f00-f34a-11ea-9d9a-81ccf08d59ac.png">

Changes:
– Font-size reduce to 14px
- No hover state on active tab
- reduce padding on .oec-tab-nav--tab: 1em
- add margin: 0 .5em:
- Active tab-nav should have bold font-weight
- Hover on inactive tabs should have rounded corners 
- Inactive tabs should have color of #565C65 (Darker-gray)

**Comment by mmazanec22** [comment]
Gonna tackle this one with #341

**Comment by mmazanec22** [comment]
Addressed by https://github.com/ctoec/component-library/pull/68
