### ISSUE TITLE
Site navigation: I can view a roster for specific sites

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#288]
# [Designs](https://share.goabstract.com/bb8ecc5f-7855-452f-b52c-31410ef6fe70)
<img width="1032" alt="Screen Shot 2020-09-18 at 3 39 29 PM" src="https://user-images.githubusercontent.com/63253539/93638357-2605a880-f9c5-11ea-9ad7-a0599d5e92db.png">

At the top of my roster, I can select a site to view only that site's enrollments. All sites are displayed by default. If more sites exist than can be displayed in the nav, add a +# more label with an icon that will display all other sites in a dropdown when selected. 

If site names are longer than 20 characters, truncate with a ...
(example: Reallyverylong child...)

If I select an org or site from the dropdown, move that label to the first position after all sites/all orgs.  

Display the total number of funded spaces and utilization for overall funding types based on the users selected view. 
- If viewing a site, only show utilization (no capacity)

Hide this control if I only have access to one organization and one site

component library:
- add option to show additional tabs in dropdown

**Comment by mmazanec22** [comment]
Closed by #558
