### ISSUE TITLE
Withdrawn enrollments: I can navigate from my roster to a view of all withdrawn enrollments.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#291]
# [Design in Abstract](https://share.goabstract.com/1545741f-51be-4382-a6aa-76bd918553eb)

– I can click on past enrollments on my roster view to see withdrawn enrollments.
<img width="981" alt="Screen Shot 2020-10-19 at 9 36 33 AM" src="https://user-images.githubusercontent.com/63253539/96458136-95ea9700-11ee-11eb-9eca-1ce187908e4b.png">

– I see withdrawn enrollments in a roster view sorted by the most recent withdrawal date and grouped by age group.
<img width="689" alt="Screen Shot 2020-10-19 at 9 43 44 AM" src="https://user-images.githubusercontent.com/63253539/96459012-96cff880-11ef-11eb-8dfc-4af84ba9a1e6.png">

- I can return to my current roster by clicking the link under the withdrawn enrollments icon label

– When I withdraw an individual child record it is shown in the withdrawn roster. 

– Do not show withdrawn records in the active roster.

**Comment by RyanHansz** [comment]
Same question as viewing past month, how much filtering to do in front vs back end

**Comment by RyanHansz** [comment]
Blocked by figuring out caching in the month to month view ticket

**Comment by RyanHansz** [comment]
Need to add icon download to abstract

**Comment by jlhogan** [comment]
this should address https://github.com/ctoec/data-collection/issues/715

**Comment by RyanHansz** [comment]
@mmazanec22 the icon download is on this page:
https://app.abstract.com/projects/0b680217-1135-4908-a9e9-2ffb268d1191/branches/bcb5076f-b765-4b09-8ac9-c9c9b4df0e90/commits/latest/files/684c82ac-0f66-4268-9d27-763f98935625/layers/9B4EB274-4908-41E3-B3D7-5BD1EE7897CA?collectionId=c14dacf5-3311-4251-a8e6-d0764af84b96&collectionLayerId=1898f013-f8f9-431c-b807-da64e560efc7&mode=build

**Comment by RyanHansz** [comment]
@mmazanec22 the icon download is on this page:
https://app.abstract.com/projects/0b680217-1135-4908-a9e9-2ffb268d1191/branches/bcb5076f-b765-4b09-8ac9-c9c9b4df0e90/commits/latest/files/684c82ac-0f66-4268-9d27-763f98935625/layers/9B4EB274-4908-41E3-B3D7-5BD1EE7897CA?collectionId=c14dacf5-3311-4251-a8e6-d0764af84b96&collectionLayerId=1898f013-f8f9-431c-b807-da64e560efc7&mode=build

Just have to scroll to the bottom right to see it
