### ISSUE TITLE
Add an h2 header to each child record section.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#294]
<img width="908" alt="Screen Shot 2020-09-08 at 10 47 09 AM" src="https://user-images.githubusercontent.com/63253539/92491788-a73c8e80-f1c0-11ea-8392-7f866f3710a1.png">
<img width="838" alt="Screen Shot 2020-09-08 at 10 46 32 AM" src="https://user-images.githubusercontent.com/63253539/92491731-912ece00-f1c0-11ea-8618-e6b12e5b2ae4.png">
<img width="936" alt="Screen Shot 2020-09-08 at 10 47 29 AM" src="https://user-images.githubusercontent.com/63253539/92491839-b3285080-f1c0-11ea-94aa-2be0b7e9db11.png">
<img width="909" alt="Screen Shot 2020-09-08 at 10 47 44 AM" src="https://user-images.githubusercontent.com/63253539/92491871-bc192200-f1c0-11ea-8d19-62782c25c274.png">
<img width="956" alt="Screen Shot 2020-09-08 at 10 48 00 AM" src="https://user-images.githubusercontent.com/63253539/92491930-cb986b00-f1c0-11ea-8f99-65f9b9c382c0.png">
<img width="607" alt="Screen Shot 2020-09-08 at 10 49 27 AM" src="https://user-images.githubusercontent.com/63253539/92492102-fa164600-f1c0-11ea-9663-33d75d8d3efa.png">

**Comment by mmazanec22** [comment]
@RyanHansz should this be h2 since h1 is the start of the main section?

**Comment by RyanHansz** [comment]
@mmazanec22 yep, as long as its 22px

**Comment by mmazanec22** [comment]
Closed by #310
