### ISSUE TITLE
Compare Hartford Data export to our template

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#31]
Comparison with Julie's export, the Fawkes template and Hartford's export is [here.](https://docs.google.com/spreadsheets/d/1ClpSvOiI8zSi2oeGGhJUWvGAfMSBc3K6b3TTrEUhLOY/edit#gid=0)

**Comment by RyanHansz** [comment]
@julyytran did we ever ask TVCCA for their export?

**Comment by julyytran** [comment]
I thought we haven't spoken to a PowerSchool user yet and are still looking to connect with one?

**Comment by RyanHansz** [comment]
Whoops, meant childplus!

**Comment by julyytran** [comment]
@victoriasuwardiman Did you ask TVCCA for an export too and we are waiting on them?

**Comment by victoriasuwardiman** [comment]
Yes and yes. I just sent a follow-up email to nudge.
