### ISSUE TITLE
Only allow enrollments for organizations users have access to. 

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/data-collection#317]
For users with multi-org access, add a dropdown to the add enrollment button that makes the user choose organization before starting enrollment. 

Add a down-carat to the add enrollment button
<img width="529" alt="Screen Shot 2020-09-18 at 4 07 27 PM" src="https://user-images.githubusercontent.com/63253539/93640730-0e302380-f9c9-11ea-9f5f-203efd8f2a52.png">

**Comment by mmazanec22** [comment]
@RyanHansz for this ticket we need to know how we should determine what org (out of the orgs for which a user has access) a child gets added to.  Should there be a dropdown next to the add child link?  Should the add child flow include a dropdown?

**Comment by RyanHansz** [comment]
It should be a dropdown before site in the enrollment and funding section:
https://share.goabstract.com/f47e1c10-8048-456c-963d-a34d6bd05ed4?collectionLayerId=1e109da3-50a9-43fa-a02c-bf86092cd02f&mode=design

**Comment by RyanHansz** [comment]
And it'll need to be added to the enrollment and funding section as well:
https://share.goabstract.com/f47e1c10-8048-456c-963d-a34d6bd05ed4?collectionLayerId=b806efb2-80ef-48be-9a87-049d20565687&mode=design

**Comment by mmazanec22** [comment]
@RyanHansz this puts us in the position of making organization not required for the creation of a child (which we have to do to save the data in other steps).  That might lead to confusion/proliferation of bad data, since org ID is how we determine whether a user has access to see that child record.  Is there a way we can add this to the beginning of the flow?

**Comment by mmazanec22** [comment]
Organization is required to create the child in the database, which we do on step 1 in the child identifiers section, so saving org selection for the last step puts us in the awkward position of either a) arbitrarily assuming an organization based on user permissions b) not saving any data entered until the very last step or c) not requiring organization to create a child

**Comment by RyanHansz** [comment]
Thanks for clarifying how this works!

**Comment by RyanHansz** [comment]
We can replicate the dropdown from ECE reporter if that makes the organization step required before starting a new enrollment

**Comment by RyanHansz** [comment]
<img width="259" alt="Screen Shot 2020-09-18 at 11 06 02 AM" src="https://user-images.githubusercontent.com/63253539/93613501-f2178c80-f99e-11ea-95d0-15af1a9febae.png">
