### ISSUE TITLE
When editing a child record, the confirmation alert should go away when I navigate to another section of the record.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#323]
For example, when I change care 4 kids status, I see a confirmation alert. When I navigate to child info, the alert disappears so I can see a new alert when I make other changes.

**Comment by mmazanec22** [comment]
Note to whoever grabs this ticket: this is happening because we're using history replace rather than history push, and the alerts use location state.  Resetting the location state somehow when we history replace should take care of this.
