### ISSUE TITLE
Redirect non-authenticated users to the homepage

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#335]
In hedwig, we redirect user to the homepage where they can login. Do we want to replicate this for Fawkes?

**Comment by mmazanec22** [comment]
We could do that + set an alert

**Comment by RyanHansz** [comment]
I don't think there's need for an alert, just redirect to the homepage.

**Comment by jlhogan** [comment]
redirect to homepage, or directly to login screen?

**Comment by RyanHansz** [comment]
Homepage so they can tell what they're logging into
