### ISSUE TITLE
Enable differentiation of validation error display btwn Create & Edit flows 

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#338]
blocked by: #365 

thoughts: create a context that uses location to determine if validations are errors (create flow -- they look red) or warnings (edit flow -- they look yellow)

For info required to enroll:
<img width="405" alt="Screen Shot 2020-09-18 at 7 59 53 AM" src="https://user-images.githubusercontent.com/63253539/93595029-f171fc80-f984-11ea-8072-f040fafc7a40.png">

**Comment by RyanHansz** [comment]
Blocking:
- Name
- Date of birth
- Gender
- Site
- Organization
- Age Group
- Enrollment date
- Funding type
- Contract space
- First funding period
- Household size (unless foster)
- Annual household income (unless foster)
- Determination date (unless foster)
- Race
- Ethnicity
- Street Address (unless experiencing homelessness)
- Town
- State
- ZIP Code

**Comment by mmazanec22** [comment]
@RyanHansz which non blocking fields need warning messages, and which ones are truly optional?  (Off the top of my head-- assuming that middle name and suffix are truly optional.)

Also-- do all "blocking" errors prevent form submission, or only some of them?  If some of them do and some of them don't, should we distinguish those in any way?  (Thinking about accessibility-- we probably should only use the HTML attribute required on the ones that do block submission, and consider whether moving focus to the first element is for submission-blocking fields or all fields with errors.)

**Comment by jlhogan** [comment]
We need to regroup on "blocking" validations. Would it be acceptable to scrap them, and only have validations of the non-blocking variety?

**Comment by RyanHansz** [comment]
I'd like to confirm this with Julie, but I believe there's a bare minimum amount of data that we need for a record to be worth collecting (like a record with no names). Since we're starting with a point in time count, it doesn't make sense to me to let people create incomplete enrollments.

**Comment by jlhogan** [comment]
one way we can get to "blocking" validations with the class-validator package is to create a [validation "class"](https://github.com/typestack/class-validator#custom-validation-classes) for blocking validations, and run this validation on PUT/POST body before writing to db, and opting to fail the req + not write to DB if blocking validation is encountered. this means we don't have to check those validations when users do bulk upload, but can easily enforce them for individual record reation via API.

**Comment by jlhogan** [comment]
>OEC isn't allowed to collect data on private pay children

wait, what? I thought that was a hope for this system is that it _could_ support non-funded enrollments (even tho it is unlikely that providers would enter that data b/c there's 0 incentive) which would give OEC an even better understanding of the data

**Comment by RyanHansz** [comment]
As I understand families need to provide separate consent for their child's data to be tracked in this system if they aren't state funded.

**Comment by jlhogan** [comment]
the more you know

**Comment by RyanHansz** [comment]
Let's discuss this again monday, but based on my current thinking, there won't be any yellow warning validations. If a user uploads a spreadsheet with missing info, that would show up as an error in that child's record since they have to fix it to submit the data to OEC.

<img width="808" alt="Screen Shot 2020-09-25 at 4 07 49 PM" src="https://user-images.githubusercontent.com/63253539/94311424-44315280-ff49-11ea-9fea-32b25d71c484.png">

![Uploading Screen Shot 2020-09-25 at 4.12.07 PM.png…]()

**Comment by mmazanec22** [comment]
@RyanHansz a related question: if a user wants to update one field on a form in the edit flow that's missing multiple fields of info, do we block them from submitting changes until they enter all of the info?

**Comment by RyanHansz** [comment]
We can save the updated info while keeping the missing info validation. Have the double alert situation, which is OK.
<img width="996" alt="Screen Shot 2020-09-28 at 9 49 22 AM" src="https://user-images.githubusercontent.com/63253539/94440652-e5015700-016f-11eb-99bf-8e2aa5699b8d.png">
