### ISSUE TITLE
Rolling updates interaction model

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#35]
For providers that are using the data collection tool to update child information, what interactions need to be supported?

How can we reduce the time needed to make the most common updates to a child's enrollment record?

How (if at all) do we differentiate between edits and new events? Example: Updating an incorrect piece of data vs. showing it changed

- New enrollment
- New funding
- Edit enrollment
- Edit funding
- Aged up
- Changed sites
- Exited provider
- Ended funding
- Changed funding
- New income determination
- Income redetermination
- Edit income determination

https://airtable.com/invite/l?inviteId=invg3mKJysmZyktZY&inviteToken=8e17ccdddcdf3761caa8343a2d9514d3137bac68232e6cae99942947005b5ab6

**Comment by RyanHansz** [comment]
@julyytran do I remember saying some of the fields aren't editable? I believe it was in reference to data matching or something /shrug. Anyway I'm assuming all fields are user-editable until told otherwise

**Comment by julyytran** [comment]
Yes, I think we were discussing not allowing edit on any unique ID that comes from another system of record they have exported from, but if they're not doing that, then we'd use birth cert as the ID, which I think should be editable in case there was a mistake made in initial entry. So right now let's go with all fields are user-editable.

**Comment by RyanHansz** [comment]
@julyytran Another point where product/engineering perspective is needed, do we need to include a status update field in the excel/csv template? Or can we tell all of the above changes based on the data users upload?

**Comment by RyanHansz** [comment]
Can we handle all the scenarios here:
https://app.mural.co/t/skylight2171/m/skylight2171/1594212671129/40986ef69aa51ab1f6d8bc65314248b50b9022f9?wid=0-1594232062081
