### ISSUE TITLE
Batch upload replaces roster: When I upload a spreadsheet, any data, if there is any, in my roster is replaced with the spreadsheet data.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#350]
Instead of a separate verify data table for the batch upload, replace the roster data with the spreadsheet data that has just been uploaded.

If the user is uploading a spreadsheet when data already exists in their roster, then show a confirmation modal telling them that all the data will be overwritten. 

![6 2 Batch Upload Messages Modal](https://user-images.githubusercontent.com/63253539/94480576-81dde780-01a4-11eb-8c62-0e0bc2929b0e.png)
![6 2 Batch Upload Messages Modal Copy](https://user-images.githubusercontent.com/63253539/94480575-81dde780-01a4-11eb-8da4-7fbcf1d54b6e.png)

**Comment by jlhogan** [comment]
need to make sure we have a good definition of what is going to be replaced -- just the data that was uploaded by this specific user? Or all the data that this user has access to ? This may be an implementation detail, but requires understanding of how the user accounts are expected to exist. so the actual question is: will the sets of data each account has access to be mutually exclusive for the initial point in time collection?

**Comment by RyanHansz** [comment]
All sites/orgs the user has permissions for. 

- So if I'm a subcontractor that only has access to one site of an org, I would only replace my data for that site (and I wouldn't see data for the rest of the Org).
- If I have access to multiple orgs, I would replace the data for all of them.

**Comment by RyanHansz** [comment]
@jlhogan this one needs a new size estimate
