### ISSUE TITLE
Roster Empty State: When I navigate to a roster with no records, I am prompted to start adding enrollments.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#352]
![5 1 Roster - Empty message](https://user-images.githubusercontent.com/63253539/93809677-91e14e80-fc1b-11ea-8961-047b3135ee89.png)

**Comment by jlhogan** [comment]
rider: update number of sites to pull from user's sites, not sites summed up from children as it is currently done

**Comment by kmagida110** [comment]
@RyanHansz @jlhogan Roster as it is currently configured doesn't show children that aren't assigned an Age Group. Child objects can be created without age groups if the child workflow isn't completed. Should I change the logic to show all children that are created regardless of whether an AgeGroup is created?

**Comment by kmagida110** [comment]
This is an issue for the ticket because the definition of no records is different depending on which record we count.

**Comment by jlhogan** [comment]
I would ignore that bug, and just implement this for the actual 0 records case. Will open another ticket now to deal with age-group-less children, and make sure they are displayed somewhere

**Comment by kmagida110** [comment]
OK, I'll make the assumption that all children will eventually show up so that if there are children with no age group associated the alert will still not show up on the assumption that the roster will eventually show those children.

**Comment by kmagida110** [comment]
@RyanHansz Should the Add a Roster button that is being added here be the same style that is shown or can it be the same as the add a record button that currently exists there? Adding a new button will be a little more work

**Comment by RyanHansz** [comment]
@kmagida110 feel free to use the existing design if it saves time.
