### ISSUE TITLE
Confirm all "required info" validations are implemented 

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#366]
- Organization
- Name
- Date of birth
- Gender
- Site
- Age Group
- Enrollment date
- Funding type
- Contract space
- First funding period
- Household size (unless foster)
- Annual household income (unless foster)
- Determination date (unless foster)
- Race
- Ethnicity
- Street Address (unless experiencing homelessness)
- Town
- State
-  ZIP Code

**Comment by JordanGuinn** [comment]
- [ ] Organization
- [ ] Name
- [ ] Date of birth
- [ ] Gender
- [ ] Site
- [ ] Age Group
- [ ] Enrollment date
- [ ] Funding type
- [ ] Contract space
- [ ] First funding period
- [ ] Household size (unless foster)
- [ ] Annual household income (unless foster)
- [ ] Determination date (unless foster)
- [ ] Race
- [ ] Ethnicity
- [ ] Street Address (unless experiencing homelessness)
- [ ] Town
- [ ] State
- [ ] ZIP Code

**Comment by JordanGuinn** [comment]
https://github.com/ctoec/data-collection/issues/605 found as a result of this work.

**Comment by JordanGuinn** [comment]
After banging my head against this for long enough, I don't think that we can actually implement the final validation for `Contract Space`, at least with how our data model and validation mechanisms are currently set up.  

Contract Space (aka `FundingTime`) exists on the `FundingSpace` model, which isn't something the user will be able to edit directly - all possible `FundingSpace` permutations will be manually created by us prior to any users accessing the application.  Instead, the user will pick a `FundingTime` and we'll figure out which `FundingSpace` to use based on that decision.  

Unfortunately, this introduces something of a catch-22 - we can't create a Funding without a FundingSpace, we can't pick a FundingSpace if the user doesn't select a FundingTime, and we can't run validations for FundingTime if we can't create a Funding. 😬

Open to any and all thoughts and suggestions, but am gonna be moving on for the time being.

**Comment by jlhogan** [comment]
The funding should not have fundingTime on it -- the funding only has the relationship to fundingSpace, which defines both the source and the time. We don't/can't validate "Contract space" separately, but rather just need to validate that the funding space is appropriate for the funding, which really just means the agegroup on the funding's enrollment == the agegroup on the funding's fundingspace! I think the wording in this ticket made it seem more confusing than it needs to be, sorry about that. We only need to validate what is validate-able!
