### ISSUE TITLE
Fuzzy town name matching: If I upload records with typos in town names, it is automatically matched to a valid CT town name.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#368]
https://portal.ct.gov/Government/Cities-and-Towns

**Comment by kmagida110** [comment]
There are ~5000 out of 65000 towns that do not match up directly to existing town names according to the census. There are a few buckets of potential issues.

- Many seem to be addresses that were loaded into the town form. These were all loaded in January so there is a chance there was a one off bulk load that was off. These likely wouldn't match anything with fuzzy matching.
- There are also a fair amount of town misspellings that seem to be close to real towns. This might be a potential validation pending a full list of towns.
- There is a final bucket of 5-15 "towns" which are valid for address but aren't actual towns by governance. These could be added to a master list, OEC adjusts for these towns but might not have a comprehensive list.
