### ISSUE TITLE
Special circumstances section: Group Disability, Dual Language and Foster youth into a section.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#382]
- All fields are required.
- rename receivingSpecialEducationServices to Special Education Services. Remove mention of IEP and IFSP in description.
- [maybe delete specialEducationServicesType]
- Add dual language learner to child model.
- Add "unknown/not disclosed" option for each. 
- Update form to look like:
<img width="389" alt="Screen Shot 2020-09-28 at 4 26 37 PM" src="https://user-images.githubusercontent.com/63253539/94482559-7a6c0d80-01a7-11eb-87f7-ca2312e3aa4d.png">

**Comment by jlhogan** [comment]
waiting on new name for "recieving special education services"

**Comment by RyanHansz** [comment]
No new name, just remove the IEP or IFSP label. Separately we need to follow up to give providers help content on who qualifies here.

**Comment by bamader** [comment]
Is the 'Disability Services' section shown in the image supposed to be special education services? Or should there be four sections to this form and we're also adding a `receivesDisabilityServices` field?

**Comment by RyanHansz** [comment]
Let's wait till the end of today after our OEC meeting so I don't say something and immediately change it!

**Comment by bamader** [comment]
@RyanHansz Any update on what these fields mean? Thinking about grabbing this ticket today since I'm already in the guts of the form updates and the booleans are done.

**Comment by RyanHansz** [comment]
Yes! 


Dual language learner | Required | Children who have a home language other than English and are learning two or more languages at the same time, or learning a second language while continuing to develop their first language are dual language learners. | Used for demographic reporting. | Yes, Y, No, N, UnknownEx: Yes



Receiving disability services | Required | Children receiving services for Autism, emotional disturbance, intellectual disability, learning disability, speech-language impairment, and other disabilities. Sometimes involves an IEP or IFSP. | Used for demographic reporting. | Yes, Y, No, N, UnknownEx: Yes
