### ISSUE TITLE
What are the data requirements?

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#39]
[Report fields inventory](https://docs.google.com/spreadsheets/d/1dml41C-yGSGjG3y1bNwd-3hSDtT5mUfaOzj8ubhuApY/edit#gid=0)

Should English language learner be part of the data collection template?

**Comment by RyanHansz** [comment]
Are there scenarios in which a child can have multiple fundings at the same time. If so, when?

**Comment by julyytran** [comment]
Info from Julie about multiple fundings at the same time:

> Yes, kids may be in more than one funding at the same time. Two part day or a 6 hour and a warp around. ECIS has validations to restrict two 6 hour school day to full days from overlapping dates and sends an email to the other provider if a new provider is trying to enroll a child though allowed with a red font appearing for the issue and a validation note for both providers. A single provider is not able to enter 1 child in two full spaces in the same dates or overlap of a day or more.

Sounds like we may not need to support this in data collection but will in data matching
