### ISSUE TITLE
As a provider who already has data in the system, I can view and update the data I already have.

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#40]
From the Getting Started page, I can click "View enrollment data" to [see my current data.](https://app.abstract.com/share/020bd5bc-ce26-444a-92cc-9ea14d1835cf?collectionId=11f49202-5a34-497f-9b32-1bea28938c0e&collectionLayerId=d8d138f8-4f44-4ef7-ba48-369b70f0dd71&present=true&preview=false&sha=62fc665367d9f884e4e87e95f3da931acfba1d21)

I can edit this data in place and then "Review and submit."

I can update this data via batch upload.

Requires logic in #35 

Validations?

**Comment by RyanHansz** [comment]
Here's my understanding of the interactions that need to be supported
https://airtable.com/invite/l?inviteId=invg3mKJysmZyktZY&inviteToken=8e17ccdddcdf3761caa8343a2d9514d3137bac68232e6cae99942947005b5ab6

**Comment by RyanHansz** [comment]
If we don't want any validation, then this is essentially an editable table. If we do want validation, it will mean grouping interactions that necessarily come together (like how aging up means you have to change funding)

**Comment by RyanHansz** [comment]
@julyytran updated design for editing in place here:
https://share.goabstract.com/bf8fb067-6052-441a-a981-63cee6ecb444

**Comment by RyanHansz** [comment]
Also added a new sort ui: 
https://designsystem.digital.gov/components/form-controls/#combo-box
So that we can remove the arrows on the inactive columns, I think the gray down arrow is confusing since they're not actually sorting.
