### ISSUE TITLE
Comms: Current pilot for v1, how should we handle these participants? Will we still submit PSRs on the backend?

### ISSUE THREAD

**Issue by lucasolivia** [ctoec/data-collection#410]
Asked in Slack channel 9/28 
https://skylight-hq.slack.com/archives/CKABWA9U6/p1601326103059500

**Comment by RyanHansz** [comment]
- giving them an export of their most recent enrollment data,
- letting them know spreadsheet reporting is coming back, and phasing out ECE Reporter V1.
- And letting them know there will be another tool for data collection in January.
