### ISSUE TITLE
As a provider, I can see data definitions for data in the upload template.

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#43]
[From the landing page
](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=fa73a30a-aec8-4aaf-874f-9d5a1cb09093&present=true&preview=false&sha=2aca6b6a909d92d30fe01737244996211d85c82d)There is a third "learn more" link to see the data requirements. This link takes me to a public page of the [data definitions.](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=6d13caae-038e-493e-a665-d7f176b34c11&present=true&preview=false&sha=c684d1dab5d1630bd05cf795774e03ee4310a6d6)

From the Getting Started Page
When I am on the Getting Started page, I can click "enrollment data requirements" to get to the [Enrollment Data Requirements page](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=6d13caae-038e-493e-a665-d7f176b34c11&present=true&preview=false&sha=c684d1dab5d1630bd05cf795774e03ee4310a6d6), which shows a table of data fields and information about each field.

I can sort this table by field name.

I can click "Back" to get back to the Getting Started page.

**Comment by julyytran** [comment]
@jlhogan Could you help with the "accepted format" column of the [data definitions? ](https://docs.google.com/spreadsheets/d/1yAZ0PtPdeFYzoTwxp4-XLxQwW2hOWFtZjz8cHjzlogk/edit#gid=1839916440&range=F2)

**Comment by RyanHansz** [comment]
@julyytran mockup of data definitions page:
https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionLayerId=6d13caae-038e-493e-a665-d7f176b34c11&mode=design

**Comment by jlhogan** [comment]
@julyytran  @RyanHansz for date formats, is it easier to pick one and stick with that? Should we determine the default date export format from source systems? Anything like `MM/DD/YYYY` `MM-DD-YYYY` `YYYY-MM-DD` are fine but wondering if it's simpler for the user to pick just one allowed format?

**Comment by jlhogan** [comment]
Also, do we want to have standard shorthands/abbrevs for race options? Seems it would be annoying to have to type americanIndianOrAlaskaNative, or NativeHawaiianOrPacificIslander. Easier might be to pull these out into separate boolean fields, as we do ECE reporter, but this may not jive with the exports from ChildPlus/PowerSchool

**Comment by RyanHansz** [comment]
My goal is to avoid users having to reformat data from their system. If we can accept any of the three that'd be best, since each provider could use a different format. 

Then we'd translate to whatever we use for Fawkes, such as MM/DD/YYYY. Thoughts @julyytran ?

**Comment by RyanHansz** [comment]
For a bunch of reading on this topic, see https://www.interaction-design.org/literature/article/how-to-implement-a-forgiving-format-to-accommodate-users-mistakes

**Comment by RyanHansz** [comment]
For race: Hartford's export is:

W - Student Race (Y/N) | Y
B - Student Race (Y/N) | N
H - Student Race (Y/N) | Y
A - Student Race (Y/N) | N
O - Student Race (Y/N) | N

**Comment by RyanHansz** [comment]
So I think separate fields could work for most

**Comment by RyanHansz** [comment]
For reference, I'm putting the exports we get here to do comparisons:
https://docs.google.com/spreadsheets/d/1ClpSvOiI8zSi2oeGGhJUWvGAfMSBc3K6b3TTrEUhLOY/edit#gid=1796177932

**Comment by julyytran** [comment]
Agreed it'd be good to accept any valid date formats and break out race especially since it is more similar to the ChildPlus export. We just got an intro to a PowerSchool user so hopefully we can get that export to validate too

**Comment by RyanHansz** [comment]
Hartford is the self-made system, believe we're still waiting for the child plus export

**Comment by jlhogan** [comment]
next Q: re address -- can we split out street address / town / state/ zip  into separate fields?

**Comment by julyytran** [comment]
Yes I think that's fine.

And thanks for the clarification, Ryan!

**Comment by RyanHansz** [comment]
Agree, updated the template

**Comment by jlhogan** [comment]
More qs: what is `Provider` in enrollment section? a person's name?

**Comment by RyanHansz** [comment]
There will likely be users who are entering data for more than one provider. As an example, someone at the city of Hartford receives data from a dozen or so providers.

**Comment by jlhogan** [comment]
Ok, accepted format and sample data for everything except "`Special Education Services Type` -- not sure what the values should be here, if they go beyond: `LEA provided services`, `Non-LEA provided services`

also, probably someone wants to take a pass at making the "accepted formats" a bit nicer -- they're true, but perhaps not the most elegant sentence fragments

**Comment by RyanHansz** [comment]
@julyytran Writing this as a reminder to follow up with Rachel on the Special Education service type. It caused some confusion in research and if OEC doesn't have a clear use for it, I'd recommend removing it.
