### ISSUE TITLE
Add excel or .csv to template download link

### ISSUE THREAD

**Issue by julyytran** [ctoec/data-collection#44]
How to present excel as the standard template and also allow for csv as a backup

**Comment by RyanHansz** [comment]
@julyytran https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionId=e2036f17-be42-40a0-9a0b-aa94c3efbc51&collectionLayerId=f128d451-cb06-4a7a-bd3a-0e775883af75&present=true&preview=false&sha=7d4f2aca197c396295a860dc4720adff3b0d438f

**Comment by julyytran** [comment]
Thanks! Do you think the link to download on the home page should have the 2 options there too, or only Excel there?

**Comment by RyanHansz** [comment]
Updated homepage to have both templates and a link to the definitions page:
https://share.goabstract.com/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionLayerId=fa73a30a-aec8-4aaf-874f-9d5a1cb09093&mode=design
