### ISSUE TITLE
Form element spacing

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#455]
<img width="410" alt="Screen Shot 2020-10-01 at 9 55 53 AM" src="https://user-images.githubusercontent.com/63253539/94818669-5e958100-03cc-11eb-9513-79e8d729acaf.png">

**Comment by mmazanec22** [comment]
Agree that this looks goofy as is-- what's the desired spacing between form elements and sections?

**Comment by RyanHansz** [comment]
<img width="573" alt="Screen Shot 2020-10-01 at 2 16 22 PM" src="https://user-images.githubusercontent.com/63253539/94847542-b6de7a00-03f0-11eb-894d-0e088d8bf4da.png">
<img width="522" alt="Screen Shot 2020-10-01 at 2 15 48 PM" src="https://user-images.githubusercontent.com/63253539/94847547-b940d400-03f0-11eb-9938-5d05854d9a58.png">
