### ISSUE TITLE
Roster action links spacing

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#456]
<img width="341" alt="Screen Shot 2020-10-01 at 9 57 16 AM" src="https://user-images.githubusercontent.com/63253539/94818791-7ff66d00-03cc-11eb-9516-fc6bfacae0e9.png">

**Comment by RyanHansz** [comment]
To oec-text-with-icon add:
- margin-right: 1rem;

Reduce margin on: 
.oec-text-with-icon__icon--side-left to
    margin-right: .25rem;

Remove bolding on Download csv file

**Comment by mmazanec22** [comment]
I can cover these in #317 since I was messing around with that part of the code anyway!

**Comment by mmazanec22** [comment]
Addressed by https://github.com/ctoec/component-library/pull/74 and #459
