### ISSUE TITLE
Add a warning label when opening a child record with needed info.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#466]
When I navigate to a child record that has missing/needed info, I see this warning message that tells me the record is missing info. The alert goes away when no section is missing required info. 
<img width="1024" alt="Screen Shot 2020-10-09 at 11 06 29 AM" src="https://user-images.githubusercontent.com/63253539/95599789-8b2a4800-0a1f-11eb-87bd-c8497c135d4d.png">

Remove this alert
<img width="1007" alt="Screen Shot 2020-10-09 at 11 08 18 AM" src="https://user-images.githubusercontent.com/63253539/95599940-be6cd700-0a1f-11eb-81d4-4ba606226a50.png">

**Comment by jlhogan** [comment]
Should we also default to the first section with missing info?

**Comment by RyanHansz** [comment]
Yes that makes sense!
