### ISSUE TITLE
No Age Group Section: I see all children without age groups in a section

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#481]
Currently:
Children with no age group are not displayed in the roster.

Ideal:
Children without agegroup are displayed in "no age group" section
<img width="1074" alt="Screen Shot 2020-10-06 at 2 40 31 PM" src="https://user-images.githubusercontent.com/63253539/95246012-e53dca00-07e1-11eb-8397-eee09f7decea.png">

**Comment by RyanHansz** [comment]
<img width="547" alt="Screen Shot 2020-10-02 at 1 58 32 PM" src="https://user-images.githubusercontent.com/63253539/94954624-5e25e480-04b7-11eb-81c2-3ed2c6bb9969.png">
