### ISSUE TITLE
Remove apostrophe from the error message, after uploading the file when telling the user to make edits.

### ISSUE THREAD

**Issue by lucasolivia** [ctoec/data-collection#490]
<img width="1683" alt="Screen Shot 2020-10-02 at 4 37 42 PM" src="https://user-images.githubusercontent.com/67710422/94967822-d4cddc80-04cd-11eb-9d06-a6a0eaa7ac54.png">

It is right before "You'll" 

Revisit this message when batch edit is implemented

**Comment by mmazanec22** [comment]
This isn't actually blocked right?  Also it got fixed in a recent PR, so closing for now (can reopen if there was more to it than just the apostrophe)
