### ISSUE TITLE
Priority testing: Choose most important

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#497]
- log in
- navigate to roster
- upload a file
- view a record
- save a change to a record
- create a new record
- delete a record
- upload a file with no missing info and submit data to OEC

Backfill other tests

**Comment by RyanHansz** [comment]
From the QA List:

- 
- - Home page
- OEC website link
- Privacy policy (coming soon)
- View data requirements
- Download excel template
- Download .csv template
- Log in
- Download Excel template
- Download .csv template
- View data definitions
- Upload data
- Upload excel template
- From home page
- From header
- From intro page
- Upload .csv template
- From home page
- From header
- From intro page
- Upload an empty file
- Upload a non .csv or excel file
- Upload a different excel file
- Upload a file with the headers changed
- Upload a file with an empty row
- Upload a file with 200+ records
- Upload a file with multiple sites
- Upload a file with multiple organizations
- Upload a file with incorrect data formats
- Upload a file with multiple organizations
- Upload a file with duplicate rows
- Upload a file after leaving page open for 20 minutes
- Roster
- Hide/expand age groups
- Alert shows correct # of records with missing information
- Load a roster with 1000s of records
- Load a roster with no records
- Export roster
- Add a record
- Child actions
- View each section
- Check that missing fields are correctly flagged
- Add new info to each section
- Add a new income determination
- Delete an income determination
- Edit an income determination
- Add a new enrollment
- Change an enrollment
- Change funding
- Edit enrollment
- Edit funding
- Delete record
- Withdraw record
- Submit data
- Download .csv
- Go to file reupload
- Go back to roster
- Logout
-

**Comment by mmazanec22** [comment]
e2e tests:

- log in
- navigate to roster
- upload a file
- view a record
- save a change to a record
- create a new record
- delete a record
- upload a file with no missing info and submit data to OEC

TBD: can we upload a file with browserstack?

**Comment by RyanHansz** [comment]
Need to scope this for one sprint
