### ISSUE TITLE
Fix header when scrolling through roster sections

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#504]
<img width="802" alt="Screen Shot 2020-10-06 at 9 42 07 AM" src="https://user-images.githubusercontent.com/63253539/95209306-3933b900-07b8-11eb-9de9-bb1b8edd76bf.png">

When I'm scrolling through long roster sections, I want to see the column headers and which age group I'm in.

**Comment by mmazanec22** [comment]
https://adrianroselli.com/2020/01/fixed-table-headers.html

**Comment by jlhogan** [comment]
but also, we really don't need to be maintaining this custom table component....
