### ISSUE TITLE
encrypted DB

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#510]

**Comment by JordanGuinn** [comment]
Are we talking at rest or in transit here?  Or both?

**Comment by jlhogan** [comment]
well we are making this up as we go for now, so i'm happy to go with at rest will do

**Comment by JordanGuinn** [comment]
Sweet - if that's the case, then I have a devops PR for this that's ready now 😎

**Comment by jlhogan** [comment]
closed https://github.com/skylight-hq/ctoec-devops/pull/97

**Comment by JordanGuinn** [comment]
FWIW, we're **also** encrypting all traffic to/from necessary RDS instances now as well: https://github.com/skylight-hq/ctoec-devops/pull/102
