### ISSUE TITLE
encrypted secret manager

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#511]

**Comment by JordanGuinn** [comment]
This is presumably a combination of the following:

1. Pick an encrypted secrets manager (we've done)
2. Migrate all of our secrets to it (we've started)

Is that right?

**Comment by jlhogan** [comment]
yes! and confirming that AWS secret manager encrypts by default (which like, yes, right?)

**Comment by JordanGuinn** [comment]
yep!

**Comment by JordanGuinn** [comment]
A couple devops tickets have already been completed that start moving us towards this reality, but we still have a good deal more to complete from my perspective:

- https://github.com/skylight-hq/ctoec-devops/issues/95
- https://github.com/skylight-hq/ctoec-devops/issues/90
- https://github.com/skylight-hq/ctoec-devops/issues/88
- https://github.com/skylight-hq/ctoec-devops/issues/94 (just cuz this inherently includes the removal of prod root db creds from source control)

**Comment by JordanGuinn** [comment]
We don't need to implement https://github.com/skylight-hq/ctoec-devops/issues/90 for MVP (password rotation can come later), and all the other linked tickets here have since been completed.  Marking this as complete.
