### ISSUE TITLE
80% avg code coverage

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#518]
:'(

**Comment by JordanGuinn** [comment]
Is this actionable?  Can I close this?  I think if we're diligent about adding automated testing to all new features moving forward we'll eventually get here, but I don't think it makes sense to try and accomplish this in one fell swoop.

**Comment by bamader** [comment]
I would agree with that. Because we've got a testing checklist in all of our PR templates this feels redundant.
