### ISSUE TITLE
Add updated privacy policy

### ISSUE THREAD

**Issue by lucasolivia** [ctoec/data-collection#523]
- Use the programmatically generated data definitions so we don't get out of sync. 
- Create Page

Hold off on updated Content:
https://docs.google.com/document/d/1THDb1gqtY-fjC1HgDPOi1Y7pG-D8NgpRutrAheuDN2E/edit#

**Comment by bamader** [comment]
@RyanHansz Is this still blocked or waiting on design input?

**Comment by RyanHansz** [comment]
@bamader You can definitely get started on this with the content here:
https://docs.google.com/document/d/1THDb1gqtY-fjC1HgDPOi1Y7pG-D8NgpRutrAheuDN2E/edit#heading=h.2qmqe0885k45
Just know it may get some updates as we get approval from OEC.

**Comment by bamader** [comment]
In the Schedule A section, do we actually want to repeat the data requirements content or can we just direct users to the other page?

**Comment by RyanHansz** [comment]
I know nothing about privacy policies, but the v1 had the data definitions on the same page, so I'd like to replicate that.
