### ISSUE TITLE
Edit site: I can add a site if I've uploaded a record without one

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#536]
![Missing site](https://user-images.githubusercontent.com/63253539/95486193-b4d06a00-0960-11eb-964f-6221c4fc8f2e.png)

# [Design](https://share.goabstract.com/a84f087a-59cc-4fee-b533-1e8b476f46db?collectionLayerId=fa62d58c-545c-4798-9ded-ede31d334697&mode=build)

**Comment by jlhogan** [comment]
have this in a current branch !

**Comment by RyanHansz** [comment]
@jlhogan so review in progress?

**Comment by jlhogan** [comment]
almost not quite, bt in progress yes

**Comment by RyanHansz** [comment]
Looks like batch upload rejects enrollments without age groups:
<img width="1207" alt="Screen Shot 2020-10-20 at 4 02 29 PM" src="https://user-images.githubusercontent.com/63253539/96638129-adf51000-12ed-11eb-89f3-af05419de4e3.png">
<img width="1106" alt="Screen Shot 2020-10-20 at 4 02 22 PM" src="https://user-images.githubusercontent.com/63253539/96638134-b0576a00-12ed-11eb-9440-c10d756cd188.png">
