### ISSUE TITLE
Care model doesn't show in enrollment card, so if it is missing, the user can't tell which record has errors

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#542]
<img width="1042" alt="Screen Shot 2020-10-08 at 3 37 36 PM" src="https://user-images.githubusercontent.com/63253539/95505398-43061980-097c-11eb-81e2-b02cd5d1261e.png">
<img width="999" alt="Screen Shot 2020-10-08 at 3 38 49 PM" src="https://user-images.githubusercontent.com/63253539/95505462-5e712480-097c-11eb-89c1-d8ee3676a6b6.png">

**Comment by bamader** [comment]
@RyanHansz Would you like the model type below site or in the same row as the other fields? To me it looks a little cleaner in the same row:
<img width="1087" alt="Screen Shot 2020-10-08 at 5 33 48 PM" src="https://user-images.githubusercontent.com/49412165/95515961-794b9500-098c-11eb-9e22-7eee510e0dd7.png">

**Comment by RyanHansz** [comment]
You're right, it does look better in one row! While we're editing this, can we make the margin-bottom: 0 on the labels (site etc) and the margin-top: 0 on the text? They're floating away from each other.

**Comment by bamader** [comment]
Yeah of course!
