### ISSUE TITLE
use backend validation error  messages

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#549]
- Validation messages displayed in the application should come from the messages in the api responses
- error status should be displayed for hidden forms (i.e. enrollment, funding, family income det) when they are collapsed
  - right now, we only show the `!` if the field is missing. need to update this check to show the `!` if the field has a validation error.

**Comment by RyanHansz** [comment]
One message on the backend when info is missing
Specify validations on backend – birth date is too early

**Comment by RyanHansz** [comment]
#484 - for one example
