### ISSUE TITLE
Create openAPI spec from Hedwig auto generated spec

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#56]
In dev, Hedwig app serves a generated openAPI yaml spec at `.../swagger/v1/swagger.json`

**AC**:
- use generate Hediwg spec as a starting point for an openAPI spec for data-collection app
- remove routes except /user/current
- add route for /reports PUT (shoudl this be called reports?)

**Comment by JordanGuinn** [comment]
The new `PUT reports` route we're talking about here is referring to our new spreadsheet upload mechanism, right?

**Comment by jlhogan** [comment]
yes, i just meant matching what currently exists in the API we've built
