### ISSUE TITLE
Add enrollment forms are flashing error validations when moving between sections.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#561]
When I move between sections while adding a child, the forms get an error validation applied to them. This makes me think I have incorrectly entered data.

- At least happening when finishing the child info section in staging

**Comment by mmazanec22** [comment]
See the note on line 59 of child identifiers form

**Comment by RyanHansz** [comment]
Reopening as this is still happening in the other sections (at least child info and address) in dev secure
