### ISSUE TITLE
App can create curent template with faked data, can be downloaded via UI

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#572]
# [Design](https://share.goabstract.com/7bbb5453-e095-44ad-a9c4-5da50c195366)
## New Page: Templates
- Instead of a dropdown, the template link in the top-bar nav goes to a page with all data template and sample downloads which is accessible when signed in or out
<img width="887" alt="Screen Shot 2020-10-19 at 3 11 40 PM" src="https://user-images.githubusercontent.com/63253539/96500794-656e2180-121d-11eb-847f-04d5fde2feb7.png">

## Getting started page
- The getting started page allows users to download the sample data:
- Go to roster and go to batch upload are now a bottom button bar
<img width="695" alt="Screen Shot 2020-10-20 at 10 41 48 AM" src="https://user-images.githubusercontent.com/63253539/96602323-e5999300-12c0-11eb-8e4b-897557d03a80.png">

**Comment by RyanHansz** [comment]
In terms of data to include in the sample: 
- The example users can download on the site should not have any errors
- For QA, we should have a spreadsheet that includes at least one instance of each required field being missing
- The sample data should show every age group and funding type possiblity
- Eventually we will want to add historical data (a child moved from infant/toddler to preschool for example)

**Comment by RyanHansz** [comment]
@mmazanec22 added some designs and notes here. Let me know if you want to talk through any details

**Comment by RyanHansz** [comment]
@mmazanec22 you can download the SVG illustrations in the inspect page of abstract

**Comment by mmazanec22** [comment]
Closed by #600
