### ISSUE TITLE
When I log into ECE Reporter, data appears to be stale

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#610]
- On sign-in, my roster appears empty until I reload the page.
- Data is also stale after uploading a new file to replace the old one

- Dependent on Julia's work to update how we're handling the cache.

**Comment by jlhogan** [comment]
don't use julia's custom cache, use a real library https://github.com/tannerlinsley/react-query ?

**Comment by mmazanec22** [comment]
Data is also stale after uploading a new file to replace the old one
