### ISSUE TITLE
Age groups and enrollments are not being parsed on example batch upload spreadsheet.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#611]
When I upload melanie's example spreadsheet, most of the children's enrollments are not added: 
<img width="798" alt="Screen Shot 2020-10-21 at 3 53 50 PM" src="https://user-images.githubusercontent.com/63253539/96780102-96d02400-13ba-11eb-834f-2c332f9b9173.png">

<img width="1117" alt="Screen Shot 2020-10-21 at 4 29 51 PM" src="https://user-images.githubusercontent.com/63253539/96780436-bbc49700-13ba-11eb-86a2-a81b909e08cd.png">

**Comment by jlhogan** [comment]
when I try to repro with a single row that failed to parse, I am unable. Something is happening when uploading multiple rows.
