### ISSUE TITLE
Spacing on text links

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#652]
Missing line-height between two text links on data definitions page:
<img width="316" alt="Screen Shot 2020-11-02 at 9 45 08 AM" src="https://user-images.githubusercontent.com/63253539/97881258-2d241400-1cf0-11eb-8b20-85a789340b8a.png">

**Comment by mmazanec22** [comment]
Noticed this and already started fixing it in my PR for #616 !  (It was because I removed the default margin so that it would fit in the table and didn't catch all instances of this)

**Comment by mmazanec22** [comment]
Closed by #660
