### ISSUE TITLE
family income section is un-skippable in create  flow

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#654]

**Comment by mmazanec22** [comment]
I'm assuming this refers to foster kids and the lack of button-- is that it or is there another bug to worry about here @jlhogan ?

**Comment by jlhogan** [comment]
yes no that's what it refers to -- in ECE reporter v1 we just automatically skip over the unnecessary section. I tried to implement that fix, and it did not work (infinite renders.....) so button sounds like a good solution!
