### ISSUE TITLE
Fix undefined default for date input

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#656]
Birthdate value does not exist, and date input field null default stopped working.

<img width="401" alt="Screen Shot 2020-11-03 at 9 49 41 AM" src="https://user-images.githubusercontent.com/63253539/98000105-1cd86b80-1dba-11eb-8d57-487f37b736bb.png">

**Comment by jlhogan** [comment]
This is not actually what's happening -- we don't have a validation for too young birthdate, but can add. 
the issue here is that the birthdate value does not exist, but the date input field null default stopped working
