### ISSUE TITLE
Batch edit tweaks

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#679]
- missing info icon has hover tool tip: "Add missing info"
- add 1em padding to 
![](https://user-images.githubusercontent.com/63253539/97364903-28d4a280-187b-11eb-9d1d-6e3b2d06e1fc.png)
- remove padding-top from
![](https://user-images.githubusercontent.com/63253539/97364929-34c06480-187b-11eb-9958-e4f49f65e1c6.png)
- If date of birth, age group, or site are missing, text reflects missing state:
![](https://user-images.githubusercontent.com/63253539/97364985-47d33480-187b-11eb-812f-1d69944dd6d0.png)
- item content text does not say "Errors in", just lists form sections with missing info
![](https://user-images.githubusercontent.com/63253539/97365001-4efa4280-187b-11eb-903b-4910872ab56c.png)
- update completed record in list content from "All finished" to
![](https://user-images.githubusercontent.com/63253539/97365027-5b7e9b00-187b-11eb-8dc9-a6a6b9e1a665.png)
- update missing info alert in roster to (ignoring button for now, @RyanHansz what should be the clickable text in absence of button?): 
<img width="982" alt="Screen Shot 2020-11-11 at 5 02 51 PM" src="https://user-images.githubusercontent.com/63253539/98869418-be596000-243f-11eb-919f-f486dcbb30b3.png">

**Comment by RyanHansz** [comment]
@jlhogan to your last question:
<img width="982" alt="Screen Shot 2020-11-11 at 5 02 51 PM" src="https://user-images.githubusercontent.com/63253539/98869418-be596000-243f-11eb-919f-f486dcbb30b3.png">

**Comment by RyanHansz** [comment]
@bamader once the outstanding bugs are fixed, can we move to https://github.com/ctoec/data-collection/issues/593 before this one?

**Comment by bamader** [comment]
@RyanHansz Just want to clarify: I should use the alert text in the image in the AC, and then use the second sentence in the image you uploaded (about using batch editing)? Or should I just use the exact copy you've uploaded in that second image?

**Comment by bamader** [comment]
Also, since I don't think we yet have any tooltips in the app, is there a preference on how we want to approach them? Seems like there are packages out there that handle tooltip formatting pretty well.
