### ISSUE TITLE
Create help page and update header link

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#687]
# [Design Mockup here](https://share.goabstract.com/ae8b17fe-9265-4d8c-a468-70818d9728a7)

<img width="1100" alt="Screen Shot 2020-11-11 at 4 34 12 PM" src="https://user-images.githubusercontent.com/63253539/98866953-c1eae800-243b-11eb-8742-86a937782e4e.png">

- Update the Feedback link in the header to read "help" and link it to this page.

- Links to the support form and help content will come later. 
- URL: https://ece-reporter.ctoec.org/help

**Comment by bamader** [comment]
@RyanHansz Do you happen to remember if the two rectangles with the guides and support are a particular kind of component in the library? I thought about using a `Card` (which we have for enrollments/fundings/income determinations) but I really don't think it'll look right.

**Comment by jlhogan** [comment]
you should be able to use cards & set their width/height? if you use the USWDS border styles (look at card css maybe?) then just any sized divs with correct padding/margins should pretty much end up looking like that

**Comment by RyanHansz** [comment]
@bamader, when we pick this up again, reach out to @victoriasuwardiman for the support form to embed

**Comment by victoriasuwardiman** [comment]
Hi! Here is the link: https://forms.monday.com/forms/f8fc70e961cc2d22488a3210385daaab?r=use1

But even better is if we could embed:

<iframe src="https://forms.monday.com/forms/embed/f8fc70e961cc2d22488a3210385daaab?r=use1" width="650" height="500" style="border: 0; box-shadow: 5px 5px 56px 0px rgba(0,0,0,0.25);"></iframe>

**Comment by bamader** [comment]
@victoriasuwardiman @RyanHansz do we have a link for the how-to guides button?

**Comment by bamader** [comment]
@RyanHansz @victoriasuwardiman It looks like the how-to guides link in the AC is going to a page not found?

**Comment by bamader** [comment]
Also at the desired width of the iframe it expands quite far beyond the boundaries of the card on its half of the page. Do we want to still keep this two column format for the cards if we're embedding the form directly on the page?

**Comment by RyanHansz** [comment]
@bamader - that's the url that this page will exist on

and I will update with the design to accommodate the embedded form

**Comment by RyanHansz** [comment]
@bamader lets' keep the original design for the help page and put the embedded form on its own separate page:
![request-form](https://user-images.githubusercontent.com/63253539/103942762-e511db00-50fe-11eb-9497-6f4107f3d7dd.gif)

**Comment by RyanHansz** [comment]
@bamader

**Comment by RyanHansz** [comment]
@bamader reopened this to be QA'd. Also it doesn't look complete on devsecure (no buttons)?
<img width="1040" alt="Screen Shot 2021-01-08 at 10 19 09 AM" src="https://user-images.githubusercontent.com/63253539/104031659-00cabf00-519b-11eb-9a28-27b995f6395c.png">

**Comment by jlhogan** [comment]
I was testing file upload in devsecure (it has diff DB than other envs, so wanted to make sure i was testing prod-like) which may have overwritten deploy of top of base. Let me push that again so we're all working from the same place

**Comment by JordanGuinn** [comment]
Looks like this was completed with https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1017, so marking as closed.
