### ISSUE TITLE
Update no age group section

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#701]
Updated this to simplify. 
<img width="1225" alt="Screen Shot 2020-11-09 at 3 25 05 PM" src="https://user-images.githubusercontent.com/63253539/98592505-d1cdc500-229f-11eb-9247-40082dbb70ec.png">

- Change no age-group section to "incomplete enrollments". 
- Deleting the child record if the user navigates away before finishing, but to preserve the data if the user is logged out or needs to refresh the page. 

Not for this ticket: We can revisit how we're handling this in the future to avoid unintentionally created incomplete enrollments (a confirmation modal when you navigate away asking if you want to save the in-progress enrollment? )

**Comment by mmazanec22** [comment]
Thinking through the implications here-- my hunch would be that we might want to implement this by deleting the child if the user navigates away before finishing, but to preserve the data if the user is logged out or needs to refresh the page.  Ryan does that sound right?

**Comment by jlhogan** [comment]
but how do we know that the user navigates away from the page? IMO this should not be a point in time requirement
