### ISSUE TITLE
Data is stale after batch uploading a new file.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#702]
When I already have data in my roster and batch upload a new file, the new data does not appear until I refresh my browser.

![Stalebatchupload](https://user-images.githubusercontent.com/63253539/98594355-8a950380-22a2-11eb-9a45-707752ccef17.gif)

**Comment by jlhogan** [comment]
https://github.com/vercel/swr/discussions/525 try this instead of `cache.clear()` on upload?
