### ISSUE TITLE
As a user, I have a secure method to receive my ECE Reporter password.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#703]
I am sent a password through a secure method that I can then use to login to ECE reporter.

For product partners - share through onboarding call

**Comment by jlhogan** [comment]
@RyanHansz do we think 14 days expiration is long enough to have confidence that providers will engage with the link & retrieve their passwords? If a few fall through the cracks, that's fine and we can recreate accounts, passwords, and links for them but would be a bummer to do this for some significant number of users.

Most of the existing free options i am seeing have a max 14 day expiration. 

Many of these projects are open source, so if we determined we needed a longer exp time than that, we can run our own instance of the tool and tweak expiration times (sean offered to support us with this, so wont eat up team resources for product development, and also should be relatively quick and easy to do)
