### ISSUE TITLE
When batch uploading withdrawn records, they are shown in the active roster.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#715]
<img width="1137" alt="Screen Shot 2020-11-10 at 2 25 41 PM" src="https://user-images.githubusercontent.com/63253539/98723626-a19a2b00-2360-11eb-8672-270ec1320ebf.png">
<img width="1138" alt="Screen Shot 2020-11-10 at 2 25 34 PM" src="https://user-images.githubusercontent.com/63253539/98723627-a232c180-2360-11eb-8a25-b8e73454ac22.png">

**Comment by mmazanec22** [comment]
If not showing withdrawn enrollments is part of AC for #291 , then let's just include that in there and close this ticket, since there hasn't been work merged yet on withdrawn enrollments at all
