### ISSUE TITLE
When I attempt to submit data to OEC that is incomplete, I am scrolled to the top of the page and see an error alert.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#751]
Instead of disabling the submit button, it is always enabled. 

When a user hits the button with errors in their roster, the warning message with the "update your roster" header turns into an error.

Hide the bottom bar when the user has no data entered. 

![Submit-error](https://user-images.githubusercontent.com/63253539/98976299-3037b500-24e5-11eb-9560-d54209b77eca.gif)

**Comment by RyanHansz** [comment]
@bamader is this blocked by anything? Noticed its been in review for 2 weeks

**Comment by bamader** [comment]
Nope, it's just waiting on another review. When I first put up the PR we wanted to prioritize bugs over new features so it got put on the backburner, but I think it should be good to go now. So plug for @mmazanec22 and @JordanGuinn for review on https://github.com/ctoec/data-collection/pull/851 👀
