### ISSUE TITLE
Accordion toggle should only be button, not entire header

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/data-collection#760]
- Also change "hide/show [age group] roster" text to just read "hide/show"

**Comment by RyanHansz** [comment]
Looks like these lost the link styling (blue color and pointer on hover to show that it's interactive):

![Screen Shot 2021-01-20 at 9.10.48 AM.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/9959c6cb-f601-40c4-b223-27cdfde26d7a)

![Screen Shot 2021-01-20 at 9.12.54 AM.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/45dba7c0-0db2-4cd1-8350-48a619aac7ee)
