### ISSUE TITLE
When batch uploading a record with multiple enrollments, two separate child records are being created.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#762]
@jlhogan feel free to add more to this one

**Comment by bamader** [comment]
I can't repro this locally or in staging. Here's the sample data sheet I'm using. In particular, I made two of the rows (5 and 6 when viewing in Excel, not sure if other programs will change the header row) be the same enrollment but have changes apply to it in both the age group and the care model type. The results I'm seeing show the correct number of enrollments displayed (3 past, 1 current) and have the updated version of one of the past enrollments. Here's an excerpt from staging showing what I think is the correct output:

<img width="861" alt="Screen Shot 2020-11-13 at 2 23 35 PM" src="https://user-images.githubusercontent.com/49412165/99112795-3cdb0c80-25bc-11eb-83e1-d48ee0fd8558.png">

[Historical_Update_Small.xlsx](https://github.com/ctoec/data-collection/files/5538913/Historical_Update_Small.xlsx)

**Comment by jlhogan** [comment]
also can't repro....
