### ISSUE TITLE
Single or double column styling for funding legend on Roster?

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#772]

**Comment by victoriasuwardiman** [comment]
![image](https://user-images.githubusercontent.com/51121888/99099192-10b59080-25a8-11eb-93e8-bfb764debbcb.png)

**Comment by RyanHansz** [comment]
@victoriasuwardiman there's an updated design for this in this ticket:
https://github.com/ctoec/data-collection/issues/671
Let me know if you have ideas for making that new design better!
