### ISSUE TITLE
Error modal flags multiple enrollment rows with missing info

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#792]
Uploading sample data shows:
<img width="776" alt="Screen Shot 2020-11-16 at 5 57 10 PM" src="https://user-images.githubusercontent.com/63253539/99318148-27bce280-2835-11eb-9614-abfbd62437ed.png">

**Comment by RyanHansz** [comment]
@bamader is this change in staging? I'm still getting the error

**Comment by bamader** [comment]
I'm trying to test it out and explore as we speak but staging isn't loading for me (just a lot of flashing in the URL bar on the login page). Trying to start up local now to see if I can repro.
