### ISSUE TITLE
Batch upload does not work in Internet Explorer :(

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#794]
(Apologies to whoever picks this up)

When I batch upload a file in internet explorer, the screen goes blank

**Comment by mmazanec22** [comment]
:cry: any hints about what version of IE and Windows?

**Comment by RyanHansz** [comment]
Windows 10 and IE 11

**Comment by mmazanec22** [comment]
Also need to make click target entire file upload area rather than just the label in IE

**Comment by jlhogan** [comment]
seems like the `content-type` header which is automatically added to the request in other browers is missing from the request when sent from IE
