### ISSUE TITLE
Missing family income does not have error styling in batch editing

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#800]
When income determination form is displayed in batch editing due to entirely missing income determination (as opposed to income determination exists, but is missing fields), the error styles are missing on the form. 

- update form status func for income determination form to display error styles when there is no det in batch editing (should not display error styles when user is creating a new income determination)
- Also remove default date being set to today (this makes it look like this is an incomplete income determination rather than a missing one)
<img width="421" alt="Screen Shot 2020-11-17 at 2 19 50 PM" src="https://user-images.githubusercontent.com/63253539/99437083-fc430200-28df-11eb-9bfd-1ad99da43dad.png">

**Comment by jlhogan** [comment]
what does this mean, specifically. Missing family income, or a family income with missing fields will result in the form being present in the batch edit step list from my tests

**Comment by RyanHansz** [comment]
They don't show the validation styles for missing info (red border etc)

**Comment by jlhogan** [comment]
ahhhh ok! that makes sense -- if the record has no income determination at all, the form will show up but without error styles

**Comment by RyanHansz** [comment]
@bamader unless you're almost done with this, can we switch to #870?

**Comment by bamader** [comment]
Yes can definitely switch! I actually realized a fast follow we need for the stability of one of our e2e tests, so I'm working on that right now and haven't started this ticket at all. The e2e change should be done here pretty shortly so when it is I'll hop over to #870 .
