### ISSUE TITLE
Better support adding historical enrollments in the app

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#801]
Since OEC is asking for data from July to the current day, users need to be able to add entire past enrollments to children's records.

Add the following text to the enrollment and function section of adding a record:
<img width="921" alt="Screen Shot 2020-11-17 at 2 29 49 PM" src="https://user-images.githubusercontent.com/63253539/99438124-5c867380-28e1-11eb-8525-91cae02cd8c7.png">

![Add-past-enrollment](https://user-images.githubusercontent.com/63253539/99433065-09112700-28db-11eb-89ee-e28b8f47329b.gif)

- Include an "add a past enrollments button on the enrollment and funding section.
- Past enrollments label and the "add a past enrollment" button should always be visible
- Clicking on the "add past enrollment button" should open a modal that allows users to add all fields to a new past enrollment record.

**Comment by jlhogan** [comment]
while in here, should the `change enrollment` button switch to `Add a new enrollment`, and should that button also open a modal rather than an in-page form ?

**Comment by RyanHansz** [comment]
> while in here, should the `change enrollment` button switch to `Add a new enrollment`, and should that button also open a modal rather than an in-page form ?

Sure if it doesn't add much work!
