### ISSUE TITLE
Staging is inaccessible in many browsers

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#806]
Currently cannot access staging in:
Chrome
Chrome incognito
Safari
Edge

**Comment by jlhogan** [comment]
don't have safari or edge, but can't repro for chrome -- we recently updated some security policies for the load balancer that disallows insecure connections, which means some old browsers are not going to work.

**Comment by RyanHansz** [comment]
Ok, things seem to be working in Browserstack. Are there any workarounds other than using Safari incognito?

Also, Amelia mentioned you had a paid account in BrowserStack from a long time ago, are you able to access it?

**Comment by mmazanec22** [comment]
I think I figured this out, have a fix in the IE branch

**Comment by jlhogan** [comment]
skylight does have a paid account, I need to shut down the free one we've been using to access the paid one. I will do that asap, sorry i wasn't prioritizing it but realize that means you can't see browserstack stuff.
