### ISSUE TITLE
Clicking cancel on the batch upload error modal should clear the selected file for upload

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#807]
**As a user who:**

- Uploads a file
- Sees that there are errors
- Goes back to re-upload a file

The selected file should be cleared so I can upload the same file after I've made updates.

<img width="1031" alt="Screen Shot 2020-11-18 at 9 30 37 AM" src="https://user-images.githubusercontent.com/63253539/99543101-c570f880-2980-11eb-8365-5b36df7e49c7.png">
<img width="903" alt="Screen Shot 2020-11-18 at 9 30 33 AM" src="https://user-images.githubusercontent.com/63253539/99543103-c570f880-2980-11eb-87c6-a18fcdff70f2.png">

**Comment by mmazanec22** [comment]
I ditched the way we were doing this because IE was mad about changing an event (and we also prob shouldn't do that).  We can make the file input in the component library a controlled component to fix this.
