### ISSUE TITLE
Multi-site tab-nav fixes

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#812]
- some sites are not visible (appear hidden behind the empty roster alert), 

- the site dropdown isn't styled, 

- and a site selected from drop-down isn't being brought to the front of the site tabs

- Truncated (...) site names need to show in full in a tooltip when the user hovers on that tab

![image](https://user-images.githubusercontent.com/63253539/99677136-60340a80-2a47-11eb-9125-2e5d4b2f1627.png)

![image](https://user-images.githubusercontent.com/63253539/99677168-688c4580-2a47-11eb-991d-26ce51bcfb20.png)

**Comment by jlhogan** [comment]
but also -- should we rename these sites to not all start with `TVCCA LIttle Learners/head Start` ?

**Comment by RyanHansz** [comment]
Definitely

**Comment by jlhogan** [comment]
will do that now

**Comment by RyanHansz** [comment]
@jlhogan can you also look at the add child button dropdown? I can't see it but it seemed like it was buggy when Hartford tried it.

**Comment by mmazanec22** [comment]
@RyanHansz I had opened a ticket about dropdown styling needing some design help: https://github.com/ctoec/data-collection/issues/669

**Comment by RyanHansz** [comment]
@mmazanec22 Can you take a look at prod? Its less about the styling, more about the dropdown being obscured by other content.

Otherwise using the styles here is a fine starting point:
https://ctoec.github.io/component-library/?path=/story/buttonwithdropdown--default
