### ISSUE TITLE
Data Definitions updates

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#821]
# [Design](https://share.goabstract.com/9aa5ea35-8875-4f70-b05a-eb7524db8e7f)
![Datarequirements](https://user-images.githubusercontent.com/63253539/100618527-f4289080-32e9-11eb-9b85-4fa625149e93.png)

## **Meta:**
- Add Version # on the data template filename
- Add tags for Required, optional, required if (show in designs)
- Add radio buttons to choose between viewing all/only required fields
- Add unknown/not collected to all boolean fields that have that option
- Prepend "optional" to any optional field in the data template

### Update header section:
- see design for content

## **Required if fields:**
- Last funding reporting period
- Enrollment end date
- Enrollment exit reason

## **Change to optional**
- Care model
- Homelessness status
- Disability services
- Foster youth
- Birth Certificate fields (type, ID#, town of birth, state of birth)

## Data field updates
**SASID / Unique Identifier** 
- Update data definition:
  - "A unique number used to identify children. Either an SDE-backed SASID created from the PSIS system or another unique identifier from a system of record such as Childplus."

**Race**
- Add "other race" option

**Space type**
 - Replace format section with a link "See contract spaces for the full list of accepted space types." 

**First funding reporting period** 
- (Full-table width) Slim info alert with "Record 07/2020 for any child whose funding began in or before July 2020."

**Last funding reporting period** 
- required if tag + text:
"Only required for  children who: 
• Withdrew,  
• Changed age group and/or site. 
• Changed funding  source"

**Enrollment End Date and exit date:**  
- required if tag + text:
"Only required for  children who: 
• Withdrew,  
• Changed age group and/or site. 

**Enrollment end date**
  - **Update definition:**  The last date the child attended services at a site **or** the last date the child received services before changing age groups.

**Comment by jlhogan** [comment]
Some things remain unclear here: 
- should "getting started" still exist? or is it just "home" now?
- should home/getting started be the truncated content shown in the 2nd page of the designs? If so, do we want to add any language about adding records directly via the tool? or only invite users to do batch upload?

**Comment by RyanHansz** [comment]
No changes to the getting started page for this round of updates. 

Since the data requirements page has to stand on its own for a while I added some of the context that people won't be able to see yet.

**Comment by jlhogan** [comment]
got it !

**Comment by jlhogan** [comment]
small nit-picky question: All rows have options for values listed in the "format" section EXCEPT exit reason, where they're listed in the "definition" section. do we want to keep this? Also, I can make all the lists of options be bulleted lists in format or definition section, if that's preferable.

**Comment by RyanHansz** [comment]
Makes sense to move the exit reasons to the format column, and let's try a bulleted list, might help separate the options a bit
