### ISSUE TITLE
error boundary goes away when user navigates to new page

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#834]
- Update error boundary to say "refresh the page"?

**Comment by mmazanec22** [comment]
@jlhogan can you elaborate on this one a bit?  My understanding is that this is the desired behavior for an error boundary, so that a user can continue to use the application even if they run into an issue

**Comment by jlhogan** [comment]
oh yeah my verbiage was confusing. I meant: Make the error boundary go away when user navigates to a new page (because currently, it does not)
