### ISSUE TITLE
Decide how to handle extra specific zip codes (XXXXX-XXXX)

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#837]
Currently, we enforce that zip codes can only be 5 numbers long. If any more info is supplied, we cut off everything but the first five numbers. Decide if we want to store these instead. If we want to continue enforcing the 5-number format, add a test to parse.test.ts that runs a check against this case.

**Comment by RyanHansz** [comment]
Handled for now, we accept both the 5 digit and the longer one, but only display 5 digits in the app
