### ISSUE TITLE
display all reporting periods

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#842]
for initial data collection, we can expect users to be adding historical records with historical fundings. 
for now, show all reporting periods

**Comment by RyanHansz** [comment]
@jlhogan will this get rid of the need for https://github.com/ctoec/data-collection/issues/905?

**Comment by jlhogan** [comment]
no, this is literally just what options we show the user in the reporting period drop downs ( which is already done, so this should be closed). 905 speaks to actually doing smart handling of pre-07/2020 dates on behalf of the user in batch upload flow. I would imagine right now that if you tried to put in reporting period before 07/2020, it just ends up empty? 
we can also just.... add more historical reporting periods. I don't know where the requirement that we force data to be from 07/2020 necessarily came from, but that is up to u! :) (or up to someone, rather)
