### ISSUE TITLE
Withdraw is not working

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#845]
![image](https://user-images.githubusercontent.com/63253539/100779799-e4d34100-33d6-11eb-9aef-7dd4b84b3638.png)
Context: Shared by TVCCA at 11:53 today (12/1)

**Comment by jlhogan** [comment]
cannot reproduce in non-prod environments -- backup devsecure from prod to attempt repro

**Comment by RyanHansz** [comment]
TVCCA seemed to be able to withdraw records now, closing this unless it shows up again
