### ISSUE TITLE
Change button text from "past enrollments" to "roster for a past month". Remove bolding on "export roster"

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#849]
On the roster, in the views section:
<img width="235" alt="Screen Shot 2020-12-01 at 3 58 14 PM" src="https://user-images.githubusercontent.com/63253539/100796100-258a8480-33ee-11eb-8f03-928692f9047d.png">

<img width="673" alt="Screen Shot 2020-12-29 at 11 55 03 AM" src="https://user-images.githubusercontent.com/63253539/103300369-babc7100-49cc-11eb-9dc9-727365a90550.png">

**Comment by mmazanec22** [comment]
@RyanHansz do we want the file download button to be bold anywhere in the app?

**Comment by RyanHansz** [comment]
@mmazanec22 they can all be normal weight for consistency's sake. Except the download button on the template page, which doesn't need the underline:
<img width="325" alt="Screen Shot 2020-12-30 at 3 36 17 PM" src="https://user-images.githubusercontent.com/63253539/103379772-c2efdb80-4ab4-11eb-9781-40b8a1b8b397.png">
