### ISSUE TITLE
Roster is in infinite rendering loop after adding child with missing info

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/data-collection#860]

**Comment by jlhogan** [comment]
I'm in process of making a few changes to roster queries to fix a diff bug; i can pick this up

**Comment by jlhogan** [comment]
how do you "add child with misisng info" since the steplist blocks progression unless all required info is provided? By using back button?

**Comment by mmazanec22** [comment]
Lol by running into the https://github.com/ctoec/data-collection/issues/859 bug-- probably just navigating away mid-process works though?

**Comment by mmazanec22** [comment]
I should note that I'm not sure whether this is only an issue for children with missing info or if something else caused it, that's just when it started happening for me

**Comment by jlhogan** [comment]
hm, can't figure out how to repro.

**Comment by mmazanec22** [comment]
It seems to be happening when I click on the incomplete child record link in the roster
