### ISSUE TITLE
Enrollment and funding updates (remove unfunded)

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#863]
- Remove unfunded option from funding types in add record flow and when changing enrollments in a child record
- Add the following alert at the top of the section:
<img width="867" alt="Screen Shot 2020-12-03 at 2 18 52 PM" src="https://user-images.githubusercontent.com/63253539/101077203-85aa3380-3572-11eb-9d9c-445cbe897bcd.png">
"Adding a child who has withdrawn, changed sites or age groups? Add their earliest enrollment then make changes from the child’s record in your roster."

**Comment by mmazanec22** [comment]
Addressed in #866
