### ISSUE TITLE
Unable to change enrollment in a child record

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#870]
In staging:
<img width="1234" alt="Screen Shot 2020-12-04 at 7 25 16 AM" src="https://user-images.githubusercontent.com/63253539/101163670-ec2a6280-3601-11eb-8e13-cbfb14cdd87a.png">

**Comment by bamader** [comment]
To be investigated by the restoring to dev secure, so unassigning and moving back to current sprint

**Comment by RyanHansz** [comment]
![Changeenrollment](https://user-images.githubusercontent.com/63253539/101512984-a3e4aa80-3949-11eb-9315-900b653df93a.gif)
