### ISSUE TITLE
Home page updates (pre-complete data)

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#873]
When I log into ECE Reporter I see:
[This design](https://share.goabstract.com/42315efe-ac59-43d4-aea1-f47b0cbf4428?collectionLayerId=f14fea62-ba34-4153-9d2b-1885f9f3b99b&mode=design)

<img width="632" alt="Screen Shot 2020-12-04 at 2 47 18 PM" src="https://user-images.githubusercontent.com/63253539/101208108-aa201180-363f-11eb-9450-3424c4aa2d75.png">

- I can see the steps to upload data in ECE Reporter
- I can see the sites I manage in ECE Reporter
- I can see the how-to guide at: https://ece-reporter.documize.com/s/burrnubmbdja9sqnbh6g/ece-reporter-help/d/bv34kdhmdesjli7los1g/how-to-prepare-your-data-for-ece-reporter

**Comment by RyanHansz** [comment]
A reminder for where to copy content in abstract:
<img width="977" alt="Screen Shot 2020-12-04 at 2 17 07 PM" src="https://user-images.githubusercontent.com/63253539/101205332-780cb080-363b-11eb-9a1a-60a83e26c899.png">

**Comment by RyanHansz** [comment]
@bamader a few quick styling updates to make the list easier to read:
<img width="669" alt="Screen Shot 2020-12-16 at 12 12 52 PM" src="https://user-images.githubusercontent.com/63253539/102382199-2bf53080-3f98-11eb-8281-61f379de95ec.png">
<img width="723" alt="Screen Shot 2020-12-16 at 12 12 32 PM" src="https://user-images.githubusercontent.com/63253539/102382200-2bf53080-3f98-11eb-850f-d1af88bf26ad.png">

**Comment by RyanHansz** [comment]
Also link to data requirements page is resulting in an error for me on staging and qa

**Comment by RyanHansz** [comment]
![Dec-16-2020 12-21-36](https://user-images.githubusercontent.com/63253539/102383232-51cf0500-3f99-11eb-981d-8480b0de19f2.gif)

**Comment by RyanHansz** [comment]
Also also, link to the how to guide is going to: https://staging.ece-fawkes.ctoecskylight.com/https://ece-reporter.documize.com/s/burrnubmbdja9sqnbh6g/ece-reporter-help/d/bv34kdhmdesjli7los1g/how-to-prepare-your-data-for-ece-reporter

Instead of the actual link

**Comment by mmazanec22** [comment]
I left this comment in the code and was going to eventually add it to the tweaks column but hopping on board this reopened ticket: the numbered list should really be implemented with an ordered list component under the hood, since that's visually what we're showing.

**Comment by bamader** [comment]
Oh wow looks like a lot of things aren't quite right on this one. I'll get back on this.

**Comment by jlhogan** [comment]
@bamader i have a fix for the data-requirements error in a branch

**Comment by bamader** [comment]
@RyanHansz What version of IE do we expect OEC to use? I just learned that one of the styling attributes needed to achieve the purple circles around the numbers in the ordered list isn't supported in IE8 and below.

**Comment by RyanHansz** [comment]
I don't know 100%, but OEC has larger problems if they're using anything older than v10

**Comment by mmazanec22** [comment]
Brandon is the list still usable and readable in IE 8?  IMO graceful degradation is a reasonable goal in this case

**Comment by bamader** [comment]
Just did some experimenting and it looks like yes, the list is both functional and readable still. The property that IE8 and lower doesn't support is the border-radius one, so instead of getting aesthetically pleasing circles we get square boxes instead. But everything still _seems_ like it's centered and spaced appropriately, so I think we're probably okay on the degradation front.
