### ISSUE TITLE
Home page updates (after Dec/July data is complete)

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#875]
After I've notified OEC that my data is complete, the home page changes to 

[Design](https://share.goabstract.com/42315efe-ac59-43d4-aea1-f47b0cbf4428?collectionLayerId=d55236a0-df7a-439c-862f-28e7018d9c72&mode=design)

<img width="553" alt="Screen Shot 2020-12-04 at 2 52 58 PM" src="https://user-images.githubusercontent.com/63253539/101208643-7691b700-3640-11eb-9c81-b1a6f85749c1.png">

- In the header section, I see my program name with: 
    - the number of active enrollments
    - A button to add a new enrollment
      - When I add a new enrollment from the home page, the back button returns me to the homepage. When I finish adding the child, I am still shown the roster with a confirmation message 
    - A link to view my roster

- In the Updates and tasks section I see:
  - A message with tips on how to keep data updated (see abstract for content)
  - A message to provide feedback on my experience using ECE Reporter (link to come)
   - Hide this message once a user has clicked the "give feedback" button

- [ ] In the funding spaces section I see ( #883):
  - A card with each funding source
  - A list within that card with each funding type and active utilization numbers

- [ ] In the sites section I see (#884):
  - A card with each site I manage
   - A total active enrollment count
   - A link to view my roster for that site

**Comment by bamader** [comment]
@RyanHansz What sections do #883 and #884 refer to? The Home page as of now (for pre-submitted orgs) doesn't have a funding spaces section or a section of site cards?

**Comment by RyanHansz** [comment]
@bamader saw your comment and added more details about the funding and site sections. They do not currently exist in any form on the homepage.

**Comment by RyanHansz** [comment]
@bamader also, we're holding off on the feedback module until the link to whatever tool we're using is ready. Which I will be pushing for by the end of next week.

**Comment by RyanHansz** [comment]
Hi @bamader just reopened these homepage updates so we can QA them as a team

**Comment by bamader** [comment]
@JordanGuinn I believe this can also be closed (same reason I described in the funding space cards ticket)
