### ISSUE TITLE
Roster empty state updates

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#877]
When I go to my roster before any data is added to it:
[Design](https://share.goabstract.com/42315efe-ac59-43d4-aea1-f47b0cbf4428?collectionLayerId=53aac75b-10a9-4a94-b18f-ed35d4e3c47f&mode=design)

<img width="551" alt="Screen Shot 2020-12-07 at 1 52 29 PM" src="https://user-images.githubusercontent.com/63253539/101392276-8ce38100-3893-11eb-883e-c24a1703f9ec.png">

- The views, actions, bottom-button bar and tab-nav are hidden
- The info alert text is updated to let users know about both file upload and adding records individually

When I go to a site roster with no records, I see:
<img width="549" alt="Screen Shot 2020-12-07 at 1 54 04 PM" src="https://user-images.githubusercontent.com/63253539/101392445-c87e4b00-3893-11eb-9b9e-41fc1252b11b.png">

**Comment by jlhogan** [comment]
> views, actions, bottom-button bar and tab-nav are hidden

this makes me think we are talking about a state where there is _NO_ data at all for the user (as opposed to the state where a single site-filtered roster is empty). What if anything should happen in that instance? should the alter also be updated to include the uploading a file CTA?

**Comment by RyanHansz** [comment]
Made some updates to the designs to separate No data from a single site without data. 

From my view, the change is that the controls (Actions, views, tab-nav, bottom-bar) are hidden when there's no data. For a single site without data, those controls are shown, and the placeholder module only shows up on the site without any data.

**Comment by mmazanec22** [comment]
Potential accessibility concern that needs to be looked into: https://www.w3.org/WAI/WCAG21/Techniques/failures/F31.html

**Comment by RyanHansz** [comment]
@mmazanec22 is that referring to the button links? If so, I updated the design to use the same label as the action section.

**Comment by RyanHansz** [comment]
For reference: Phoebe coded a prototype of this page here:
https://github.com/femmebot/supreme-barnacle
