### ISSUE TITLE
Home page updates - Funding spaces

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#883]
<img width="1036" alt="Screen Shot 2020-12-30 at 9 20 13 AM" src="https://user-images.githubusercontent.com/63253539/103357044-3aefde80-4a80-11eb-9683-0be31a366b6c.png">

[Design](https://app.abstract.com/projects/0b680217-1135-4908-a9e9-2ffb268d1191/branches/448b79b1-7299-4fe7-9daa-7b71a6490d25/commits/c0e47953916a073d9fadf9f5766e690b674c9f94/files/684c82ac-0f66-4268-9d27-763f98935625/layers/8F9D955B-1F62-41AF-9492-19E0B0CFCC8A?collectionId=f963e7c4-ce33-49a5-a417-99451bf45054&collectionLayerId=d55236a0-df7a-439c-862f-28e7018d9c72&mode=design)

- Do not display this section for users with multiple organizations
- Display this section for users who have organization-level permissions
- Calculate the total funding space usage, grouped by funding source, age group then space type

**Comment by JordanGuinn** [comment]
@RyanHansz @bamader @jlhogan Is this issue completed?  I see that it was closed with https://github.com/ctoec/data-collection/pull/971, but it then looks like it was promptly reopened?

**Comment by bamader** [comment]
@JordanGuinn Yes, this issue was done. I think it got re-opened because there was a small bug in staging that prevented it from showing up properly, but we must've pushed the fix without re-linking the issue.
