### ISSUE TITLE
Home page updates - sites

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#884]
<img width="1028" alt="Screen Shot 2020-12-30 at 9 22 46 AM" src="https://user-images.githubusercontent.com/63253539/103357198-95893a80-4a80-11eb-883c-f27d5a340c14.png">

# [Design](https://app.abstract.com/projects/0b680217-1135-4908-a9e9-2ffb268d1191/branches/448b79b1-7299-4fe7-9daa-7b71a6490d25/commits/c0e47953916a073d9fadf9f5766e690b674c9f94/files/684c82ac-0f66-4268-9d27-763f98935625/layers/8F9D955B-1F62-41AF-9492-19E0B0CFCC8A?collectionId=f963e7c4-ce33-49a5-a417-99451bf45054&collectionLayerId=d55236a0-df7a-439c-862f-28e7018d9c72&mode=design)

- Display all sites a user has access to in cards across three columns, sorted by name A-Z
- I can click a "view site roster" button link with an arrow that takes me to my roster view with that site selected

**Comment by RyanHansz** [comment]
@bamader can we QA this as a team before officially closing it? I'm not seeing the changes in staging or QA

**Comment by bamader** [comment]
Yeah wtf the change is only like half there. Let me investigate.

**Comment by bamader** [comment]
@JordanGuinn Any reason this issue is still open? It should've closed with a merged PR a little while ago.

**Comment by JordanGuinn** [comment]
Nope!  I'll close it now.
