### ISSUE TITLE
Batch Upload doesn't parse 'Y' and 'N' for undefinable booleans

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#885]
There are a number of fields in the template that use undefinable booleans but allow users to enter in more than just the three ways Yes/No/Unknown (i.e. fields like dualLanguageLearner, hispanicOrLatinxEthnicity, foster, receivesDisabilityServices, etc. all have Yes, Y, No, N as valid inputs in the sheet instructions). Rows that are uploaded with anything but Yes or No in these columns are not parsed or saved as children to the roster.
* Just needs a `mapEnum` to be applied to each field (since UndefinableBoolean is an enum now) before instantiating the Child object and trying to save it to the DB

**Comment by jlhogan** [comment]
for clarity: `enumTransformer` in the server code is a specifically a thing for typeorm to use enum key strings as the DB values. It has nothing to do with parsing logic

**Comment by bamader** [comment]
Yeah that was a typo on my part, I meant `mapEnum`
