### ISSUE TITLE
Incomplete enrollments are shown in the withdrawn roster instead of the active roster.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#886]
<img width="1276" alt="Screen Shot 2020-12-08 at 11 25 45 AM" src="https://user-images.githubusercontent.com/63253539/101510675-35ebb380-3948-11eb-90ec-51e1b8b9a359.png">

**Comment by bamader** [comment]
Can't repro this locally, in staging, or in QA. It's likely that one of our merges fixed this and the deployment to prod was just behind.
