### ISSUE TITLE
Add feedback module to landing page 

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#897]
<img width="751" alt="Screen Shot 2020-12-09 at 7 34 50 AM" src="https://user-images.githubusercontent.com/63253539/101630607-1d83a380-39f1-11eb-95cd-080249145c00.png">

Copy and SVG illustration can be found [here](https://share.goabstract.com/42315efe-ac59-43d4-aea1-f47b0cbf4428?collectionLayerId=1e3d0f67-25e0-4421-aaf1-f4be42491705&mode=build)

- Replaces:
![Screen Shot 2021-01-20 at 9.02.32 AM.png](https://images.zenhubusercontent.com/5f6e38ea084e48ea4bed8071/6ab0a1ed-271b-40f9-90c2-237de911de5c)

**Comment by victoriasuwardiman** [comment]
Here is the link! https://forms.monday.com/forms/f5bcf5d3d611b99f45ffb8187cd6c2b9?r=use1

Ryan, I made a few changes because of Monday's features and to shorten it a bit. See what you think

**Comment by JordanGuinn** [comment]
## Test Cases
- [ ] All e2e tests are passing
- [ ] "Hello <-username->!" header is present
- [ ] Feedback module is present on landing page
- [ ] Feedback module matches design
- [ ] "Give Feedback" button opens monday.com form

**Comment by JordanGuinn** [comment]
This is ready for merge/deploy.
