### ISSUE TITLE
Determine home page display for multi-org user

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#909]
Currently, we have an h1 that says "Hello, [User name]!" and an h2 that says "Sites you manage at [org name]". We need to figure out how to display the h2 for users that are associated with multiple organizations. Displaying the list of sites for each organization below it could also be long and messy.

**Comment by RyanHansz** [comment]
Note: This issue will only occur for one user, so I'd advocate for whatever approach will close this fastest.
