### ISSUE TITLE
Get e2e tests running in IE/Edge

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#910]
edge: current blocked b/c file upload isn't working in edge driver, and is required for most tests at this point
potential fixes: 
- make file upload work in edge driver. Circa 2016 it was a known issue but may have been resolved. links to issues no longer exist b/c microsoft has sunset the support tool they used to use. This may have been fixed, worth maybe digging into a bit more if theres a newer driver version we're missing.
- for tests no explicitly testing the upload, make the file upload conditional on if data exists or not and then run these tests after the chrome tests, and data will already exist.

ie: apparently these are a mess, and are so slow, and are timing out. maybe there are ways to improve this.

**Comment by mmazanec22** [comment]
Other testing frameworks have a "run before all" feature that I'm wondering if we could look for here

**Comment by JordanGuinn** [comment]
Closing until we decide that application usage in Microsoft Edge/Internet Explorer is something we want/need to explicitly support (we do virtually zero testing of any sort in either browser).
