### ISSUE TITLE
Missing needed info: As a provider who has uploaded data, I can see when required fields are missing.

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#92]
## On each field required for data collection:
<img width="454" alt="Screen Shot 2020-08-31 at 3 05 25 PM" src="https://user-images.githubusercontent.com/63253539/91756835-67abec00-eb9b-11ea-9727-6cca1032a517.png">
classes in ECE Reporter: 

```
<span class="usa-warning-message" id="birthCertificateId-birthState-birthTown-warning" role="status"><span class="oec-inline-icon oec-inline-icon--incomplete">[SVG goes here]<span class="usa-sr-only">(incomplete)</span></span> This information is required for OEC reporting</span>

<div class=" usa-form-group usa-form-group--warning">
<label class="usa-label usa-label--warning" for="birthCertificateId">Birth certificate ID # </label>
<input class="usa-input usa-input--warning" type="text" id="birthCertificateId" aria-describedby="birthCertificateId-warning" aria-invalid="false" aria-required="true" value="">
</div>

```

<img width="1022" alt="Screen Shot 2020-08-31 at 3 12 30 PM" src="https://user-images.githubusercontent.com/63253539/91757503-6929e400-eb9c-11ea-9738-e3f83eef9fc3.png">

```

<span class="oec-inline-icon oec-inline-icon--incomplete">[SVG goes here]<span class="usa-sr-only">(incomplete)</span></span>


```

## On each child roster item with missing/needed info:
<img width="804" alt="Screen Shot 2020-08-31 at 3 06 54 PM" src="https://user-images.githubusercontent.com/63253539/91756954-9c1fa800-eb9b-11ea-9cfe-44e48fad4b72.png">

```
<span class="oec-inline-icon oec-inline-icon--incomplete">[SVG goes here]<span class="usa-sr-only">(incomplete)</span></span>

```

## On each child record section:
<img width="1023" alt="Screen Shot 2020-08-31 at 3 09 37 PM" src="https://user-images.githubusercontent.com/63253539/91757248-ffa9d580-eb9b-11ea-9d7c-635706844266.png">

## Alert on top of roster:
![Update roster](https://user-images.githubusercontent.com/63253539/92776698-806f8b00-f36d-11ea-8a2f-652887072f1c.png)

**Comment by jlhogan** [comment]
Let's chat about this before someone starts implementing -- we likely want to add a full validation layer, and want to think through when/where/how that layer lives in the rest of the request chain!
