### ISSUE TITLE
For an enrollment record without a funding and/or income associated, the batch edit shows a blank edit area

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/data-collection#937]
Repro steps:
1) Have a child record without a funding associated with enrollment (delete existing)
2) Notice alerts for missing information
3) Go back to Roster
4) Click batch edit link in alert
5) Click child record without funding

Result: blank edit area or completed state
Expected result: All of the required fields with form elements to complete

1) Have a child record without income associated with enrollment (delete existing)
2) Notice alerts for missing information
3) Go back to Roster
4) Click batch edit link in alert
5) Click child record without funding

Result: blank edit area or completed state
Expected result: All of the required fields with form elements to complete

![image](https://user-images.githubusercontent.com/51121888/102631172-6e934600-411b-11eb-9386-e33574c9f148.png)

**Comment by RyanHansz** [comment]
This may lead to the following error when you update the record: ![batch-edit-bugs](https://user-images.githubusercontent.com/63253539/102647689-2b919c80-4134-11eb-8498-eaf0020aa331.gif)
