### ISSUE TITLE
Update the header: Add sub-links to roster and batch-upload pages

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#94]
# [Designs](https://share.goabstract.com/f628fb10-aaa3-45d4-af7b-c2c255e44cc6)
• Rename title to ECE Reporter:
• When logged in, add sub-links for roster and batch-upload:
<img width="1101" alt="Screen Shot 2020-09-18 at 8 39 22 AM" src="https://user-images.githubusercontent.com/63253539/93598283-757ab300-f98a-11ea-9731-45e62c472fa7.png">

• Clicking the logo and ECE reporter section should take the user back to the getting started page.

**Comment by RyanHansz** [comment]
The header is simplified to save screen space. The data template link opens a submenu to choose template format. Data definitions links to [This page](https://app.abstract.com/share/5ea2033d-b4eb-4322-8a2a-1b601b77c8fc?collectionLayerId=6d13caae-038e-493e-a665-d7f176b34c11&mode=design&sha=6709b22394262daf7f1fd10ca749ac72a02ea7c6).

Feedback is an link URL: "mailto:oec-data-pilot@skylight.digital"

**Comment by cailyncodes** [comment]
Going to add a new component to the component library for this

**Comment by RyanHansz** [comment]
Menu for file types should open on hover.
Name should change to one line - ECE Data Collector
Logged out 
OEC logo should shrink to 36px width
[Design](https://share.goabstract.com/b8947201-0dea-4a03-896a-3fdc09d9e356)
