### ISSUE TITLE
Transfer Support content to an OEC repo

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#976]
<img width="1343" alt="Screen Shot 2020-12-30 at 10 03 36 AM" src="https://user-images.githubusercontent.com/63253539/103359683-4ba35300-4a86-11eb-9b23-f8c32c09879d.png">

Prototype help website:   https://ryanhansz.github.io/
- Transfer Prototype Repo: https://github.com/RyanHansz/RyanHansz.github.io to an OEC one
- Host at http://support.ece-reporter.ctoec.org/ if possible
- Styling tweaks to come later once the support website is up and running

**Comment by jlhogan** [comment]
done! https://github.com/ctoec/ece-reporter-support
