### ISSUE TITLE
Home page update - Show funding space types before a user has verified data

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#981]
Value: Lets users verify that we've added the correct sites and funding space combinations

<img width="1062" alt="Screen Shot 2021-01-07 at 3 26 03 PM" src="https://user-images.githubusercontent.com/63253539/103941311-aa0ea800-50fc-11eb-8336-651dd7249c86.png">

- Add a slim alert with a link to a form created in #1005  for users to suggest revisions to their data
- Do not show the funding spaces for multi-org users
- Use funding space cards and formatting from #875 
- Hide SR Capacity (we're not as confident in those numbers and they change often.
- Change intro copy to 
  - "ECE Reporter will allow you to share your state-funded enrollment data with the Office of Early Childhood (OEC). Make sure the site names and funding spaces below are accurate before you start entering data.
- Add a header with font-size of 26px: "Your managed sites and funding spaces"
- Add a "sites" header: 22px 
- Add a "funding" header: 22px
- divider line between funding info and How to use ECE Reporter section. 2rem margin-top and bottom on the divider
- Increase "How to use ECE Reporter" to 26px

Note #1028 to hide SR space totals

**Comment by bamader** [comment]
@RyanHansz If we're changing the sites part of the page to just be "Sites" instead of "Sites you manage at {orgName}", should we also hide the site section for multi-org users?

**Comment by RyanHansz** [comment]
@bamader yes, we can hide this section for the pre-submit multi-org user
