### ISSUE TITLE
Step Indicator UI Component: I can see my progress through a grouping of related pages

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#992]
## Background
Functional React component from Carbon: https://react.carbondesignsystem.com/?path=/story/progressindicator--default

Can likely be styled with USWDS classes; let's not worry too much about adherence to this design tho
https://designsystem.digital.gov/components/step-indicator/

**Comment by JordanGuinn** [comment]
Closing - migrated the acceptance criteria here to https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/992.
