### ISSUE TITLE
Make sections and individual fields link-able in data-requirements table

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#996]

**Comment by JordanGuinn** [comment]
@RyanHansz Linkable to what, exactly?  Or is this saying as a user, I should be able to traverse the contents of the table by appending selectors to the URL?

**Comment by jlhogan** [comment]
i made this ticket, and yes the latter. Like in-page hashes that link to the sections / fields -- easier for pointing people to things
